
"""BYS360 runtime schema contract.

Core Refactor Faz 3 notu:
- app/__init__.py sadece uygulama fabrikasi olarak kalir.
- Beklenen tablo/kolon sozlesmesi bu dosyada tutulur.
- Canli kapsam disi moduller burada pratikte ayiklanir; schema validation
  yalnizca aktif omurga icin calisir.
"""
from __future__ import annotations

from collections.abc import Iterable

EXPECTED_SCHEMA = {
    "users": {
        "sicil_no",
        "email",
        "password_hash",
        "ad",
        "soyad",
        "full_name_cache",
        "role",
        "role_label",
        "birim",
        "ust_birim",
        "yonetici_sicil",
        "ikinci_yonetici_sicil",
        "ucuncu_yonetici_sicil",
        "organization_unit_id",
        "is_active",
    },
    "organization_units": {
        "name",
        "unit_type",
        "parent_id",
        "manager_user_id",
        "sort_order",
        "is_active",
        "unit_code",
        "closed_at",
        "closure_reason",
        "successor_unit_id",
    },
    "performance_periods": {
        "title",
        "start_date",
        "end_date",
        "is_active",
        "results_published",
        "enable_level_3",
        "enable_level_3_scoring",
        "require_level_3_completion_for_final",
        "level_1_weight",
        "level_2_weight",
        "level_3_weight",
        "minimum_presence_days_for_evaluation",
        "leave_skip_threshold_days",
        "absence_skip_threshold_days",
        "auto_skip_if_fully_absent",
        "manager_delegation_required",
        "snapshot_status",
        "snapshot_generated_at",
        "snapshot_generated_by_id",
        "period_type",
        "scope_type",
        "scope_value",
        "special_reason",
        "allow_overlap",
    },
    "performance_weight_configs": {
        "period_id",
        "evaluator_1_weight",
        "evaluator_2_weight",
        "evaluator_3_weight",
        "level_3_enabled",
        "level_3_mode",
        "is_active",
    },
    "performance_evaluations": {
        "period_id",
        "employee_id",
        "status",
        "level_1_evaluator_id",
        "level_2_evaluator_id",
        "level_3_evaluator_id",
        "level_1_total_100",
        "level_2_total_100",
        "level_3_total_100",
        "final_total_100",
        "is_published_to_employee",
        "employee_score_viewed_at",
        "employee_score_acknowledged_at",
        "employee_score_acknowledged_note",
        "workflow_status",
        "level_1_submitted_to_level_2_at",
        "level_2_seen_level_1_at",
        "level_2_returned_to_level_1_at",
        "level_2_return_note",
        "level_2_returned_by_id",
        "level_1_last_resubmitted_at",
        "evaluation_exempted",
        "evaluation_exemption_reason",
        "employee_leave_days_in_period",
        "employee_absence_days_in_period",
        "employee_available_days_in_period",
    },
    "performance_evaluation_items": {
        "evaluation_id",
        "criteria_id",
        "manager_level",
        "score",
        "score_100",
    },
    "evaluation_assignments": {
        "period_id",
        "employee_id",
        "evaluator_id",
        "manager_level",
        "status",
        "original_evaluator_id",
        "delegation_id",
        "assignment_source",
        "coverage_note",
    },
    "leave_balances": {
        "user_id",
        "leave_type",
        "year",
        "total_days",
        "carried_over_days",
        "used_days",
        "manual_override",
        "note",
    },
    "personnel_leaves": {
        "user_id",
        "period_id",
        "leave_type",
        "status",
        "start_date",
        "end_date",
        "approved_day_count",
        "start_half_day",
        "end_half_day",
        "blocks_performance_evaluation",
        "performance_mode",
        "blocks_manager_duties",
        "description",
        "approved_by_id",
        "approved_at",
    },
    "announcements": {
        "title",
        "body",
        "announcement_type",
        "is_active",
        "is_required",
        "show_rule",
        "target_scope",
        "target_role",
        "target_unit_id",
        "publish_start_at",
        "publish_end_at",
        "button_text",
        "media_type",
        "media_url",
        "media_file_path",
        "cover_image_path",
        "cta_text",
        "cta_url",
        "created_by_user_id",
        "updated_by_user_id",
    },
    "announcement_reads": {
        "announcement_id",
        "user_id",
        "first_seen_at",
        "last_seen_at",
        "dismissed_at",
        "acknowledged_at",
        "seen_count",
        "ip_address",
        "user_agent",
    },
    "message_threads": {
        "thread_type",
        "subject",
        "badge_label",
        "icon_name",
        "accent_color",
        "created_by_user_id",
        "is_active",
        "last_message_at",
    },
    "attendance_exceptions": {
        "user_id",
        "period_id",
        "record_date",
        "exception_type",
        "status",
        "day_fraction",
        "blocks_performance_evaluation",
        "performance_mode",
        "blocks_manager_duties",
        "description",
        "approved_by_id",
        "approved_at",
    },
    "delegation_assignments": {
        "delegator_user_id",
        "delegate_user_id",
        "source_leave_id",
        "source_attendance_id",
        "status",
        "start_date",
        "end_date",
        "scope_type",
        "applies_level_1",
        "applies_level_2",
        "applies_level_3",
        "note",
        "approved_by_id",
        "approved_at",
    },
    "ai_request_logs": {
        "module_type",
        "feature_type",
        "target_table",
        "target_id",
        "user_id",
        "request_text",
        "response_text",
        "provider_name",
        "model_name",
        "prompt_version",
        "status",
        "latency_ms",
        "token_in",
        "token_out",
        "was_masked",
        "was_user_visible",
        "error_message",
    },
    "ai_recommendations": {
        "module_type",
        "target_table",
        "target_id",
        "recommendation_type",
        "title",
        "body",
        "severity",
        "status",
        "ai_request_log_id",
        "reviewed_by_user_id",
        "reviewed_at",
        "created_by_id",
        "updated_by_id",
    },
    "ai_feedback_logs": {
        "ai_request_log_id",
        "user_id",
        "feedback_type",
        "feedback_note",
    },
    "ai_redaction_rules": {
        "module_type",
        "field_name",
        "redaction_type",
        "replacement_text",
        "is_active",
        "created_by_id",
        "updated_by_id",
    },
    "ai_summary_cache": {
        "module_type",
        "target_table",
        "target_id",
        "summary_kind",
        "summary_text",
        "source_hash",
        "expires_at",
    },

    "repository_spaces": {
        "module_type",
        "name",
        "code",
        "description",
        "organization_unit_id",
        "parent_space_id",
        "visibility_level",
        "sort_order",
        "is_active",
        "is_archived",
    },
    "repository_folders": {
        "repository_space_id",
        "parent_folder_id",
        "name",
        "slug",
        "description",
        "folder_type",
        "sort_order",
        "is_active",
        "is_archived",
    },
    "documents": {
        "repository_space_id",
        "folder_id",
        "title",
        "description",
        "original_filename",
        "stored_filename",
        "storage_path",
        "file_extension",
        "mime_type",
        "file_size",
        "file_hash",
        "document_type",
        "version_no",
        "is_latest_version",
    },
    "document_versions": {
        "document_id",
        "version_no",
        "original_filename",
        "stored_filename",
        "storage_path",
        "file_extension",
        "mime_type",
        "file_size",
        "file_hash",
        "change_note",
        "is_current",
    },
    "media_albums": {
        "repository_space_id",
        "folder_id",
        "module_type",
        "title",
        "description",
        "album_date",
        "cover_media_id",
        "event_location",
        "visibility_level",
        "is_active",
        "is_archived",
    },
    "media_assets": {
        "album_id",
        "repository_space_id",
        "folder_id",
        "title",
        "description",
        "original_filename",
        "stored_filename",
        "storage_path",
        "thumbnail_path",
        "file_extension",
        "mime_type",
        "file_size",
        "file_hash",
        "media_type",
        "capture_date",
        "display_order",
        "is_active",
        "is_archived",
    },
    "attachment_links": {
        "module_type",
        "target_table",
        "target_id",
        "document_id",
        "media_asset_id",
        "media_album_id",
        "attachment_role",
        "is_primary",
    },
    "download_logs": {
        "user_id",
        "document_id",
        "media_asset_id",
        "module_type",
        "target_table",
        "target_id",
        "ip_address",
        "user_agent",
    },
    "access_policies": {
        "module_type",
        "target_table",
        "target_id",
        "role_name",
        "organization_unit_id",
        "user_id",
        "can_view",
        "can_upload",
        "can_edit",
        "can_archive",
        "can_download",
    },
    "education_categories": {"name", "description"},
    "education_providers": {"name", "provider_type", "contact_name", "contact_email", "contact_phone", "website", "notes"},
    "education_records": {
        "category_id",
        "code",
        "title",
        "description",
        "education_type",
        "status",
        "trainer_name",
        "trainer_title",
        "provider_id",
        "provider_name",
        "provider_contact_name",
        "provider_contact_email",
        "provider_contact_phone",
        "organizer_unit_id",
        "start_date",
        "end_date",
        "duration_hours",
        "duration_days",
        "duration_value",
        "duration_unit",
        "session_count",
        "delivery_method",
        "platform_name",
        "location",
        "target_audience",
        "participant_limit",
        "planned_participant_count",
        "actual_participant_count",
        "attendance_rate",
        "satisfaction_score",
        "satisfaction_response_count",
        "certificate_enabled",
        "certificate_count",
        "source_type",
        "learning_outcomes",
        "result_summary",
        "total_cost",
        "cost_per_person",
        "is_mandatory",
        "repository_space_id",
    },
    "education_feedbacks": {"education_record_id", "participant_id", "user_id", "overall_score", "content_score", "trainer_score", "organization_score", "recommendation_score", "would_recommend", "comment", "submitted_channel"},
    "education_sessions": {
        "education_record_id",
        "title",
        "session_date",
        "start_time",
        "end_time",
        "location",
        "notes",
    },
    "education_participants": {
        "education_record_id",
        "user_id",
        "source_type",
        "participant_name_snapshot",
        "sicil_no_snapshot",
        "unvan_snapshot",
        "unit_snapshot",
        "participation_status",
        "attendance_status",
        "certificate_eligible",
        "requires_tckn_for_export",
        "sort_order",
        "signature_text",
        "attendance_time_text",
        "notes",
    },
    "education_attendance": {
        "education_session_id",
        "participant_id",
        "attendance_status",
        "signed_at",
        "note",
    },
    "education_participant_identities": {
        "participant_id",
        "education_record_id",
        "identity_type",
        "identity_value_encrypted",
        "identity_hash",
        "identity_masked",
        "identity_last4",
        "legal_basis_note",
        "purpose_note",
        "expires_at",
        "is_active",
    },
    "education_sensitive_access_logs": {
        "participant_id",
        "education_record_id",
        "identity_id",
        "actor_user_id",
        "action",
        "access_scope",
        "masked_value",
        "reason_note",
        "ip_address",
        "user_agent",
    },
    "strategy_plans": {
        "code",
        "title",
        "description",
        "start_year",
        "end_year",
        "status",
        "owner_unit_id",
        "planning_cycle_label",
        "vision_statement",
        "repository_space_id",
    },
    "strategy_goals": {
        "strategy_plan_id",
        "code",
        "title",
        "description",
        "strategic_axis",
        "target_percent",
        "performance_status",
        "responsible_unit_id",
        "status",
        "start_date",
        "end_date",
        "priority_level",
        "repository_space_id",
    },
    "strategy_actions": {
        "strategy_goal_id",
        "code",
        "title",
        "description",
        "responsible_unit_id",
        "responsible_user_id",
        "status",
        "progress_percent",
        "start_date",
        "due_date",
        "completed_date",
        "risk_note",
        "result_note",
        "repository_space_id",
    },
    "strategy_indicators": {
        "strategy_goal_id",
        "strategy_action_id",
        "code",
        "title",
        "description",
        "owner_user_id",
        "unit_of_measure",
        "baseline_value",
        "target_value",
        "current_value",
        "measurement_period",
        "data_source",
        "direction",
        "amber_threshold",
        "green_threshold",
        "status",
    },
    "strategy_indicator_values": {
        "strategy_indicator_id",
        "period_label",
        "value",
        "note",
        "recorded_on",
    },
    "strategy_meetings": {
        "strategy_plan_id",
        "strategy_goal_id",
        "strategy_action_id",
        "title",
        "meeting_date",
        "location",
        "summary",
        "decisions",
        "follow_up_actions",
        "repository_space_id",
    },
    "strategy_risks": {
        "strategy_plan_id",
        "strategy_goal_id",
        "strategy_action_id",
        "title",
        "category",
        "description",
        "owner_user_id",
        "probability_level",
        "impact_level",
        "risk_score",
        "status",
        "mitigation_plan",
        "review_note",
        "due_date",
        "reviewed_on",
    },
    "strategy_decisions": {
        "strategy_meeting_id",
        "strategy_plan_id",
        "strategy_goal_id",
        "strategy_action_id",
        "title",
        "description",
        "owner_user_id",
        "due_date",
        "status",
        "priority_level",
        "completion_note",
        "completed_on",
        "is_active",
        "is_archived",
    },
    "assignment_coverage_logs": {
        "period_id",
        "employee_id",
        "manager_level",
        "event_scope",
        "event_type",
        "severity",
        "reason",
        "run_key",
        "original_evaluator_id",
        "acting_evaluator_id",
        "delegation_id",
        "created_by_user_id",
    },
    "performance_criteria": {
        "name",
        "description",
        "weight",
        "sort_order",
        "is_active",
        "criteria_code",
        "effective_start_date",
        "effective_end_date",
    },
    "organization_unit_versions": {
        "organization_unit_id",
        "unit_code_snapshot",
        "name",
        "unit_type",
        "parent_unit_id_snapshot",
        "parent_name_snapshot",
        "org_path_snapshot",
        "effective_start_date",
        "effective_end_date",
        "change_reason",
        "is_current",
    },
    "employee_org_assignment_history": {
        "employee_id",
        "organization_unit_id",
        "organization_unit_version_id",
        "unit_name_snapshot",
        "parent_unit_name_snapshot",
        "org_path_snapshot",
        "manager_1_user_id",
        "manager_2_user_id",
        "manager_3_user_id",
        "manager_1_name_snapshot",
        "manager_2_name_snapshot",
        "manager_3_name_snapshot",
        "manager_1_sicil_snapshot",
        "manager_2_sicil_snapshot",
        "manager_3_sicil_snapshot",
        "start_date",
        "end_date",
        "assignment_type",
        "reason",
        "is_current",
    },
    "performance_result_snapshots": {
        "period_id",
        "evaluation_id",
        "employee_id",
        "employee_name_snapshot",
        "sicil_no_snapshot",
        "organization_unit_id_snapshot",
        "organization_unit_code_snapshot",
        "birim_snapshot",
        "ust_birim_snapshot",
        "org_path_snapshot",
        "manager_1_user_id_snapshot",
        "manager_1_name_snapshot",
        "manager_1_sicil_snapshot",
        "manager_2_user_id_snapshot",
        "manager_2_name_snapshot",
        "manager_2_sicil_snapshot",
        "manager_3_user_id_snapshot",
        "manager_3_name_snapshot",
        "manager_3_sicil_snapshot",
        "level_1_total_100",
        "level_2_total_100",
        "level_3_total_100",
        "final_total_100",
        "evaluation_status_snapshot",
        "ranking_in_unit",
        "ranking_in_scope",
        "level_1_general_comment",
        "level_2_general_comment",
        "level_3_general_comment",
        "published_at",
        "published_by_user_id",
        "source_type",
        "source_reference",
        "version_no",
        "is_current",
        "payload_json",
    },
    "performance_import_batches": {
        "import_type",
        "period_id",
        "file_name",
        "status",
        "created_by_user_id",
        "completed_at",
        "row_count",
        "success_count",
        "error_count",
        "notes",
    },
    "performance_import_batch_rows": {
        "batch_id",
        "row_no",
        "sicil_no",
        "employee_name_raw",
        "birim_raw",
        "ust_birim_raw",
        "status",
        "error_message",
        "raw_payload_json",
    },
}


REMOVED_MODULE_SCHEMA_PREFIXES: tuple[str, ...] = (
    "education_",
    "strategy_",
    "repository_",
)

REMOVED_MODULE_SCHEMA_KEYS: set[str] = {
    "documents",
    "document_versions",
    "media_albums",
    "media_assets",
    "attachment_links",
    "download_logs",
    "access_policies",
}


def is_removed_scope_table(table_name: str) -> bool:
    """Return True when a schema key belongs to a quarantined live-scope module."""
    return table_name.startswith(REMOVED_MODULE_SCHEMA_PREFIXES) or table_name in REMOVED_MODULE_SCHEMA_KEYS


def get_expected_schema() -> dict[str, set[str]]:
    """Return the active live schema contract used by startup validation.

    A fresh copy is returned so tests or future checks cannot mutate the module-level
    contract by accident.
    """
    return {
        table_name: set(columns)
        for table_name, columns in EXPECTED_SCHEMA.items()
        if not is_removed_scope_table(table_name)
    }


def iter_expected_tables() -> Iterable[str]:
    """Yield active table names for lightweight reporting and gate scripts."""
    return get_expected_schema().keys()
