"""BYS360 canlı omurga ayar katalogları.

Bu katalog yalnızca canlıda kalan çekirdek alanları yönetir:
- Kimlik, kullanıcı, yetki ve ayarlar
- Genel alanlar, bildirim, yardım/destek ve loglar
- Personel yönetimi, izin/devamsızlık/vekâlet
- Performans yönetimi
- İletişim, anket ve geri bildirim
- AI karar destek merkezi

Kapsam dışına alınan geniş modül ailelerine ait ayarlar bu katalogda
bilinçli olarak gösterilmez.
"""
from __future__ import annotations

SYSTEM_SETTING_DEFINITIONS = [
    {
        "setting_key": "general.system_name",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Sistem adı",
        "description": "Başlıklarda ve yönetim ekranlarında görünen sistem adı.",
        "value_type": "string",
        "input_type": "text",
        "default": "BYS360 – Bütünleşik Yönetim Sistemi",
    },
    {
        "setting_key": "general.institution_name",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Kurum adı",
        "description": "Üst bilgi, rapor başlığı ve kurumsal metinlerde kullanılacak kurum adı.",
        "value_type": "string",
        "input_type": "text",
        "default": "Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı",
    },
    {
        "setting_key": "general.default_language",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Varsayılan dil",
        "description": "Yönetim ekranlarında önerilen varsayılan dil kodu.",
        "value_type": "string",
        "input_type": "text",
        "default": "tr",
    },
    {
        "setting_key": "general.date_format",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Tarih biçimi",
        "description": "Arayüz ve rapor çıktılarında kullanılacak tarih gösterimi.",
        "value_type": "string",
        "input_type": "text",
        "default": "dd.MM.yyyy",
    },
    {
        "setting_key": "general.time_format",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Saat biçimi",
        "description": "Saat gösteriminde kullanılacak ortak format.",
        "value_type": "string",
        "input_type": "text",
        "default": "24h",
    },
    {
        "setting_key": "general.maintenance_mode",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Bakım modu",
        "description": "Bakım çalışmalarında yönetim dışındaki erişimi sınırlamak için kullanılır.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "false",
    },
    {
        "setting_key": "general.version_note",
        "group_key": "general",
        "group_label": "Genel Sistem Ayarları",
        "group_description": "Sistemin görünen adı, kurum bilgileri ve ortak kullanım varsayımları.",
        "label": "Sürüm notu",
        "description": "Ayarlar ekranında görünen kısa sürüm notu veya değişiklik özeti.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "Canlı omurga; personel, performans, iletişim, anket, destek ve AI karar destek alanlarıyla sadeleştirildi.",
    },

    {
        "setting_key": "about.hero_title",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Ana başlık",
        "description": "Tanıtım alanında kullanılan büyük başlık.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "Kurumsal Süreçleri Tek Dijital Omurgada Toplayan Bütünleşik Yönetim Sistemi",
    },
    {
        "setting_key": "about.hero_subtitle",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Ana açıklama",
        "description": "Tanıtım alanında başlığın altında görünen açıklama.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "BYS360; kimlik, yetki, personel, performans, izin-vekalet, iletişim, anket, destek, raporlama ve AI karar destek alanlarını aynı kurumsal kullanım dili içinde bir araya getirir.",
    },
    {
        "setting_key": "about.hero_badges",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Ana rozetler",
        "description": "Her satıra bir rozet yazın. Örnek: Canlı omurga, Rol bazlı erişim.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "Canlı omurga\nRol bazlı erişim\nŞeffaf performans akışı\nAI destekli analiz",
    },

    {
        "setting_key": "about.modal_title",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Avatar Hakkında başlığı",
        "description": "Sağ üst avatar menüsünden açılan Hakkında penceresinin başlığı.",
        "value_type": "string",
        "input_type": "text",
        "default": "BYS360 Hakkında",
    },
    {
        "setting_key": "about.modal_badges",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Avatar Hakkında rozetleri",
        "description": "Her satıra bir rozet yazın. Bu rozetler modalın üst kısmında görünür.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "Kurumsal Yayın\nCanlı Ortam",
    },
    {
        "setting_key": "about.modal_description",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Avatar Hakkında açıklaması",
        "description": "Sağ üst avatar menüsünden açılan pencerede görünen canlı omurga açıklaması.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "BYS360; kimlik, yetki, personel, performans, izin-vekalet, iletişim, anket, destek, raporlama ve AI karar destek alanlarını aynı kurumsal kullanım dili içinde bir araya getirir.",
    },
    {
        "setting_key": "about.application_name",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Uygulama adı",
        "description": "Hakkında penceresindeki Uygulama kartında görünen metin.",
        "value_type": "string",
        "input_type": "text",
        "default": "BYS360 – Bütünleşik Yönetim Sistemi",
    },
    {
        "setting_key": "about.developer_name",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Geliştirici adı",
        "description": "Hakkında penceresindeki Geliştirici kartında görünen metin.",
        "value_type": "string",
        "input_type": "text",
        "default": "Personel Gülsen Özden",
    },
    {
        "setting_key": "about.institution_name",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Kurum adı",
        "description": "Hakkında penceresindeki Kurum kartında görünen metin.",
        "value_type": "string",
        "input_type": "text",
        "default": "Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı",
    },
    {
        "setting_key": "about.release_info",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Yayın bilgisi",
        "description": "Hakkında penceresindeki Yayın Bilgisi kartı. Satır satır yazılabilir.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "Sürüm 1.0.0\nYapı 2026.04",
    },
    {
        "setting_key": "about.overview_title",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Genel anlatım başlığı",
        "description": "Modül kartlarından önceki kurumsal anlatım başlığı.",
        "value_type": "string",
        "input_type": "text",
        "default": "Canlı kullanım için sadeleştirilmiş bütünlüklü yapı",
    },
    {
        "setting_key": "about.overview_text",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Genel anlatım metni",
        "description": "Canlı omurgayı anlatan kısa metin.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "BYS360, modülleri ayrı ve kopuk ekranlar olarak değil; birbirini besleyen tek bir yönetim omurgası olarak kurgular. Kullanıcı, yetki, personel, performans, iletişim, anket, destek ve AI karar destek alanları aynı deneyim içinde devam eder.",
    },
    {
        "setting_key": "about.callout_title",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Güven ve görünürlük başlığı",
        "description": "Tanıtım alanındaki kurumsal güven bölümünün başlığı.",
        "value_type": "string",
        "input_type": "text",
        "default": "Kurumsal güven, yetki ve süreç görünürlüğü",
    },
    {
        "setting_key": "about.callout_text",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Güven ve görünürlük metni",
        "description": "Koyu bölümdeki açıklama metni.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "BYS360 yalnızca işlem ekranları sunmaz; aynı zamanda kurumsal kullanım için yetki sınırı, kapsam seçimi, görünürlük ve denetlenebilir süreç yaklaşımını korur.",
    },
    {
        "setting_key": "about.footer_title",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Alt çağrı başlığı",
        "description": "Sayfanın en altındaki çağrı başlığı.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "BYS360, kurum içi süreçleri aynı dilde bir araya getiren yönetim altyapısıdır.",
    },
    {
        "setting_key": "about.footer_text",
        "group_key": "about",
        "group_label": "Hakkında Penceresi",
        "group_description": "Sağ üst avatar menüsündeki Hakkında penceresi ve varsa tanıtım metinleri.",
        "label": "Alt çağrı metni",
        "description": "Sayfanın en altındaki açıklama metni.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "Personel yönetiminden performans akışına, iletişim ve anket yönetiminden AI karar destek alanına kadar canlı yüzeyler; sade, düzenli ve kurumsal bir kullanım deneyimi oluşturacak şekilde tasarlanmıştır.",
    },

    {
        "setting_key": "ui.sidebar_color",
        "group_key": "ui",
        "group_label": "Kurumsal Görünüm Ayarları",
        "group_description": "Renk, filigran, logo ve genel görünüm omurgası.",
        "label": "Sidebar ana renk",
        "description": "Kurumsal sol menüde kullanılacak ana renk kodu.",
        "value_type": "string",
        "input_type": "text",
        "default": "#8B0000",
    },
    {
        "setting_key": "ui.topbar_color",
        "group_key": "ui",
        "group_label": "Kurumsal Görünüm Ayarları",
        "group_description": "Renk, filigran, logo ve genel görünüm omurgası.",
        "label": "Üst bar renk tonu",
        "description": "Üst gezinme alanında referans alınacak vurgu tonu.",
        "value_type": "string",
        "input_type": "text",
        "default": "#8B0000",
    },
    {
        "setting_key": "ui.watermark_asset",
        "group_key": "ui",
        "group_label": "Kurumsal Görünüm Ayarları",
        "group_description": "Renk, filigran, logo ve genel görünüm omurgası.",
        "label": "Filigran görseli",
        "description": "Arka plan filigranında kullanılacak görsel dosya adı.",
        "value_type": "string",
        "input_type": "text",
        "default": "ay_yildiz.png",
    },
    {
        "setting_key": "ui.show_watermark",
        "group_key": "ui",
        "group_label": "Kurumsal Görünüm Ayarları",
        "group_description": "Renk, filigran, logo ve genel görünüm omurgası.",
        "label": "Filigran göster",
        "description": "Kurumsal arka plan filigranının görünür olup olmayacağını belirler.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "ui.logo_size",
        "group_key": "ui",
        "group_label": "Kurumsal Görünüm Ayarları",
        "group_description": "Renk, filigran, logo ve genel görünüm omurgası.",
        "label": "Logo boyutu",
        "description": "Sol menü ve kapak ekranlarında kullanılacak önerilen logo piksel değeri.",
        "value_type": "int",
        "input_type": "number",
        "default": "120",
    },
    {
        "setting_key": "ui.footer_text",
        "group_key": "ui",
        "group_label": "Kurumsal Görünüm Ayarları",
        "group_description": "Renk, filigran, logo ve genel görünüm omurgası.",
        "label": "Alt bant metni",
        "description": "Tüm sayfalarda görünen kurumsal telif metni.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "© 2026 Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı. Her hakkı saklıdır.",
    },

    {
        "setting_key": "security.enable_captcha_after_failed_login",
        "group_key": "security",
        "group_label": "Kullanıcı ve Güvenlik Ayarları",
        "group_description": "Kimlik doğrulama, oturum güvenliği ve dosya koruma eşikleri.",
        "label": "Hatalı girişte CAPTCHA",
        "description": "Eşik aşıldığında güvenlik doğrulamasını otomatik açar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "security.failed_login_threshold",
        "group_key": "security",
        "group_label": "Kullanıcı ve Güvenlik Ayarları",
        "group_description": "Kimlik doğrulama, oturum güvenliği ve dosya koruma eşikleri.",
        "label": "Hatalı giriş eşiği",
        "description": "CAPTCHA devreye girmeden önce izin verilen hatalı giriş sayısı.",
        "value_type": "int",
        "input_type": "number",
        "default": "3",
    },
    {
        "setting_key": "security.require_password_change_first_login",
        "group_key": "security",
        "group_label": "Kullanıcı ve Güvenlik Ayarları",
        "group_description": "Kimlik doğrulama, oturum güvenliği ve dosya koruma eşikleri.",
        "label": "İlk girişte şifre değiştir",
        "description": "Yeni açılan kullanıcı hesaplarında ilk girişte parola yenilemeyi zorunlu tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "security.session_timeout_minutes",
        "group_key": "security",
        "group_label": "Kullanıcı ve Güvenlik Ayarları",
        "group_description": "Kimlik doğrulama, oturum güvenliği ve dosya koruma eşikleri.",
        "label": "Oturum zaman aşımı",
        "description": "Pasif oturumların kaç dakika sonra yenilenmesi gerektiğini belirler.",
        "value_type": "int",
        "input_type": "number",
        "default": "60",
    },

    {
        "setting_key": "personnel.require_registration_number",
        "group_key": "personnel",
        "group_label": "Personel Kayıt Ayarları",
        "group_description": "Personel kartı zorunlulukları ve canlı personel omurgası.",
        "label": "Sicil No zorunlu",
        "description": "Personel kartında TC yerine sicil numarası kullanımını zorunlu tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "personnel.require_title",
        "group_key": "personnel",
        "group_label": "Personel Kayıt Ayarları",
        "group_description": "Personel kartı zorunlulukları ve canlı personel omurgası.",
        "label": "Unvan zorunlu",
        "description": "Personel ekleme/düzenleme ekranında unvan bilgisini zorunlu tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "personnel.require_unit",
        "group_key": "personnel",
        "group_label": "Personel Kayıt Ayarları",
        "group_description": "Personel kartı zorunlulukları ve canlı personel omurgası.",
        "label": "Birim zorunlu",
        "description": "Personel ekleme/düzenleme ekranında birim bilgisini zorunlu tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "personnel.require_parent_unit",
        "group_key": "personnel",
        "group_label": "Personel Kayıt Ayarları",
        "group_description": "Personel kartı zorunlulukları ve canlı personel omurgası.",
        "label": "Üst birim zorunlu",
        "description": "Personel kartında üst birim alanını zorunlu hale getirir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "personnel.require_manager",
        "group_key": "personnel",
        "group_label": "Personel Kayıt Ayarları",
        "group_description": "Personel kartı zorunlulukları ve canlı personel omurgası.",
        "label": "Yönetici alanı zorunlu",
        "description": "Bağlı olduğu yönetici alanının boş bırakılmasını engeller.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "personnel.auto_generate_first_password",
        "group_key": "personnel",
        "group_label": "Personel Kayıt Ayarları",
        "group_description": "Personel kartı zorunlulukları ve canlı personel omurgası.",
        "label": "İlk şifreyi otomatik üret",
        "description": "Yeni kullanıcı oluştururken başlangıç parolasını otomatik üretir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },

    {
        "setting_key": "notifications.use_single_center",
        "group_key": "notifications",
        "group_label": "Bildirim ve E-Posta Ayarları",
        "group_description": "Sistem içi bildirim, e-posta ve merkezi akış davranışları.",
        "label": "Tek bildirim merkezi",
        "description": "Üst bar ve bildirim ekranlarını canlı genel bildirim merkeziyle birlikte çalıştırır.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "notifications.show_unread_counter",
        "group_key": "notifications",
        "group_label": "Bildirim ve E-Posta Ayarları",
        "group_description": "Sistem içi bildirim, e-posta ve merkezi akış davranışları.",
        "label": "Okunmamış sayaç göster",
        "description": "Üst barda okunmamış bildirim sayısını görünür tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "notifications.retention_days",
        "group_key": "notifications",
        "group_label": "Bildirim ve E-Posta Ayarları",
        "group_description": "Sistem içi bildirim, e-posta ve merkezi akış davranışları.",
        "label": "Bildirim saklama süresi",
        "description": "Eski bildirim kayıtlarının kaç gün görünür tutulacağını belirler.",
        "value_type": "int",
        "input_type": "number",
        "default": "180",
    },

    {
        "setting_key": "attachments.upload_root",
        "group_key": "attachments",
        "group_label": "Ek ve Dosya Yükleme Ayarları",
        "group_description": "Destek talebi, mesaj ve anket ekleri için ortak yükleme davranışları.",
        "label": "Yükleme kök klasörü",
        "description": "Canlı modüllerdeki ek dosyalar için kullanılacak yükleme kök yolu.",
        "value_type": "string",
        "input_type": "text",
        "default": "data/uploads",
    },
    {
        "setting_key": "attachments.allowed_extensions",
        "group_key": "attachments",
        "group_label": "Ek ve Dosya Yükleme Ayarları",
        "group_description": "Destek talebi, mesaj ve anket ekleri için ortak yükleme davranışları.",
        "label": "İzin verilen uzantılar",
        "description": "Destek, mesaj ve anket eklerinde kabul edilecek dosya uzantıları.",
        "value_type": "string",
        "input_type": "textarea",
        "default": "pdf,docx,xlsx,png,jpg,jpeg,webp,mp4",
    },
    {
        "setting_key": "attachments.max_upload_mb",
        "group_key": "attachments",
        "group_label": "Ek ve Dosya Yükleme Ayarları",
        "group_description": "Destek talebi, mesaj ve anket ekleri için ortak yükleme davranışları.",
        "label": "Maksimum yükleme boyutu",
        "description": "Tek dosya için önerilen MB sınırı.",
        "value_type": "int",
        "input_type": "number",
        "default": "25",
    },
    {
        "setting_key": "attachments.enable_soft_delete",
        "group_key": "attachments",
        "group_label": "Ek ve Dosya Yükleme Ayarları",
        "group_description": "Destek talebi, mesaj ve anket ekleri için ortak yükleme davranışları.",
        "label": "Silinen eki geri alınabilir tut",
        "description": "Ekleri kalıcı silmeden önce geri alınabilir alanda tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },

    {
        "setting_key": "reporting.default_export_format",
        "group_key": "reporting",
        "group_label": "Raporlama ve Dışa Aktarım Ayarları",
        "group_description": "Performans, personel, anket ve AI özetlerinde kullanılacak ortak varsayımlar.",
        "label": "Varsayılan çıktı formatı",
        "description": "Rapor ekranlarında ilk önerilecek çıktı türü.",
        "value_type": "string",
        "input_type": "text",
        "default": "pdf",
    },
    {
        "setting_key": "reporting.use_logo_in_pdf",
        "group_key": "reporting",
        "group_label": "Raporlama ve Dışa Aktarım Ayarları",
        "group_description": "Performans, personel, anket ve AI özetlerinde kullanılacak ortak varsayımlar.",
        "label": "PDF'de logo kullan",
        "description": "PDF rapor üst bilgisinde kurum logosunun kullanılmasını sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "reporting.mask_personnel_number",
        "group_key": "reporting",
        "group_label": "Raporlama ve Dışa Aktarım Ayarları",
        "group_description": "Performans, personel, anket ve AI özetlerinde kullanılacak ortak varsayımlar.",
        "label": "Sicil numarasını maskele",
        "description": "Dışa aktarımlarda sicil numarasının kısmi maskeli gösterimini açar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "false",
    },

    {
        "setting_key": "logs.retention_days",
        "group_key": "logs",
        "group_label": "Log ve Denetim Ayarları",
        "group_description": "İşlem kaydı, güvenlik denetimi ve saklama süreleri.",
        "label": "Log saklama süresi",
        "description": "İşlem ve hata loglarının kaç gün korunacağını belirler.",
        "value_type": "int",
        "input_type": "number",
        "default": "365",
    },
    {
        "setting_key": "logs.enable_audit_log",
        "group_key": "logs",
        "group_label": "Log ve Denetim Ayarları",
        "group_description": "İşlem kaydı, güvenlik denetimi ve saklama süreleri.",
        "label": "Audit log aktif",
        "description": "Kritik kullanıcı ve yönetim işlemlerinin iz kaydını açık tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "logs.enable_mail_log",
        "group_key": "logs",
        "group_label": "Log ve Denetim Ayarları",
        "group_description": "İşlem kaydı, güvenlik denetimi ve saklama süreleri.",
        "label": "Mail log aktif",
        "description": "Mail gönderim kayıtlarının sistemde tutulmasını sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "technical.healthcheck_enabled",
        "group_key": "technical",
        "group_label": "Teknik Sistem Ayarları",
        "group_description": "Veritabanı, pool ve sistem sağlık kontrollerine ilişkin teknik anahtarlar.",
        "label": "Sağlık kontrolü aktif",
        "description": "Teknik sağlık kontrolü ekranlarının ve servis kontrollerinin referans anahtarını tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "technical.sqlalchemy_pool_pre_ping",
        "group_key": "technical",
        "group_label": "Teknik Sistem Ayarları",
        "group_description": "Veritabanı, pool ve sistem sağlık kontrollerine ilişkin teknik anahtarlar.",
        "label": "SQLAlchemy pre-ping",
        "description": "Bağlantı havuzunda kopuk bağlantıları önceden test etmeyi referans alır.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "setting_key": "technical.sqlalchemy_pool_recycle",
        "group_key": "technical",
        "group_label": "Teknik Sistem Ayarları",
        "group_description": "Veritabanı, pool ve sistem sağlık kontrollerine ilişkin teknik anahtarlar.",
        "label": "SQLAlchemy pool recycle",
        "description": "Havuzdaki bağlantıların yenilenme süresini saniye cinsinden saklar.",
        "value_type": "int",
        "input_type": "number",
        "default": "1800",
    },
]


MODULE_SETTING_DEFINITIONS = [
    {
        "module_key": "identity_access",
        "module_label": "Kimlik, Kullanıcı ve Yetki",
        "module_description": "Kullanıcı, rol, menü görünürlüğü ve erişim davranışları.",
        "setting_key": "use_role_based_visibility",
        "label": "Rol bazlı görünürlük aktif",
        "description": "Menü ve ekran görünürlüğünü rol profilleri üzerinden yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "identity_access",
        "module_label": "Kimlik, Kullanıcı ve Yetki",
        "module_description": "Kullanıcı, rol, menü görünürlüğü ve erişim davranışları.",
        "setting_key": "allow_user_override",
        "label": "Kişi bazlı görünürlük istisnası",
        "description": "Gerektiğinde seçili kullanıcıya özel menü görünürlüğü tanımlanmasını sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "personnel_management",
        "module_label": "Personel Yönetimi",
        "module_description": "Personel kayıtları, organizasyon eşleşmesi ve rapor görünürlüğü.",
        "setting_key": "use_registration_number_identity",
        "label": "Sicil No esas alınsın",
        "description": "Personel eşleşmelerinde TC yerine Sicil No yaklaşımını esas alır.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "personnel_management",
        "module_label": "Personel Yönetimi",
        "module_description": "Personel kayıtları, organizasyon eşleşmesi ve rapor görünürlüğü.",
        "setting_key": "enable_personnel_reports",
        "label": "Personel raporları aktif",
        "description": "Canlı personel raporlama ekranlarını görünür tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },

    {
        "module_key": "performance_core",
        "module_label": "Performans · Değerlendirme Yapısı",
        "module_description": "Değerlendirme terminolojisi, görünürlük ve 3. amir davranışı.",
        "setting_key": "third_manager_mode",
        "label": "3. amir modu",
        "description": "3. amirin kapalı, yorumcu veya puanlayan rolde çalışmasını belirler.",
        "value_type": "choice",
        "input_type": "select",
        "default": "comment_only",
        "choices": [("disabled", "Kapalı"), ("comment_only", "Sadece yorum"), ("scored", "Yorum + puan")],
    },
    {
        "module_key": "performance_core",
        "module_label": "Performans · Değerlendirme Yapısı",
        "module_description": "Değerlendirme terminolojisi, görünürlük ve 3. amir davranışı.",
        "setting_key": "criteria_term",
        "label": "Ekran terminolojisi",
        "description": "Değerlendirme ekranlarında kullanılacak ana terimi belirler.",
        "value_type": "choice",
        "input_type": "select",
        "default": "criteria",
        "choices": [("criteria", "Değerlendirme Kriterleri"), ("behavior", "Davranış Göstergeleri")],
    },
    {
        "module_key": "performance_scoring",
        "module_label": "Performans · Puanlama Kuralları",
        "module_description": "Ağırlıklar, 100’lük dönüşüm ve açıklama zorunlulukları.",
        "setting_key": "default_weight_profile",
        "label": "Varsayılan ağırlık profili",
        "description": "Yeni dönemlerde önerilecek ağırlık dağılımı.",
        "value_type": "choice",
        "input_type": "select",
        "default": "50-50-0",
        "choices": [("50-50-0", "50 / 50 / 0"), ("40-40-20", "40 / 40 / 20"), ("100-0-0", "100 / 0 / 0")],
    },
    {
        "module_key": "performance_scoring",
        "module_label": "Performans · Puanlama Kuralları",
        "module_description": "Ağırlıklar, 100’lük dönüşüm ve açıklama zorunlulukları.",
        "setting_key": "convert_to_hundred_scale",
        "label": "100’lük sisteme çevir",
        "description": "1-5 puanlamanın 100’lük karşılığa otomatik çevrilmesini açar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_scoring",
        "module_label": "Performans · Puanlama Kuralları",
        "module_description": "Ağırlıklar, 100’lük dönüşüm ve açıklama zorunlulukları.",
        "setting_key": "require_comment_for_score_1",
        "label": "1 puanda açıklama zorunlu",
        "description": "1 verilen kriterlerde açıklama alanını zorunlu tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_scoring",
        "module_label": "Performans · Puanlama Kuralları",
        "module_description": "Ağırlıklar, 100’lük dönüşüm ve açıklama zorunlulukları.",
        "setting_key": "require_comment_for_score_5",
        "label": "5 puanda açıklama zorunlu",
        "description": "5 verilen kriterlerde açıklama alanını zorunlu tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_scoring",
        "module_label": "Performans · Puanlama Kuralları",
        "module_description": "Ağırlıklar, 100’lük dönüşüm ve açıklama zorunlulukları.",
        "setting_key": "require_general_comment_below_70",
        "label": "70 altı genel görüş zorunlu",
        "description": "Nihai puan 70’in altında kaldığında genel görüş alanını zorunlu yapar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_scoring",
        "module_label": "Performans · Puanlama Kuralları",
        "module_description": "Ağırlıklar, 100’lük dönüşüm ve açıklama zorunlulukları.",
        "setting_key": "require_general_comment_above_90",
        "label": "90 üstü genel görüş zorunlu",
        "description": "Nihai puan 90’ın üstüne çıktığında detaylı genel görüş ister.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_flow",
        "module_label": "Performans · İş Akışı ve Yayın",
        "module_description": "70 altı süreç, Başkan onayı, yayın kilidi ve statü dili.",
        "setting_key": "low_score_requires_president_approval",
        "label": "70 altı Başkan onayı zorunlu",
        "description": "Nihai puan 70’in altında kaldığında sonucun kesinleşmeden önce Başkan onayına düşmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_flow",
        "module_label": "Performans · İş Akışı ve Yayın",
        "module_description": "70 altı süreç, Başkan onayı, yayın kilidi ve statü dili.",
        "setting_key": "low_score_publish_lock",
        "label": "70 altı yayın kilidi aktif",
        "description": "Başkan onayı ve İK/Admin ön kontrolü tamamlanmadan 70 altı karnenin personele yayınlanmasını engeller.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_flow",
        "module_label": "Performans · İş Akışı ve Yayın",
        "module_description": "70 altı süreç, Başkan onayı, yayın kilidi ve statü dili.",
        "setting_key": "status_language_mode",
        "label": "Statü dili",
        "description": "Kullanıcı ekranlarında teknik kod yerine kurumsal Türkçe statü ifadelerinin kullanılmasını belirler.",
        "value_type": "string",
        "input_type": "select",
        "default": "institutional_tr",
        "choices": [("institutional_tr", "Kurumsal Türkçe"), ("technical", "Teknik kod - sadece bakım")],
    },
    {
        "module_key": "performance_flow",
        "module_label": "Performans · İş Akışı ve Yayın",
        "module_description": "Şeffaf değerlendirme, görünürlük ve yayın zamanlaması.",
        "setting_key": "blind_review_mode",
        "label": "Kör değerlendirme",
        "description": "Canlı kurala göre kapalı tutulmalıdır; sonraki amir önceki kanaati görebilir.",
        "value_type": "choice",
        "input_type": "select",
        "default": "off",
        "choices": [("off", "Kapalı"), ("partial", "Kısmi"), ("on", "Açık")],
    },
    {
        "module_key": "performance_flow",
        "module_label": "Performans · İş Akışı ve Yayın",
        "module_description": "Şeffaf değerlendirme, görünürlük ve yayın zamanlaması.",
        "setting_key": "require_publish_before_scorecard",
        "label": "Karne yayımlanmadan görünmesin",
        "description": "İK/Admin yayını olmadan personelin sonuç ekranını açmasını engeller.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_period",
        "module_label": "Performans · Dönem ve Takvim",
        "module_description": "Dönem türleri, aktif takvim ve kapanış davranışları.",
        "setting_key": "default_period_type",
        "label": "Varsayılan dönem türü",
        "description": "Yeni dönem kartında ilk önerilecek dönem tipini belirler.",
        "value_type": "choice",
        "input_type": "select",
        "default": "yearly",
        "choices": [("monthly", "Aylık"), ("quarterly", "3 Aylık"), ("semiannual", "6 Aylık"), ("yearly", "Yıllık")],
    },
    {
        "module_key": "performance_feedback",
        "module_label": "Performans · Geri Bildirim ve Toplantı",
        "module_description": "Toplantı talebi, bildirim ve randevu çakışma kontrolleri.",
        "setting_key": "allow_feedback_request",
        "label": "Personel toplantı talebi açabilsin",
        "description": "Notu açıklanan personelin geri bildirim toplantısı talebi oluşturmasına izin verir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_feedback",
        "module_label": "Performans · Geri Bildirim ve Toplantı",
        "module_description": "Toplantı talebi, bildirim ve randevu çakışma kontrolleri.",
        "setting_key": "prevent_meeting_conflicts",
        "label": "Çakışan randevuyu engelle",
        "description": "Aynı kullanıcı ve zaman diliminde birden fazla geri bildirim toplantısını engeller.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },

    {
        "module_key": "leave_delegation",
        "module_label": "İzin, Devamsızlık ve Vekâlet",
        "module_description": "İzinli amir, vekâlet ve görev yönlendirme kararları.",
        "setting_key": "delegation_policy_mode",
        "label": "İzin politikası modu",
        "description": "İzinli kullanıcı için muafiyet, kısmi değerlendirme veya bilgi amaçlı kayıt yaklaşımını belirler.",
        "value_type": "choice",
        "input_type": "select",
        "default": "exclude",
        "choices": [("exclude", "Muaf tut"), ("partial", "Kısmi değerlendir"), ("informational", "Bilgi amaçlı kaydet")],
    },
    {
        "module_key": "leave_delegation",
        "module_label": "İzin, Devamsızlık ve Vekâlet",
        "module_description": "İzinli amir, vekâlet ve görev yönlendirme kararları.",
        "setting_key": "use_delegation_for_blocked_managers",
        "label": "İzinli amirde vekâlet kullan",
        "description": "Bloke olan yönetici görevlerinde aktif vekâlet akışını devreye alır.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },

    {
        "module_key": "communication_messaging",
        "module_label": "İletişim ve Mesajlaşma",
        "module_description": "Mesajlar, duyurular, ekler ve bildirim akışı.",
        "setting_key": "messages_enabled",
        "label": "Mesajlar aktif",
        "description": "Canlı mesajlaşma ekranlarını görünür ve kullanılabilir tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "communication_messaging",
        "module_label": "İletişim ve Mesajlaşma",
        "module_description": "Mesajlar, duyurular, ekler ve bildirim akışı.",
        "setting_key": "allow_message_attachments",
        "label": "Mesaj ekleri aktif",
        "description": "Mesaj içinde görsel, video, PDF ve ofis dosyası eklenebilmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "survey_management",
        "module_label": "Anket Yönetimi",
        "module_description": "Anket oluşturma, yanıt toplama ve sonuç görünürlüğü.",
        "setting_key": "surveys_enabled",
        "label": "Anketler aktif",
        "description": "Canlı anket ekranlarını ve atama akışını görünür tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "survey_management",
        "module_label": "Anket Yönetimi",
        "module_description": "Anket oluşturma, yanıt toplama ve sonuç görünürlüğü.",
        "setting_key": "show_results_to_managers",
        "label": "Sonuçları yöneticilere aç",
        "description": "Yetkili yöneticilerin anket sonuçlarını rapor ekranında görmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "feedback_pulse",
        "module_label": "Geri Bildirim ve Nabız",
        "module_description": "Nabız yoklaması, kurumsal geri bildirim ve sonuç izleme.",
        "setting_key": "pulse_enabled",
        "label": "Nabız yoklaması aktif",
        "description": "Kısa periyotlu çalışan nabız girişlerini aktif eder.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "feedback_campaign",
        "module_label": "Geri Bildirim Kampanyaları",
        "module_description": "Kampanya, aksiyon planı ve yönetici takip akışı.",
        "setting_key": "campaigns_enabled",
        "label": "Kampanyalar aktif",
        "description": "Kurumsal geri bildirim kampanyalarının yönetilmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "support_center",
        "module_label": "Yardım ve Destek Merkezi",
        "module_description": "Destek talepleri, yanıtlar, ekler ve memnuniyet akışı.",
        "setting_key": "tickets_enabled",
        "label": "Destek talepleri aktif",
        "description": "Kullanıcıların destek talebi açmasını ve yanıt almasını sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_decision_support",
        "module_label": "AI Karar Destek Merkezi",
        "module_description": "Kontrollü özetleme, önceliklendirme, log ve yönetişim ayarları.",
        "setting_key": "ai_center_enabled",
        "label": "AI karar destek aktif",
        "description": "AI karar destek merkezi ve analiz ekranlarının canlı omurgada görünmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_decision_support",
        "module_label": "AI Karar Destek Merkezi",
        "module_description": "Kontrollü özetleme, önceliklendirme, log ve yönetişim ayarları.",
        "setting_key": "require_redaction",
        "label": "AI veri maskeleme zorunlu",
        "description": "AI işleminden önce hassas alanların maskelenmesini referans ayar olarak tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "reporting_analytics",
        "module_label": "Raporlama ve Analiz",
        "module_description": "Performans, personel, anket ve AI analiz ekranları için ortak davranışlar.",
        "setting_key": "executive_summary_enabled",
        "label": "Yönetici özeti aktif",
        "description": "Raporlama ekranlarında yönetici özet bloklarını görünür tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "mail_automation",
        "module_label": "Mail ve Otomatik Hatırlatma",
        "module_description": "SMTP mantığı, test maili ve hatırlatma aralıkları.",
        "setting_key": "smtp_enabled",
        "label": "SMTP aktif",
        "description": "Sistemden e-posta gönderimini aktif eder.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "false",
    },
    {
        "module_key": "mail_automation",
        "module_label": "Mail ve Otomatik Hatırlatma",
        "module_description": "SMTP mantığı, test maili ve hatırlatma aralıkları.",
        "setting_key": "automation_reminders_enabled",
        "label": "Otomatik hatırlatmalar aktif",
        "description": "Bekleyen değerlendirme ve destek süreçleri için otomatik hatırlatma akışını açar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },

    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "enabled",
        "label": "Asistan aktif",
        "description": "Sağ alt BYS360 Asistan penceresinin yetkili kullanıcılarda görünmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "summary_enabled",
        "label": "Özet kartları aktif",
        "description": "Asistan içinde yalnızca sayı düzeyinde bekleyen iş, bildirim, anket, mesaj ve destek özeti gösterir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "actions_enabled",
        "label": "Güvenli yönlendirme kartları aktif",
        "description": "Asistanın yetki kapsamındaki ekranlara güvenli link kartlarıyla yönlendirmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "topics_enabled",
        "label": "Hızlı başlıklar aktif",
        "description": "Asistan içinde hızlı konu başlıklarının ve önerilen soruların görünmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "safety_note_enabled",
        "label": "Güvenlik bilgi notu aktif",
        "description": "Asistanın idari karar üretmediğini ve hassas içerik göstermediğini belirten notu görünür tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "count_summary_enabled",
        "label": "Sayı düzeyinde özet izni",
        "description": "Asistanın içerik göstermeden yalnızca sayısal özet üretmesine izin verir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "safe_links_enabled",
        "label": "Güvenli iç bağlantılar aktif",
        "description": "Asistan cevaplarında yalnızca BYS360 içindeki güvenli bağlantıların gösterilmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "assistant",
        "module_label": "BYS360 Asistan",
        "module_description": "Kurumsal rehberlik, yetki kontrollü özet kartları ve güvenli yönlendirme davranışları.",
        "setting_key": "visible_roles",
        "label": "Asistanı görecek roller",
        "description": "Virgül veya satırla ayırarak yazın. Örnek: admin,baskan,grup_baskani,koordinator,personel",
        "value_type": "string",
        "input_type": "textarea",
        "default": "admin,baskan,baskan_yardimcisi,grup_baskani,mali_musavir,birim_sorumlusu,koordinator,personel",
    },
]

# >>> BYS360_KUNYE_SETTINGS_DEFINITIONS_START
KUNYE_SYSTEM_SETTING_DEFINITIONS = [{'setting_key': 'kunye.eyebrow', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Üst küçük başlık', 'description': 'Künye sayfasının hero alanındaki küçük başlık.', 'value_type': 'string', 'input_type': 'text', 'default': 'BYS360 Bütünleşik Yönetim Sistemi'}, {'setting_key': 'kunye.page_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Sayfa başlığı', 'description': 'Künye sayfasındaki ana başlık.', 'value_type': 'string', 'input_type': 'text', 'default': 'Sistem Künyesi'}, {'setting_key': 'kunye.subtitle', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Sayfa açıklaması', 'description': 'Hero alanında görünen açıklama metni.', 'value_type': 'string', 'input_type': 'textarea', 'default': 'Bu sayfa, BYS360’ın kurumsal sahiplik bilgisini, proje sorumluluğunu ve sistem/yazılım yönetimi bilgisini sade, izlenebilir ve kurumsal bir çerçevede sunar.'}, {'setting_key': 'kunye.corporate_section_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Kurumsal sahiplik başlığı', 'description': 'İlk kartın başlığı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Kurumsal Sahiplik'}, {'setting_key': 'kunye.institution_authority_label', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Kurum yetkilisi etiketi', 'description': 'İmtiyaz sahibi / kurum yetkilisi alan etiketi.', 'value_type': 'string', 'input_type': 'text', 'default': 'İmtiyaz Sahibi / Kurum Yetkilisi'}, {'setting_key': 'kunye.institution_authority_prefix', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Kurum yetkilisi açıklaması', 'description': 'Başkan adının üstünde görünen kurum adına açıklaması.', 'value_type': 'string', 'input_type': 'textarea', 'default': 'Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı adına'}, {'setting_key': 'kunye.chair_name', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Başkan adı', 'description': 'Kurum yetkilisi olarak görünen başkan adı.', 'value_type': 'string', 'input_type': 'text', 'default': 'İsmail KAŞDEMİR'}, {'setting_key': 'kunye.chair_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Başkan unvanı', 'description': 'Kurum yetkilisi unvanı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Başkan'}, {'setting_key': 'kunye.system_owner_label', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Sistem sahibi etiketi', 'description': 'Sistem sahibi kurum alan etiketi.', 'value_type': 'string', 'input_type': 'text', 'default': 'Sistem Sahibi Kurum'}, {'setting_key': 'kunye.system_owner_value', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Sistem sahibi kurum', 'description': 'Sistemin sahibi kurum bilgisi.', 'value_type': 'string', 'input_type': 'textarea', 'default': 'Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı'}, {'setting_key': 'kunye.corporate_responsibility_label', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Kurumsal sorumluluk etiketi', 'description': 'Kurumsal sorumluluk alan etiketi.', 'value_type': 'string', 'input_type': 'text', 'default': 'Kurumsal Sorumluluk'}, {'setting_key': 'kunye.corporate_responsibility_value', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Kurumsal sorumluluk metni', 'description': 'Kurumsal sorumluluk açıklaması.', 'value_type': 'string', 'input_type': 'textarea', 'default': 'Kurum içi dijital yönetim süreçlerinin kontrollü, güvenli ve izlenebilir yürütülmesi'}, {'setting_key': 'kunye.project_section_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Proje bilgileri başlığı', 'description': 'Proje bilgilerinin yer aldığı kart başlığı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Proje Bilgileri'}, {'setting_key': 'kunye.project_owner_label', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Proje yürütücüsü etiketi', 'description': 'Proje yürütücüsü alan etiketi.', 'value_type': 'string', 'input_type': 'text', 'default': 'Proje Yürütücüsü'}, {'setting_key': 'kunye.project_owner_name', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Proje yürütücüsü adı', 'description': 'Künye sayfasındaki proje yürütücüsü adı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Mustafa BEKTAŞ'}, {'setting_key': 'kunye.project_owner_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Proje yürütücüsü unvanı', 'description': 'Proje yürütücüsünün görünen unvanı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Personel ve İdari İşler Grup Başkanı'}, {'setting_key': 'kunye.developer_label', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Proje geliştiricisi etiketi', 'description': 'Proje geliştiricisi alan etiketi.', 'value_type': 'string', 'input_type': 'text', 'default': 'Proje Geliştiricisi'}, {'setting_key': 'kunye.developer_name', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Proje geliştiricisi adı', 'description': 'Künye sayfasında görünen proje geliştiricisi adı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Personel Gülsen ÖZDEN'}, {'setting_key': 'kunye.software_management_label', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Sistem ve yazılım etiketi', 'description': 'Sistem ve yazılım yönetimi alan etiketi.', 'value_type': 'string', 'input_type': 'text', 'default': 'Sistem ve Yazılım Yönetimi'}, {'setting_key': 'kunye.software_management_value', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Sistem ve yazılım yönetimi', 'description': 'Sistem ve yazılım yönetimi bilgisinde görünen metin.', 'value_type': 'string', 'input_type': 'text', 'default': 'BYS360 Proje Ekibi'}, {'setting_key': 'kunye.security_section_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Güvenlik ilkesi başlığı', 'description': 'Güvenlik ve kullanım kartı başlığı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Güvenlik ve Kullanım İlkesi'}, {'setting_key': 'kunye.security_text', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Güvenlik ve kullanım metni', 'description': 'Künye sayfasında görünen güvenlik ve kullanım ilkesi metni.', 'value_type': 'string', 'input_type': 'textarea', 'default': 'BYS360, kurum içi dijital yönetim süreçlerinin rol bazlı yetkilendirme, kayıt altına alma, denetlenebilirlik ve insan denetimli karar destek ilkeleriyle yürütülmesi amacıyla geliştirilmiştir. Sistem, idari karar yerine geçmez; yetkili kullanıcıların süreçleri daha kontrollü, güvenli ve izlenebilir biçimde yürütmesine destek olur.'}, {'setting_key': 'kunye.copyright_section_title', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Telif başlığı', 'description': 'Telif ve kullanım kartı başlığı.', 'value_type': 'string', 'input_type': 'text', 'default': 'Telif ve Kullanım'}, {'setting_key': 'kunye.copyright_text', 'group_key': 'kunye', 'group_label': 'Sistem Künyesi', 'group_description': 'Sistem Künyesi sayfasında görünen kurumsal sahiplik, proje ve kullanım bilgileri.', 'label': 'Telif ve kullanım metni', 'description': 'Künye sayfasının telif ve kullanım açıklaması.', 'value_type': 'string', 'input_type': 'textarea', 'default': '© 2026 Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı. Her hakkı saklıdır. BYS360 yalnızca kurum içi yetkili kullanım amacıyla geliştirilmiş kurumsal dijital yönetim sistemidir.'}]

_existing_system_setting_keys = {item.get("setting_key") for item in SYSTEM_SETTING_DEFINITIONS}
SYSTEM_SETTING_DEFINITIONS.extend(
    item for item in KUNYE_SYSTEM_SETTING_DEFINITIONS
    if item.get("setting_key") not in _existing_system_setting_keys
)
# <<< BYS360_KUNYE_SETTINGS_DEFINITIONS_END

# BYS360_SETTINGS_MANUAL_V1_CATALOG_BEGIN
try:
    MODULE_SETTING_DEFINITIONS
except NameError:
    MODULE_SETTING_DEFINITIONS = []

_BYS360_MANUAL_MODULE_SETTING_DEFINITIONS = [{'module_key': 'performance_category', 'module_label': 'Performans Kategori ve Grup Görünürlüğü', 'setting_key': 'categories_enabled', 'label': 'Personel kategorileri aktif', 'description': 'Güvenlik, Temizlik, İdari Personel, Teknik Personel gibi performans kategorileri kullanılabilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_category', 'module_label': 'Performans Kategori ve Grup Görünürlüğü', 'setting_key': 'import_category_column_enabled', 'label': 'İçe aktarmada kategori sütunu aktif', 'description': 'Toplu personel aktarımında kategori/personel kategorisi alanları okunur.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_category', 'module_label': 'Performans Kategori ve Grup Görünürlüğü', 'setting_key': 'show_category_average_without_person_detail', 'label': 'Kategori ortalamasında kişi detayı gizle', 'description': 'Personel kendi kategori/grup ortalamasını görebilir; başka personel detayı görmez.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_interim_notes', 'module_label': 'Dönem İçi Notlar', 'setting_key': 'enabled', 'label': 'Dönem içi notlar aktif', 'description': 'Yetkili amirler dönem içinde kayıtlı ara not oluşturabilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_interim_notes', 'module_label': 'Dönem İçi Notlar', 'setting_key': 'show_during_scoring', 'label': 'Puanlamada dönem içi notları göster', 'description': 'Amir puanlama yaparken ilgili personele ait dönem içi notları hatırlatma olarak görebilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_interim_notes', 'module_label': 'Dönem İçi Notlar', 'setting_key': 'allow_scorecard_visibility', 'label': 'Karneye yansıtma ayarı aktif', 'description': 'Dönem içi notların karne görünürlüğü ayrı süreç ayarıyla yönetilebilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_development', 'module_label': 'Gelişim Rehberi', 'setting_key': 'guidance_enabled', 'label': 'Gelişim rehberi aktif', 'description': 'Performans sonucu sonrası gelişim önerisi ve rehber not alanları kullanılabilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_development', 'module_label': 'Gelişim Rehberi', 'setting_key': 'show_on_scorecard', 'label': 'Karne altında gelişim önerisi göster', 'description': 'Yayınlanan karnede yetki ve yayın durumuna göre gelişim önerisi bölümü gösterilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_development', 'module_label': 'Gelişim Rehberi', 'setting_key': 'manager_recommendations_enabled', 'label': 'Yönetici gelişim önerisi yazabilsin', 'description': 'Yetkili amir/yönetici gelişim önerisi oluşturabilir ve sürece bağlayabilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_reminders', 'module_label': 'Hatırlatma ve Aksatan Amirler', 'setting_key': 'overdue_manager_tracking_enabled', 'label': 'Aksatan amir takibi aktif', 'description': 'Süresi geçen değerlendirme görevlerinde amir gecikme takibi yapılır.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_reminders', 'module_label': 'Hatırlatma ve Aksatan Amirler', 'setting_key': 'system_notification_enabled', 'label': 'Sistem içi hatırlatma aktif', 'description': 'Yaklaşan veya geciken değerlendirme işleri için sistem içi bildirim üretilebilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_reminders', 'module_label': 'Hatırlatma ve Aksatan Amirler', 'setting_key': 'mail_log_required', 'label': 'Hatırlatma mail log kaydı zorunlu', 'description': 'E-posta hatırlatma açıksa gönderim sonucu mail log kayıtlarına düşer.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_process', 'module_label': 'Performans Süreç Takibi', 'setting_key': 'tracking_enabled', 'label': 'Süreç takibi aktif', 'description': 'Performans süreçleri yetki kapsamına göre süreç takibi ekranında izlenir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_process', 'module_label': 'Performans Süreç Takibi', 'setting_key': 'reports_enabled', 'label': 'Süreç raporları aktif', 'description': 'Süreç raporları ve risk analizi ekranları yönetici kapsamına göre açılır.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_process', 'module_label': 'Performans Süreç Takibi', 'setting_key': 'personnel_support_publish_preapproval_enabled', 'label': 'Yayın ön onayı aktif', 'description': 'Başkan/üst onayı sonrası yayın öncesinde Personel ve Destek Hizmetleri Grup Başkanı kontrol adımı kullanılabilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_archive', 'module_label': 'Geçmiş Karne Arşivi', 'setting_key': 'enabled', 'label': 'Geçmiş karne arşivi aktif', 'description': 'Eski yıl performans kayıtları yetki kapsamına göre görüntülenebilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_archive', 'module_label': 'Geçmiş Karne Arşivi', 'setting_key': 'excel_import_enabled', 'label': 'Arşiv Excel aktarımı aktif', 'description': 'Geçmiş yıl puanları kontrollü Excel aktarımıyla içeri alınabilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_archive', 'module_label': 'Geçmiş Karne Arşivi', 'setting_key': 'personnel_self_view_enabled', 'label': 'Personel kendi geçmişini görebilsin', 'description': 'Personel yalnızca kendisine ait geçmiş performans kayıtlarını görebilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_archive', 'module_label': 'Geçmiş Karne Arşivi', 'setting_key': 'manager_scope_guard_enabled', 'label': 'Yönetici arşiv kapsam kilidi aktif', 'description': 'Koordinatör ve grup başkanı yalnızca yetkili olduğu kapsamın geçmiş kayıtlarını görebilir.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}, {'module_key': 'performance_visibility', 'module_label': 'Performans Menü ve Görünürlük', 'setting_key': 'new_screen_settings_synced', 'label': 'Yeni ekran ayar senkronu tamamlandı', 'description': 'Yeni canlı performans ekranları Ayarlar, Rol Matrisi ve Modül Ayarları omurgasına bağlanmıştır.', 'value_type': 'bool', 'input_type': 'bool', 'default': 'true'}]
_BYS360_EXISTING_PAIRS = {
    (_item.get("module_key"), _item.get("setting_key"))
    for _item in MODULE_SETTING_DEFINITIONS
    if isinstance(_item, dict)
}

for _item in _BYS360_MANUAL_MODULE_SETTING_DEFINITIONS:
    _pair = (_item.get("module_key"), _item.get("setting_key"))
    if _pair not in _BYS360_EXISTING_PAIRS:
        MODULE_SETTING_DEFINITIONS.append(_item)
        _BYS360_EXISTING_PAIRS.add(_pair)
# BYS360_SETTINGS_MANUAL_V1_CATALOG_END
# BYS360_AY1_AI_PERFORMANCE_SETTINGS_INTEGRATION_V1_BEGIN
# BYS360 Asistanı ve Performans Yönetimi yeni sekme/ekran ayarları Ayarlar modülüne bağlandı.
# Bu blok yalnızca ayar katalogu tanımlarını genişletir; idari karar, puan, yayın veya onay işlemi yapmaz.
_BYS360_AY1_MODULE_SETTING_DEFINITIONS = [
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "enabled",
        "label": "BYS360 Asistanı aktif",
        "description": "BYS360 Asistanı panelinin yetkili kullanıcılarda çalışmasını sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "widget_enabled",
        "label": "Sağ alt asistan butonu aktif",
        "description": "BYS360 Asistan butonunun sayfalarda görünmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "panel_enabled",
        "label": "BYS360 Asistanı sekmesi aktif",
        "description": "Genel menü altındaki BYS360 Asistanı ekranını yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "performance_summary_enabled",
        "label": "Performans özet kartları aktif",
        "description": "Başkan/Üst Onay, yayın kilidi ve bekleyen değerlendirme görevlerinin sayı düzeyinde özetlenmesini sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "kpi_summary_enabled",
        "label": "KPI/Hedef özet kartları aktif",
        "description": "KPI ve hedef yönetimi verilerinin yalnızca yetki kontrollü özet olarak sunulmasını sağlar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "action_queue_enabled",
        "label": "Onaylı aksiyon kuyruğu aktif",
        "description": "Asistan önerilerinin yalnızca takip/onay kuyruğuna alınmasını sağlar; otomatik işlem yapmaz.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "ai_agent",
        "module_label": "BYS360 Asistanı",
        "module_description": "BYS360 Asistanı paneli, özet kartları ve onaylı aksiyon kuyruğu ayarları.",
        "setting_key": "security_note_enabled",
        "label": "Güvenlik bilgi notu aktif",
        "description": "BYS360 Asistanının karar vermediğini, puan/onay/yayın işlemi yapmadığını belirten notu görünür tutar.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "president_approvals_tab_enabled",
        "label": "Başkan Onayları sekmesi aktif",
        "description": "70 altı Başkan/Üst Onay kayıtlarının sekme ve menü görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "personnel_support_publish_approval_tab_enabled",
        "label": "Yayın Ön Onayı sekmesi aktif",
        "description": "Personel ve Destek Hizmetleri Grup Başkanı yayın ön onayı ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "process_tracking_tab_enabled",
        "label": "Süreç Takibi sekmesi aktif",
        "description": "Performans süreç akışı ve izleme ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "process_reports_tab_enabled",
        "label": "Süreç Raporları sekmesi aktif",
        "description": "Performans süreç raporları ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "interim_notes_tab_enabled",
        "label": "Dönem İçi Notlar sekmesi aktif",
        "description": "Dönem içi gözlem, başarı ve gelişim notları ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "development_guidance_tab_enabled",
        "label": "Gelişim Rehberi sekmesi aktif",
        "description": "Gelişim önerisi ve rehberlik ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "reminders_tab_enabled",
        "label": "Hatırlatma ve Aksatan Amirler sekmesi aktif",
        "description": "Bekleyen/geciken amir görevleri ve hatırlatma ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "archive_tab_enabled",
        "label": "Geçmiş Karne Arşivi sekmesi aktif",
        "description": "Geçmiş yıl karne/puan arşivi ekranının görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
    {
        "module_key": "performance_screen_visibility",
        "module_label": "Performans · Sekme ve Ekran Görünürlüğü",
        "module_description": "Performans Yönetimi içinde yeni eklenen sekme ve ekranların ayar/rol matrisiyle yönetilmesi.",
        "setting_key": "kpi_tabs_enabled",
        "label": "KPI/Hedef sekmeleri aktif",
        "description": "KPI paneli, hedef yönetimi, yetkinlik kütüphanesi, öz değerlendirme ve KPI analiz sekmelerinin görünürlüğünü yönetir.",
        "value_type": "bool",
        "input_type": "bool",
        "default": "true",
    },
]

try:
    _existing_ay1_defs = {(item.get("module_key"), item.get("setting_key")) for item in MODULE_SETTING_DEFINITIONS if isinstance(item, dict)}
    for _definition in _BYS360_AY1_MODULE_SETTING_DEFINITIONS:
        _key = (_definition.get("module_key"), _definition.get("setting_key"))
        if _key not in _existing_ay1_defs:
            MODULE_SETTING_DEFINITIONS.append(dict(_definition))
            _existing_ay1_defs.add(_key)
except Exception:
    __import__("logging").getLogger(__name__).exception("BYS360 kalite denetimi: sessiz except/pass yakalandi (app/services/settings/catalog.py)")
# BYS360_AY1_AI_PERFORMANCE_SETTINGS_INTEGRATION_V1_END
