# -*- coding: utf-8 -*-
from __future__ import annotations

import json
from pathlib import Path

import pytest


def test_android_responsive_visual_regression_evidence_suite_p6b_report_ok():
    root = Path(__file__).resolve().parents[2]
    report = root / "reports" / "architecture" / "BYS360_ANDROID_RESPONSIVE_VISUAL_REGRESSION_EVIDENCE_SUITE_GATE_P6B_REPORT.json"
    if not report.exists():
        pytest.skip("P6B report is generated by the repair/quality gate before targeted pytest.")
    data = json.loads(report.read_text(encoding="utf-8"))
    assert data["ok"] is True
    assert data["android_responsive_visual_regression_evidence_suite_gate_ok"] is True
    assert data["p6a_visual_regression_report_ok"] is True
    assert data["p5f_final_evidence_report_ok"] is True
    assert data["visual_regression_evidence_doc_ok"] is True
    assert data["findings_index_ok"] is True
