"""Build menu visibility helpers split from app.services.settings.effective_menu.

Generated by Phase4J V39C2. The facade keeps the public wrapper and alias behavior.
"""

from __future__ import annotations

def build_menu_visibility_map(
    user: Any,
    *,
    logger: Any = None,
    rollback: RollbackHook | None = None,
) -> dict[str, bool]:
    """Kullanıcının canlı menü görünürlük haritasını üretir.

    Öncelik sırası:
    1. Rol varsayılanı
    2. Birim profili
    3. Kullanıcı override kaydı
    4. Çekirdek canlı menü savunması
    """
    # Phase4J V39C2: lazy facade dependency imports avoid circular import during module load
    from app.services.settings.effective_menu import (
        Any,
        PORTAL_MENU_VISIBILITY_POLICY,
        UserMenuPermission,
        _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_KEYS,
        _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_MANAGER_ROLES,
        _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_OBSOLETE_KEYS,
        _active_menu_items,
        _apply_bys360_press_news_admin_only_policy,
        _apply_bys360_settings_live_authority_v1,
        _apply_core_menu_visibility_policy,
        _apply_phase3_2_performance_menu_visibility,
        _apply_phase3_performance_menu_policy,
        _apply_role_gate,
        _apply_role_matrix_closed_guard,
        _bys360_apply_general_category_visibility_fix_v1,
        _bys360_apply_performance_main_switch,
        _bys360_apply_performance_shortcut_gate_v4,
        _bys360_exec_item_matches,
        _bys360_exec_norm,
        _bys360_force_home_menu_visible_v1,
        _bys360_is_exec_summary_menu_key,
        _bys360_perf_rm_v8_apply_aliases,
        _bys360_perf_rm_v8_apply_main_gate,
        _bys360_perf_rm_v8_norm_role,
        _bys360_portal_role_matrix_v2_12_apply,
        _bys360_restore_general_section_v4,
        _load_role_matrix_state,
        _load_unit_profile_state,
        _load_user_override_state,
        _log_warning,
        _phase3_2_normalize_role_name,
        _role_allowed_for_menu,
        _rollback,
        _user_has_any_assigned_survey,
        build_effective_user_menu_context,
        get_role_default_menu_keys,
        is_removed_menu_key,
        normalize_role_name,
    )

    active_menu_items = _active_menu_items()
    visibility = {item["key"]: False for item in active_menu_items if item.get("key")}
    if not user:
        visibility.update({"home": True, "account": True, "logout": True})
        return visibility

    role_name = normalize_role_name(getattr(user, "role", ""))
    effective_context: dict[str, Any] = {}

    try:
        effective_context = build_effective_user_menu_context(user, active_menu_items)
        visibility.update(effective_context.get("effective_rule_map", {}) or {})
    except Exception as exc:  # pragma: no cover - canlı DB/şema fallback alanı
        _rollback(rollback)
        _log_warning(
            logger,
            "Menu visibility settings service fallback calisti | user_id=%s | exc=%s",
            getattr(user, "id", None),
            exc,
        )
        for key in get_role_default_menu_keys(role_name):
            if key and not is_removed_menu_key(key):
                visibility[key] = True

        try:
            rows = UserMenuPermission.query.filter_by(user_id=user.id).all()
        except Exception as load_exc:  # pragma: no cover
            _rollback(rollback)
            _log_warning(
                logger,
                "Kullanıcı menü izinleri okunamadı | user_id=%s | exc=%s",
                getattr(user, "id", None),
                load_exc,
            )
            rows = []
        for row in rows:
            menu_key = getattr(row, "menu_key", "")
            if menu_key and not is_removed_menu_key(menu_key):
                visibility[menu_key] = bool(getattr(row, "is_visible", False))

    source_map = effective_context.get("source_map", {}) if isinstance(effective_context, dict) else {}
    _apply_role_matrix_closed_guard(visibility, role_name, source_map=source_map, rollback=rollback)

    _apply_role_gate(visibility, active_menu_items, role_name)

    if not visibility.get("surveys") and _role_allowed_for_menu(
        {"required_roles": ["admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"]},
        role_name,
    ):
        if _user_has_any_assigned_survey(user, rollback=rollback):
            visibility["surveys"] = True

    source_map = effective_context.get("source_map", {}) if isinstance(effective_context, dict) else {}
    _apply_role_matrix_closed_guard(visibility, role_name, source_map=source_map, rollback=rollback)
    visibility = _apply_core_menu_visibility_policy(visibility, role_name, source_map=source_map)

    visibility = _apply_phase3_performance_menu_policy(visibility, role_name)  # BYS360_PHASE3_VISIBILITY_PERMISSION_MENU_APPLIED
    visibility = _apply_phase3_2_performance_menu_visibility(visibility, role_name)  # BYS360_PHASE3_2_MENU_VISIBILITY_APPLIED

    # BYS360_SETTINGS_LIVE_AUTHORITY_V2_APPLIED
    # Rol matrisi, birim profili ve kişi bazlı ayarlar faz/çekirdek/statik rol
    # politikalarından sonra son karar olarak uygulanır; açılan menü görünür,
    # kapatılan menü yeniden açılmaz.
    visibility = _apply_bys360_settings_live_authority_v1(
        visibility,
        user,
        role_name,
        active_menu_items,
        rollback=rollback,
    )
    visibility = _apply_bys360_press_news_admin_only_policy(visibility, user)  # compatibility guard
    visibility = _bys360_apply_performance_main_switch(visibility, user, role_name, rollback=rollback)
    visibility = _bys360_restore_general_section_v4(visibility, user)
    visibility = _bys360_apply_performance_shortcut_gate_v4(visibility)


    # PHASE3A_EFFECTIVE_MENU_V7_V8_INLINE_BEGIN
    if user:
        role_name = normalize_role_name(getattr(user, "role", ""))
        role_state = _load_role_matrix_state(role_name, rollback=rollback)
        unit_state = _load_unit_profile_state(user, rollback=rollback)
        user_state = _load_user_override_state(user, rollback=rollback)

        for _key in _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_OBSOLETE_KEYS:
            visibility[_key] = False

        manager_norms = {
            _phase3_2_normalize_role_name(_r)
            for _r in _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_MANAGER_ROLES
        }

        for _key in _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_KEYS:
            if _key not in visibility:
                visibility[_key] = False
            if _key in role_state:
                visibility[_key] = bool(role_state[_key])
            elif role_name in manager_norms:
                visibility[_key] = True
            if role_state.get(_key) is not False and _key in unit_state:
                visibility[_key] = bool(unit_state[_key])
            if role_state.get(_key) is not False and _key in user_state:
                visibility[_key] = bool(user_state[_key])
            if role_name in {"personel", "user", "kullanici", "kullan\u0131c\u0131", "standart_personel", "rolsuz", "__none__"} and _key in {"admin_users", "org_units", "hr_management", "hr_reports"}:
                if role_state.get(_key) is not True and user_state.get(_key) is not True:
                    visibility[_key] = False

        visibility["account"] = True
        visibility["logout"] = True

        role_name = _bys360_perf_rm_v8_norm_role(getattr(user, "role", ""))
        try:
            role_state = _load_role_matrix_state(role_name, rollback=rollback)
        except Exception:
            log = __import__("logging").getLogger(__name__)
            log.exception("BYS360 effective menu fallback failed | phase=perf_rm_v8_role_state")
            role_state = {}
        try:
            unit_state = _load_unit_profile_state(user, rollback=rollback)
        except Exception:
            log = __import__("logging").getLogger(__name__)
            log.exception("BYS360 effective menu fallback failed | phase=perf_rm_v8_unit_state")
            unit_state = {}
        try:
            user_state = _load_user_override_state(user, rollback=rollback)
        except Exception:
            log = __import__("logging").getLogger(__name__)
            log.exception("BYS360 effective menu fallback failed | phase=perf_rm_v8_user_state")
            user_state = {}

        visibility = _bys360_perf_rm_v8_apply_aliases(visibility, role_state, unit_state, user_state)
        visibility = _bys360_perf_rm_v8_apply_main_gate(visibility, role_state, unit_state, user_state)
        visibility["account"] = True
        visibility["logout"] = True
    # PHASE3A_EFFECTIVE_MENU_V7_V8_INLINE_END


    # PHASE3A_EFFECTIVE_MENU_V14_GENERAL_HOME_INLINE_BEGIN
    if user:
        try:
            active_menu_items = _active_menu_items()
            active_keys = {
                str((item or {}).get("key") or "").strip()
                for item in active_menu_items or []
                if str((item or {}).get("key") or "").strip()
            }
        except Exception:
            log = __import__("logging").getLogger(__name__)
            log.exception("BYS360 effective menu fallback failed | phase=v14_active_keys")
            active_keys = set(visibility.keys())

        try:
            user_state = _load_user_override_state(user, rollback=rollback)
        except Exception:
            log = __import__("logging").getLogger(__name__)
            log.exception("BYS360 effective menu fallback failed | phase=v14_user_state")
            user_state = {}

        for key, is_visible in (user_state or {}).items():
            key = str(key or "").strip()
            if not key or key not in active_keys or is_removed_menu_key(key):
                continue
            visibility[key] = bool(is_visible)

        performance_children = {
            "scorecards", "performance_dashboard", "performance_criteria", "criteria",
            "performance_periods", "periods", "performance_evaluation_tasks", "assignments",
            "performance_tasks", "performance_task_management", "performance_hierarchy_tree",
            "performance_hierarchy_assignments", "performance_team_compare", "team_analysis",
            "team_performance_comparison_history", "performance_feedback_meetings", "feedback_meetings",
            "performance_publish", "publish", "performance_mail_settings", "performance_mail",
            "performance_process_tracking", "performance_process_reports", "performance_president_approvals",
            "performance_personnel_support_publish_approval", "performance_interim_notes",
            "performance_development_guidance", "performance_meeting_p3_reminders",
            "performance_kpi_dashboard", "performance_kpi_management", "performance_competency_library",
            "performance_self_assessment", "performance_kpi_analysis", "performance_feedback_aftercare",
            "performance_feedback_aftercare_new", "performance_feedback_meeting_guide", "performance_feedback_followup",
            "performance_archive", "performance_reports", "performance_scorecard", "my_performance_comparison",
        }
        if any(bool(visibility.get(key)) for key in performance_children):
            for main_key in ("performance_module", "performance_management", "performans_yonetimi"):
                if main_key in active_keys or main_key in visibility:
                    visibility[main_key] = True

        assistant_children = {"ai_agent_panel", "ai_agent_knowledge", "ai_agent_teaching_center", "assistant_center"}
        if any(bool(visibility.get(key)) for key in assistant_children):
            for main_key in ("assistant_module", "ai_agent_panel"):
                if main_key in active_keys or main_key in visibility:
                    visibility[main_key] = True

        visibility["account"] = True
        visibility["logout"] = True

    visibility = _bys360_apply_general_category_visibility_fix_v1(visibility, user, rollback=rollback)
    visibility = _bys360_force_home_menu_visible_v1(visibility, user)
    # PHASE3A_EFFECTIVE_MENU_V14_GENERAL_HOME_INLINE_END


    # PHASE3A_EFFECTIVE_MENU_PORTAL_EXEC_INLINE_BEGIN
    role = str(getattr(user, "role", "") or "").strip().lower()
    for key, allowed_roles in PORTAL_MENU_VISIBILITY_POLICY.items():
        if role in allowed_roles and not is_removed_menu_key(key):
            visibility.setdefault(key, True)

    visibility = _bys360_portal_role_matrix_v2_12_apply(visibility, user, rollback=rollback)

    try:
        exec_role = _bys360_exec_norm(getattr(user, "role", ""))
        is_admin = exec_role in globals().get("_BYS360_EXEC_ADMIN_ONLY_ROLES", set())
        try:
            active_items = _active_menu_items()
        except Exception:
            log = __import__("logging").getLogger(__name__)
            log.exception("BYS360 effective menu fallback failed | phase=exec_active_items")
            active_items = []

        exec_keys = set(globals().get("_BYS360_EXEC_KNOWN_KEYS", set()))
        for item in active_items or []:
            if isinstance(item, dict) and _bys360_exec_item_matches(item):
                k = str(item.get("key") or "").strip()
                if k:
                    exec_keys.add(k)

        for k in list(visibility.keys()):
            if _bys360_is_exec_summary_menu_key(k):
                exec_keys.add(k)

        for k in exec_keys:
            if k in visibility:
                visibility[k] = bool(is_admin)

        if "executive_summary" in visibility:
            visibility["executive_summary"] = bool(is_admin)
    except Exception:
        log = __import__("logging").getLogger(__name__)
        log.exception("BYS360 effective menu fallback failed | phase=exec_admin_only")
    # PHASE3A_EFFECTIVE_MENU_PORTAL_EXEC_INLINE_END

    return visibility

__all__ = [
    "build_menu_visibility_map",
]
