"""BYS360 menu constants split from app.services.settings.effective_menu.

Generated by Phase4J V36C SAFE. Kept API-compatible through facade imports.
"""

from __future__ import annotations

_BYS360_MANUAL_ROLE_MENU_ADDITIONS = {'admin': ['performance_archive', 'performance_process_tracking', 'performance_process_reports', 'performance_personnel_support_publish_approval'], 'baskan': ['performance_archive', 'performance_process_tracking', 'performance_process_reports'], 'baskan_yardimcisi': ['performance_archive', 'performance_process_tracking', 'performance_process_reports'], 'grup_baskani': ['performance_archive', 'performance_process_tracking', 'performance_process_reports', 'performance_personnel_support_publish_approval'], 'mali_musavir': ['performance_archive', 'performance_process_tracking', 'performance_process_reports'], 'koordinator': ['performance_archive', 'performance_process_tracking', 'performance_process_reports'], 'birim_sorumlusu': ['performance_archive', 'performance_process_tracking', 'performance_process_reports'], 'personel': ['performance_archive']}

_BYS360_MANUAL_POLICY = {}

_BYS360_REMINDERS_MENU_KEY = 'performance_meeting_p3_reminders'

_BYS360_REMINDERS_ALLOWED_ROLES = set(['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'])

_BYS360_PROCESS_MENU_KEYS = ['performance_process_tracking', 'performance_process_reports']

_BYS360_PROCESS_MENU_ROLES = set(['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'])

_BYS360_PERFORMANCE_ROLE_MATRIX_NEW_TAB_POLICY = {'performance_process_tracking': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'], 'performance_process_reports': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'], 'performance_interim_notes': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'], 'performance_development_guidance': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'], 'performance_meeting_p3_reminders': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'], 'performance_archive': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'], 'performance_personnel_support_publish_approval': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'grup_baskani'], 'performance_president_approvals': ['admin', 'super_admin', 'system_admin', 'sistem_yoneticisi', 'baskan']}

_BYS360_ROLE_MATRIX_V12_AUTHORITY_KEYS = {
    "support_index", "support_new", "support_my_tickets", "support_assigned", "support_all",
    "assistant_center", "assistant_quick_help", "assistant_my_summary", "assistant_support_routing",
    "assistant_performance_guidance", "assistant_president_approval_guidance", "assistant_publish_preapproval_guidance",
    "assistant_interim_notes_guidance", "assistant_development_guidance", "assistant_archive_guidance",
    "assistant_process_alerts", "assistant_my_reminders", "assistant_scheduled_tasks", "assistant_report_generate",
    "assistant_report_share", "assistant_ai_summary", "assistant_logs", "assistant_settings",
    "performance_process_tracking", "performance_process_reports", "performance_personnel_support_publish_approval",
    "performance_president_approvals", "performance_archive", "performance_interim_notes", "performance_development_guidance",
    "performance_meeting_p3_reminders",
}

_BYS360_ROLE_MATRIX_V12_POLICY = {
    "support_index": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},
    "support_new": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},
    "support_my_tickets": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},
    "support_assigned": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "support_all": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_process_tracking": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_process_reports": {"admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_personnel_support_publish_approval": {"admin", "grup_baskani"},
}

_BYS360_AG5E_AI_TEACHING_MENU_KEY = "ai_teaching_center"

_BYS360_AG5E_AI_TEACHING_ROLES = {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "baskan", "başkan", "ust_yonetim", "ai_yoneticisi"}

_BYS360_PERSONEL_ALLOWED_POLICY = {
    "hr_leave_tracking": {
        "admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator",
        "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı",
        "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir",
        "koordinator", "koordinatör", "birim_sorumlusu",
    },
}

_BYS360_PERSONEL_DISALLOWED_POLICY_KEYS = {
    "hr_management",
    "hr_reports",
    "hr_personnel_operations",
    "hr_career_planning",
    "hr_reward_discipline",
}

_BYS360_PERSONEL_ROLE_MATRIX_CURRENT_ALLOWED_KEYS = {"admin_users", "org_units", "hr_leave_tracking"}

_BYS360_PERSONEL_ROLE_MATRIX_CURRENT_MANAGER_ROLES = {
    "admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator",
    "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı",
    "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir",
    "koordinator", "koordinatör", "birim_sorumlusu",
}

_BYS360_ALL_MENU_ROLE_MATRIX_AUTHORITY_KEYS = {'home', 'dashboard', 'notifications', 'announcements', 'account', 'settings', 'db_check', 'logout', 'support_index', 'support_new', 'support_my_tickets', 'support_assigned', 'support_all', 'support_help_admin', 'admin_users', 'org_units', 'hr_leave_tracking', 'performance_scorecard', 'my_performance_comparison', 'performance_reports', 'performance_tasks', 'performance_criteria', 'performance_periods', 'performance_evaluation_tasks', 'performance_task_management', 'performance_hierarchy_tree', 'performance_hierarchy_assignments', 'performance_team_compare', 'team_performance_comparison_history', 'performance_feedback_meetings', 'performance_publish', 'performance_president_approvals', 'performance_personnel_support_publish_approval', 'performance_process_tracking', 'performance_process_reports', 'performance_interim_notes', 'performance_development_guidance', 'performance_meeting_p3_reminders', 'performance_archive', 'performance_history_import', 'performance_mail_settings', 'performance_kpi_dashboard', 'performance_kpi_management', 'performance_competency_library', 'performance_self_assessment', 'performance_kpi_analysis', 'messages', 'surveys', 'survey_manage', 'survey_results', 'feedback_dashboard', 'feedback_pulse', 'feedback_campaigns', 'feedback_results', 'feedback_actions', 'feedback_manager', 'feedback_admin', 'ai_center', 'ai_agent_panel', 'ai_teaching_center', 'assistant_center', 'assistant_quick_help', 'assistant_my_summary', 'assistant_support_routing', 'assistant_performance_guidance', 'assistant_president_approval_guidance', 'assistant_publish_preapproval_guidance', 'assistant_interim_notes_guidance', 'assistant_development_guidance', 'assistant_archive_guidance', 'assistant_process_alerts', 'assistant_my_reminders', 'assistant_scheduled_tasks', 'assistant_report_generate', 'assistant_report_share', 'assistant_ai_summary', 'assistant_logs', 'assistant_settings'}

_BYS360_ALL_MENU_ROLE_MATRIX_POLICY = {
    'performance_scorecard': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'my_performance_comparison': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_reports': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_tasks': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_criteria': {'admin', 'baskan', 'baskan_yardimcisi'},
    'performance_periods': {'admin', 'baskan', 'baskan_yardimcisi'},
    'performance_evaluation_tasks': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_task_management': {'admin'},
    'performance_hierarchy_tree': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_hierarchy_assignments': {'admin'},
    'performance_team_compare': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'team_performance_comparison_history': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_feedback_meetings': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_publish': {'admin', 'baskan'},
    'performance_president_approvals': {'admin', 'baskan'},
    'performance_personnel_support_publish_approval': {'admin', 'grup_baskani', 'personel_ve_destek_hizmetleri_grup_baskani', 'personel_destek_hizmetleri_grup_baskani', 'personel_ve_idari_isler_grup_baskani', 'personel_idari_isler_grup_baskani'},
    'performance_process_tracking': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_process_reports': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_interim_notes': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_development_guidance': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_meeting_p3_reminders': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_archive': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_history_import': {'admin'},
    'performance_mail_settings': {'admin'},
    'performance_kpi_dashboard': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_kpi_management': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator'},
    'performance_competency_library': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_self_assessment': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_kpi_analysis': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator'},
    'support_index': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'support_new': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'support_my_tickets': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'support_assigned': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'support_all': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'ai_agent_panel': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'ai_teaching_center': {'admin', 'baskan'},
    'assistant_center': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_quick_help': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_my_summary': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_support_routing': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_performance_guidance': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assistant_president_approval_guidance': {'admin', 'baskan'},
    'assistant_publish_preapproval_guidance': {'admin', 'grup_baskani', 'personel_ve_destek_hizmetleri_grup_baskani', 'personel_destek_hizmetleri_grup_baskani', 'personel_ve_idari_isler_grup_baskani', 'personel_idari_isler_grup_baskani'},
    'assistant_interim_notes_guidance': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assistant_development_guidance': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assistant_archive_guidance': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_process_alerts': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_my_reminders': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'assistant_scheduled_tasks': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assistant_report_generate': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assistant_report_share': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assistant_ai_summary': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator'},
    'assistant_logs': {'admin', 'baskan'},
    'assistant_settings': {'admin'},
    'admin_users': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'org_units': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'hr_leave_tracking': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
}

_BYS360_ASSISTANT_TAB_AUTHORITY_KEYS = {'assistant_module', 'ai_agent_panel', 'ai_agent_knowledge', 'ai_agent_teaching_center', 'ai_teaching_center', 'assistant_center', 'assistant_quick_help', 'assistant_my_summary', 'assistant_support_routing', 'assistant_performance_guidance', 'assistant_president_approval_guidance', 'assistant_publish_preapproval_guidance', 'assistant_interim_notes_guidance', 'assistant_development_guidance', 'assistant_archive_guidance', 'assistant_process_alerts', 'assistant_my_reminders', 'assistant_scheduled_tasks', 'assistant_report_generate', 'assistant_report_share', 'assistant_ai_summary', 'assistant_logs', 'assistant_settings'}

_BYS360_ASSISTANT_TAB_POLICY = {
    'assistant_module': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'ai_agent_panel': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'ai_agent_knowledge': {'admin', 'baskan'},
    'ai_agent_teaching_center': {'admin', 'baskan'},
    'ai_teaching_center': {'admin', 'baskan'},
}

_BYS360_PERFORMANCE_MAIN_KEYS = {'performance_module', 'performance_management', 'performans_yonetimi'}

_BYS360_PERFORMANCE_CHILD_KEYS = {'performance_tasks', 'performance_scorecard', 'scorecards', 'my_performance_comparison', 'performance_dashboard', 'performance_reports', 'performance_criteria', 'criteria', 'performance_periods', 'periods', 'performance_evaluation_tasks', 'assignments', 'performance_task_management', 'performance_hierarchy_tree', 'performance_hierarchy_assignments', 'performance_team_compare', 'team_analysis', 'team_performance_comparison_history', 'performance_feedback_meetings', 'feedback_meetings', 'performance_publish', 'publish', 'performance_mail_settings', 'performance_mail', 'performance_process_tracking', 'performance_process_reports', 'performance_president_approvals', 'performance_personnel_support_publish_approval', 'performance_archive', 'performance_interim_notes', 'performance_development_guidance', 'performance_meeting_p3_reminders', 'performance_kpi_dashboard', 'performance_kpi_management', 'performance_competency_library', 'performance_self_assessment', 'performance_kpi_analysis'}

_BYS360_PERFORMANCE_ALL_KEYS = set(_BYS360_PERFORMANCE_MAIN_KEYS) | set(_BYS360_PERFORMANCE_CHILD_KEYS)

_BYS360_PERFORMANCE_MAIN_SWITCH_POLICY = {
    'performance_module': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_management': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performans_yonetimi': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_tasks': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_scorecard': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'scorecards': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'my_performance_comparison': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_dashboard': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_reports': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_criteria': {'admin', 'baskan', 'baskan_yardimcisi'},
    'criteria': {'admin', 'baskan', 'baskan_yardimcisi'},
    'performance_periods': {'admin', 'baskan', 'baskan_yardimcisi'},
    'periods': {'admin', 'baskan', 'baskan_yardimcisi'},
    'performance_evaluation_tasks': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'assignments': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_task_management': {'admin'},
    'performance_hierarchy_tree': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_hierarchy_assignments': {'admin'},
    'performance_team_compare': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'team_analysis': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'team_performance_comparison_history': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_feedback_meetings': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'feedback_meetings': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_publish': {'admin', 'baskan'},
    'publish': {'admin', 'baskan'},
    'performance_process_tracking': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_process_reports': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_president_approvals': {'admin', 'baskan'},
    'performance_personnel_support_publish_approval': {'admin', 'grup_baskani'},
    'performance_archive': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_interim_notes': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_development_guidance': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_meeting_p3_reminders': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_kpi_dashboard': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_kpi_management': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator'},
    'performance_competency_library': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu'},
    'performance_self_assessment': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator', 'birim_sorumlusu', 'personel'},
    'performance_kpi_analysis': {'admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir', 'koordinator'},
    'performance_mail_settings': {'admin'},
    'performance_mail': {'admin'},
}

_BYS360_GENERAL_CORE_KEYS_V4 = {'general_section', 'home', 'dashboard', 'notifications', 'support_index', 'support_new', 'support_my_tickets'}

_BYS360_PERFORMANCE_MAIN_KEYS_V4 = {'performance_module', 'performance_management', 'performans_yonetimi'}

_BYS360_PERFORMANCE_GENERAL_SHORTCUT_KEYS_V4 = {'performance_tasks', 'performance_scorecard', 'performance_archive', 'my_performance_comparison', 'performance_reports'}

_BYS360_PERFORMANCE_CHILD_KEYS_V4 = {'performance_tasks', 'performance_scorecard', 'scorecards', 'my_performance_comparison', 'performance_dashboard', 'performance_reports', 'performance_criteria', 'criteria', 'performance_periods', 'periods', 'performance_evaluation_tasks', 'assignments', 'performance_task_management', 'performance_hierarchy_tree', 'performance_hierarchy_assignments', 'performance_team_compare', 'team_analysis', 'team_performance_comparison_history', 'performance_feedback_meetings', 'feedback_meetings', 'performance_publish', 'publish', 'performance_mail_settings', 'performance_mail', 'performance_process_tracking', 'performance_process_reports', 'performance_president_approvals', 'performance_personnel_support_publish_approval', 'performance_archive', 'performance_interim_notes', 'performance_development_guidance', 'performance_meeting_p3_reminders', 'performance_kpi_dashboard', 'performance_kpi_management', 'performance_competency_library', 'performance_self_assessment', 'performance_kpi_analysis', 'performance_feedback_aftercare', 'performance_feedback_aftercare_new', 'performance_feedback_meeting_guide', 'performance_feedback_followup'}

_BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_KEYS = {"admin_users", "org_units", "hr_management", "hr_leave_tracking", "hr_reports"}

_BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_MANAGER_ROLES = {
    "admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator",
    "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı",
    "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir",
    "koordinator", "koordinatör", "birim_sorumlusu",
}

_BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_OBSOLETE_KEYS = {
    "hr_personnel_operations", "hr_career_planning", "hr_reward_discipline",
    "personnel_dashboard", "personnel_create", "personnel_edit", "organization_unit_versions", "hierarchy",
    "leave", "attendance", "delegation", "personnel_reports",
    "personnel_requests", "personnel_validity", "personnel_assets", "personnel_checklists",
    "personnel_reminders", "personnel_lifecycle", "personnel_handover", "personnel_approvals",
    "personnel_request_analytics", "personnel_request_tasks",
}

_BYS360_PERF_RM_V8_MAIN_KEYS = {"performance_module", "performance_management", "performans_yonetimi"}

_BYS360_PERF_RM_V8_ALIAS_GROUPS = {
    "performance_tasks": ["performance_tasks"],
    "performance_scorecard": ["performance_scorecard", "scorecards"],
    "my_performance_comparison": ["my_performance_comparison"],
    "performance_reports": ["performance_reports"],
    "performance_archive": ["performance_archive"],
    "performance_dashboard": ["performance_dashboard"],
    "performance_criteria": ["performance_criteria", "criteria"],
    "performance_periods": ["performance_periods", "periods"],
    "performance_evaluation_tasks": ["performance_evaluation_tasks", "assignments"],
    "performance_task_management": ["performance_task_management"],
    "performance_hierarchy_tree": ["performance_hierarchy_tree"],
    "performance_hierarchy_assignments": ["performance_hierarchy_assignments"],
    "performance_team_compare": ["performance_team_compare", "team_analysis"],
    "team_performance_comparison_history": ["team_performance_comparison_history"],
    "performance_feedback_meetings": ["performance_feedback_meetings", "feedback_meetings"],
    "performance_publish": ["performance_publish", "publish"],
    "performance_mail_settings": ["performance_mail_settings", "performance_mail"],
    "performance_process_tracking": ["performance_process_tracking"],
    "performance_process_reports": ["performance_process_reports"],
    "performance_president_approvals": ["performance_president_approvals"],
    "performance_personnel_support_publish_approval": ["performance_personnel_support_publish_approval"],
    "performance_interim_notes": ["performance_interim_notes"],
    "performance_development_guidance": ["performance_development_guidance"],
    "performance_meeting_p3_reminders": ["performance_meeting_p3_reminders"],
    "performance_feedback_aftercare": ["performance_feedback_aftercare"],
    "performance_feedback_aftercare_new": ["performance_feedback_aftercare_new"],
    "performance_feedback_meeting_guide": ["performance_feedback_meeting_guide"],
    "performance_feedback_followup": ["performance_feedback_followup"],
    "performance_kpi_dashboard": ["performance_kpi_dashboard"],
    "performance_kpi_management": ["performance_kpi_management"],
    "performance_competency_library": ["performance_competency_library"],
    "performance_self_assessment": ["performance_self_assessment"],
    "performance_kpi_analysis": ["performance_kpi_analysis"],
    "performance_history_import": ["performance_history_import"],
}

_BYS360_PERF_RM_V8_CHILD_KEYS = {key for values in _BYS360_PERF_RM_V8_ALIAS_GROUPS.values() for key in values}

_BYS360_PERF_RM_V8_CANONICAL_CHILD_KEYS = set(_BYS360_PERF_RM_V8_ALIAS_GROUPS.keys())

_BYS360_PERF_RM_V8_ALL_KEYS = set(_BYS360_PERF_RM_V8_MAIN_KEYS) | set(_BYS360_PERF_RM_V8_CHILD_KEYS)

_BYS360_PERF_RM_V8_MANAGER_ROLES = {
    "admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator",
    "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı",
    "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir",
    "koordinator", "koordinatör", "birim_sorumlusu",
}

_BYS360_PERF_RM_V8_ALL_AUTH_ROLES = set(_BYS360_PERF_RM_V8_MANAGER_ROLES) | {"personel", "user", "standart_personel"}

_BYS360_PERF_RM_V8_ROLE_POLICY = {
    "performance_module": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "performance_management": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "performans_yonetimi": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "performance_tasks": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_scorecard": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "scorecards": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "my_performance_comparison": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "performance_archive": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "performance_self_assessment": _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    "performance_reports": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_dashboard": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_criteria": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "criteria": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "performance_periods": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "periods": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "performance_evaluation_tasks": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "assignments": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_task_management": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator"},
    "performance_hierarchy_tree": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_hierarchy_assignments": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator"},
    "performance_team_compare": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "team_analysis": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "team_performance_comparison_history": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_feedback_meetings": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "feedback_meetings": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_publish": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president"},
    "publish": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president"},
    "performance_mail_settings": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator"},
    "performance_mail": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator"},
    "performance_process_tracking": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_process_reports": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_president_approvals": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president"},
    "performance_personnel_support_publish_approval": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "grup_baskani", "grup_başkanı", "personel_ve_destek_hizmetleri_grup_baskani", "personel_destek_hizmetleri_grup_baskani", "personel_ve_idari_isler_grup_baskani", "personel_idari_isler_grup_baskani"},
    "performance_interim_notes": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_development_guidance": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_meeting_p3_reminders": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_feedback_aftercare": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_feedback_aftercare_new": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_feedback_meeting_guide": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_feedback_followup": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_kpi_dashboard": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_kpi_management": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
    "performance_competency_library": _BYS360_PERF_RM_V8_MANAGER_ROLES,
    "performance_kpi_analysis": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
    "performance_history_import": {"admin", "super_admin", "system_admin", "sistem_yoneticisi", "administrator"},
}

_BYS360_GENERAL_CATEGORY_SECTION_KEYS_V1 = {"general_section", "genel", "general"}

_BYS360_GENERAL_CATEGORY_CHILD_KEYS_V1 = {
    "home",
    "dashboard",
    "notifications",
    "support_index",
    "support_new",
    "support_my_tickets",
    "support_assigned",
    "support_all",
    "support_help_admin",
}

_BYS360_EXEC_ADMIN_ONLY_ROLES = {'admin', 'administrator', 'sistem_yoneticisi', 'super_admin', 'system_admin'}

_BYS360_EXEC_KNOWN_KEYS = {'daily_weather_mail', 'executive_summary_tasks', 'executive_summary_automatic_emails', 'executive_summary_auto_emails', 'executive_summary_logs', 'executive_summary_mail_logs', 'executive_summary_panel', 'executive_summary_test_send', 'executive_daily_weather_mail', 'executive_summary_scheduled_jobs', 'executive_summary_test', 'executive_summary', 'executive_summary_admin_panel', 'executive_summary_dashboard'}

_BYS360_EXEC_URL_MARKERS = ('/dashboard/yonetici-ozeti', '/executive-summary', '/yonetici-ozeti')

_BYS360_PERIOD_CENTER_MENU_KEY_V221 = "performance_period_management_center"

_BYS360_PERIOD_CENTER_DEFAULT_ROLES_V221 = {
    "admin", "administrator", "super_admin", "system_admin", "sistem_yoneticisi",
    "baskan", "president", "baskan_yardimcisi", "grup_baskani", "mali_musavir",
}

_BYS360_V223_PERIOD_CENTER_KEY_ROLES = {'performance_period_management_center': ['admin', 'baskan', 'baskan_yardimcisi', 'grup_baskani', 'mali_musavir'], 'performance_evaluation_live_tracking': ['admin', 'baskan', 'baskan_yardimcisi', 'birim_sorumlusu', 'grup_baskani', 'koordinator', 'mali_musavir'], 'performance_evaluator_reminder_center': ['admin', 'baskan', 'baskan_yardimcisi', 'birim_sorumlusu', 'grup_baskani', 'koordinator', 'mali_musavir']}

__all__ = [
    "_BYS360_AG5E_AI_TEACHING_MENU_KEY",
    "_BYS360_AG5E_AI_TEACHING_ROLES",
    "_BYS360_ALL_MENU_ROLE_MATRIX_AUTHORITY_KEYS",
    "_BYS360_ALL_MENU_ROLE_MATRIX_POLICY",
    "_BYS360_ASSISTANT_TAB_AUTHORITY_KEYS",
    "_BYS360_ASSISTANT_TAB_POLICY",
    "_BYS360_EXEC_ADMIN_ONLY_ROLES",
    "_BYS360_EXEC_KNOWN_KEYS",
    "_BYS360_EXEC_URL_MARKERS",
    "_BYS360_GENERAL_CATEGORY_CHILD_KEYS_V1",
    "_BYS360_GENERAL_CATEGORY_SECTION_KEYS_V1",
    "_BYS360_GENERAL_CORE_KEYS_V4",
    "_BYS360_MANUAL_POLICY",
    "_BYS360_MANUAL_ROLE_MENU_ADDITIONS",
    "_BYS360_PERFORMANCE_ALL_KEYS",
    "_BYS360_PERFORMANCE_CHILD_KEYS",
    "_BYS360_PERFORMANCE_CHILD_KEYS_V4",
    "_BYS360_PERFORMANCE_GENERAL_SHORTCUT_KEYS_V4",
    "_BYS360_PERFORMANCE_MAIN_KEYS",
    "_BYS360_PERFORMANCE_MAIN_KEYS_V4",
    "_BYS360_PERFORMANCE_MAIN_SWITCH_POLICY",
    "_BYS360_PERFORMANCE_ROLE_MATRIX_NEW_TAB_POLICY",
    "_BYS360_PERF_RM_V8_ALIAS_GROUPS",
    "_BYS360_PERF_RM_V8_ALL_AUTH_ROLES",
    "_BYS360_PERF_RM_V8_ALL_KEYS",
    "_BYS360_PERF_RM_V8_CANONICAL_CHILD_KEYS",
    "_BYS360_PERF_RM_V8_CHILD_KEYS",
    "_BYS360_PERF_RM_V8_MAIN_KEYS",
    "_BYS360_PERF_RM_V8_MANAGER_ROLES",
    "_BYS360_PERF_RM_V8_ROLE_POLICY",
    "_BYS360_PERIOD_CENTER_DEFAULT_ROLES_V221",
    "_BYS360_PERIOD_CENTER_MENU_KEY_V221",
    "_BYS360_PERSONEL_ALLOWED_POLICY",
    "_BYS360_PERSONEL_DISALLOWED_POLICY_KEYS",
    "_BYS360_PERSONEL_ROLE_MATRIX_CURRENT_ALLOWED_KEYS",
    "_BYS360_PERSONEL_ROLE_MATRIX_CURRENT_MANAGER_ROLES",
    "_BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_KEYS",
    "_BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_MANAGER_ROLES",
    "_BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_OBSOLETE_KEYS",
    "_BYS360_PROCESS_MENU_KEYS",
    "_BYS360_PROCESS_MENU_ROLES",
    "_BYS360_REMINDERS_ALLOWED_ROLES",
    "_BYS360_REMINDERS_MENU_KEY",
    "_BYS360_ROLE_MATRIX_V12_AUTHORITY_KEYS",
    "_BYS360_ROLE_MATRIX_V12_POLICY",
    "_BYS360_V223_PERIOD_CENTER_KEY_ROLES",
]
