"""BYS360 effective menu helpers split from app.services.settings.effective_menu.

Generated by Phase4J V34C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

import contextlib
from collections.abc import Callable
from typing import Any

from app.config import is_removed_menu_key
from app.models import RoleMenuDefault, UserMenuPermission

RollbackHook = Callable[[], None]

_BYS360_PERFORMANCE_MAIN_KEYS = {'performance_module', 'performance_management', 'performans_yonetimi'}

_BYS360_PERFORMANCE_CHILD_KEYS = {'performance_tasks', 'performance_scorecard', 'scorecards', 'my_performance_comparison', 'performance_dashboard', 'performance_reports', 'performance_criteria', 'criteria', 'performance_periods', 'periods', 'performance_evaluation_tasks', 'assignments', 'performance_task_management', 'performance_hierarchy_tree', 'performance_hierarchy_assignments', 'performance_team_compare', 'team_analysis', 'team_performance_comparison_history', 'performance_feedback_meetings', 'feedback_meetings', 'performance_publish', 'publish', 'performance_mail_settings', 'performance_mail', 'performance_process_tracking', 'performance_process_reports', 'performance_president_approvals', 'performance_personnel_support_publish_approval', 'performance_archive', 'performance_interim_notes', 'performance_development_guidance', 'performance_meeting_p3_reminders', 'performance_meeting_development', 'performance_meeting_test_scenarios', 'performance_meeting_development_faz3', 'performance_meeting_final_gate', 'performance_kpi_dashboard', 'performance_kpi_management', 'performance_competency_library', 'performance_self_assessment', 'performance_kpi_analysis'}

_BYS360_PERFORMANCE_MAIN_KEYS_V4 = {'performance_module', 'performance_management', 'performans_yonetimi'}

_BYS360_PERFORMANCE_GENERAL_SHORTCUT_KEYS_V4 = {'performance_tasks', 'performance_scorecard', 'performance_archive', 'my_performance_comparison', 'performance_reports'}

_BYS360_PERF_RM_V8_MAIN_KEYS = {"performance_module", "performance_management", "performans_yonetimi"}

_BYS360_PERF_RM_V8_ALIAS_GROUPS = {
    "performance_tasks": ["performance_tasks"],
    "performance_scorecard": ["performance_scorecard", "scorecards"],
    "my_performance_comparison": ["my_performance_comparison"],
    "performance_reports": ["performance_reports"],
    "performance_archive": ["performance_archive"],
    "performance_dashboard": ["performance_dashboard"],
    "performance_criteria": ["performance_criteria", "criteria"],
    "performance_periods": ["performance_periods", "periods"],
    "performance_evaluation_tasks": ["performance_evaluation_tasks", "assignments"],
    "performance_task_management": ["performance_task_management"],
    "performance_hierarchy_tree": ["performance_hierarchy_tree"],
    "performance_hierarchy_assignments": ["performance_hierarchy_assignments"],
    "performance_team_compare": ["performance_team_compare", "team_analysis"],
    "team_performance_comparison_history": ["team_performance_comparison_history"],
    "performance_feedback_meetings": ["performance_feedback_meetings", "feedback_meetings"],
    "performance_publish": ["performance_publish", "publish"],
    "performance_mail_settings": ["performance_mail_settings", "performance_mail"],
    "performance_process_tracking": ["performance_process_tracking"],
    "performance_process_reports": ["performance_process_reports"],
    "performance_president_approvals": ["performance_president_approvals"],
    "performance_personnel_support_publish_approval": ["performance_personnel_support_publish_approval"],
    "performance_interim_notes": ["performance_interim_notes"],
    "performance_development_guidance": ["performance_development_guidance"],
    "performance_meeting_p3_reminders": ["performance_meeting_p3_reminders"],
    # BYS360_MEETING_DEV_P0_NAV_FIX_ALIAS_GROUPS
    "performance_meeting_development": ["performance_meeting_development"],
    "performance_meeting_test_scenarios": ["performance_meeting_test_scenarios"],
    "performance_meeting_development_faz3": ["performance_meeting_development_faz3"],
    "performance_meeting_final_gate": ["performance_meeting_final_gate"],
    # /BYS360_MEETING_DEV_P0_NAV_FIX_ALIAS_GROUPS
    "performance_feedback_aftercare": ["performance_feedback_aftercare"],
    "performance_feedback_aftercare_new": ["performance_feedback_aftercare_new"],
    "performance_feedback_meeting_guide": ["performance_feedback_meeting_guide"],
    "performance_feedback_followup": ["performance_feedback_followup"],
    "performance_kpi_dashboard": ["performance_kpi_dashboard"],
    "performance_kpi_management": ["performance_kpi_management"],
    "performance_competency_library": ["performance_competency_library"],
    "performance_self_assessment": ["performance_self_assessment"],
    "performance_kpi_analysis": ["performance_kpi_analysis"],
    "performance_history_import": ["performance_history_import"],
}

_BYS360_PERF_RM_V8_CHILD_KEYS = {key for values in _BYS360_PERF_RM_V8_ALIAS_GROUPS.values() for key in values}

_BYS360_PERF_RM_V8_CANONICAL_CHILD_KEYS = set(_BYS360_PERF_RM_V8_ALIAS_GROUPS.keys())

_BYS360_GENERAL_CATEGORY_SECTION_KEYS_V1 = {"general_section", "genel", "general"}

_BYS360_GENERAL_CATEGORY_CHILD_KEYS_V1 = {
    "home",
    "dashboard",
    "notifications",
    "support_index",
    "support_new",
    "support_my_tickets",
    "support_assigned",
    "support_all",
    "support_help_admin",
}

PORTAL_ROLE_MATRIX_V2_12_KEYS = {
    "portal_feed", "portal_people", "portal_profiles", "portal_post_create", "portal_wall_post",
    "portal_post_interact", "portal_post_report", "portal_post_delete", "portal_groups",
    "portal_group_create", "portal_moderation",
}

PORTAL_ROLE_MATRIX_V2_12_DEFAULTS = {
    "admin": PORTAL_ROLE_MATRIX_V2_12_KEYS,
    "baskan": PORTAL_ROLE_MATRIX_V2_12_KEYS,
    "baskan_yardimcisi": PORTAL_ROLE_MATRIX_V2_12_KEYS,
    "grup_baskani": PORTAL_ROLE_MATRIX_V2_12_KEYS,
    "mali_musavir": PORTAL_ROLE_MATRIX_V2_12_KEYS,
    "koordinator": PORTAL_ROLE_MATRIX_V2_12_KEYS - {"portal_moderation"},
    "birim_sorumlusu": PORTAL_ROLE_MATRIX_V2_12_KEYS - {"portal_moderation"},
    "personel": PORTAL_ROLE_MATRIX_V2_12_KEYS - {"portal_group_create", "portal_moderation"},
}

_BYS360_EXEC_KNOWN_KEYS = {'daily_weather_mail', 'executive_summary_tasks', 'executive_summary_automatic_emails', 'executive_summary_auto_emails', 'executive_summary_logs', 'executive_summary_mail_logs', 'executive_summary_panel', 'executive_summary_test_send', 'executive_daily_weather_mail', 'executive_summary_scheduled_jobs', 'executive_summary_test', 'executive_summary', 'executive_summary_admin_panel', 'executive_summary_dashboard'}

_BYS360_EXEC_URL_MARKERS = ('/dashboard/yonetici-ozeti', '/executive-summary', '/yonetici-ozeti')

def normalize_role_name(value: Any) -> str:
    return str(value or "").strip().lower()

def _rollback(rollback: RollbackHook | None) -> None:
    if rollback is None:
        return
    try:
        rollback()
    except Exception:
        import logging
        logging.getLogger(__name__).exception("BYS360_MAINTENANCE_V13_P1_SILENT_EXCEPTION_LOGGER | app/services/settings/effective_menu.py")

def _safe_query_all(query: Any, *, rollback: RollbackHook | None = None) -> list[Any]:
    try:
        return list(query.all())
    except Exception:
        _rollback(rollback)
        return []

def _get_unit_name_for_authority(user: Any) -> str:
    for attr in ("birim", "unit_name", "department", "organization_unit_name"):
        value = getattr(user, attr, None)
        if value:
            return str(value or "").strip()
    try:
        unit = getattr(user, "organization_unit", None)
        if unit is not None:
            return str(getattr(unit, "name", "") or "").strip()
    except Exception:
        import logging
        logging.getLogger(__name__).exception("BYS360 SAFE V6: sessiz yakalanan hata loglandi.")
        return ""
    return ""

def _row_map_by_key(rows: list[Any]) -> dict[str, bool]:
    result: dict[str, bool] = {}
    for row in rows or []:
        key = str(getattr(row, "menu_key", "") or "").strip()
        if not key or is_removed_menu_key(key):
            continue
        result[key] = bool(getattr(row, "is_visible", False))
    return result

def _load_role_matrix_state(role_name: str, *, rollback: RollbackHook | None = None) -> dict[str, bool]:
    normalized_role = normalize_role_name(role_name)
    if not normalized_role:
        return {}
    rows = _safe_query_all(RoleMenuDefault.query.filter_by(role_name=normalized_role), rollback=rollback)
    return _row_map_by_key(rows)

def _load_unit_profile_state(user: Any, *, rollback: RollbackHook | None = None) -> dict[str, bool]:
    unit_name = _get_unit_name_for_authority(user)
    if not unit_name:
        return {}
    try:
        from app.models import UnitMenuProfile
    except Exception:
        import logging
        logging.getLogger(__name__).exception("BYS360 SAFE V6: sessiz yakalanan hata loglandi.")
        return {}
    rows = _safe_query_all(UnitMenuProfile.query.filter_by(unit_name=unit_name), rollback=rollback)
    return _row_map_by_key(rows)

def _load_user_override_state(user: Any, *, rollback: RollbackHook | None = None) -> dict[str, bool]:
    user_id = getattr(user, "id", None)
    if not user_id:
        return {}
    rows = _safe_query_all(UserMenuPermission.query.filter_by(user_id=user_id), rollback=rollback)
    return _row_map_by_key(rows)

def _bys360_press_news_role(value: object) -> str:
    text = str(value or "").strip().lower().replace("-", "_").replace(" ", "_")
    return (text.replace("İ", "i").replace("I", "i").replace("ı", "i")
                .replace("Ş", "s").replace("ş", "s")
                .replace("Ğ", "g").replace("ğ", "g")
                .replace("Ü", "u").replace("ü", "u")
                .replace("Ö", "o").replace("ö", "o")
                .replace("Ç", "c").replace("ç", "c"))

def _bys360_performance_role_state(role_name, *, rollback=None):
    try:
        return _load_role_matrix_state(normalize_role_name(role_name), rollback=rollback)
    except Exception:
        import logging
        logging.getLogger(__name__).exception("BYS360 SAFE V6: sessiz yakalanan hata loglandi.")
        return {}

def _bys360_apply_performance_main_switch(visibility, user, role_name, *, rollback=None):
    role_state = _bys360_performance_role_state(role_name, rollback=rollback)
    main_has_explicit = any(_key in role_state for _key in _BYS360_PERFORMANCE_MAIN_KEYS)
    if main_has_explicit:
        main_enabled = any(bool(role_state.get(_key)) for _key in _BYS360_PERFORMANCE_MAIN_KEYS)
    else:
        main_enabled = any(bool(visibility.get(_key)) for _key in _BYS360_PERFORMANCE_CHILD_KEYS)
    visibility["performance_module"] = bool(main_enabled)
    visibility["performance_management"] = bool(main_enabled)
    visibility["performans_yonetimi"] = bool(main_enabled)
    if not main_enabled:
        for _key in _BYS360_PERFORMANCE_CHILD_KEYS:
            if _key in visibility:
                visibility[_key] = False
    return visibility

def _bys360_restore_general_section_v4(visibility, user):
    # En az Anasayfa/Dashboard çekirdeği korunur. Genel bölüm kapatılmak istenirse ileride ayrı ana anahtar bilinçli kapatılır.
    visibility.setdefault("general_section", True)
    visibility.setdefault("home", True)
    visibility.setdefault("dashboard", True)
    if bool(visibility.get("general_section", True)):
        visibility["home"] = bool(visibility.get("home", True))
        visibility["dashboard"] = bool(visibility.get("dashboard", True))
    return visibility

def _bys360_apply_performance_shortcut_gate_v4(visibility):
    main_enabled = any(bool(visibility.get(_key, _key == "performance_module")) for _key in _BYS360_PERFORMANCE_MAIN_KEYS_V4)
    if not main_enabled:
        for _key in _BYS360_PERFORMANCE_GENERAL_SHORTCUT_KEYS_V4:
            visibility[_key] = False
    return visibility

def _bys360_perf_rm_v8_norm_role(value):
    return str(value or "").strip().lower()

def _bys360_perf_rm_v8_state_for_keys(keys, role_state, unit_state, user_state):
    """Rol > birim > kişi sıralamasıyla açık/kapat kararını döndürür.

    Rol matrisi kapalıysa birim/kişi açamaz. Rol matrisi açık veya kayıt yoksa
    birim ve kişi istisnaları çalışır.
    """
    keys = list(keys or [])
    value = None
    role_decision = None
    for key in keys:
        if key in role_state:
            role_decision = bool(role_state[key])
            value = role_decision
            break
    if role_decision is False:
        return False
    for key in keys:
        if key in unit_state:
            value = bool(unit_state[key])
    for key in keys:
        if key in user_state:
            value = bool(user_state[key])
    return value

def _bys360_perf_rm_v8_apply_aliases(visibility, role_state, unit_state, user_state):
    for canonical, aliases in _BYS360_PERF_RM_V8_ALIAS_GROUPS.items():
        decision = _bys360_perf_rm_v8_state_for_keys([canonical] + [a for a in aliases if a != canonical], role_state, unit_state, user_state)
        if decision is not None:
            visibility[canonical] = bool(decision)
            for alias in aliases:
                visibility[alias] = bool(decision)
        else:
            # Eski aliaslardan biri farklı katmanda açık kaldıysa canonical sol menü anahtarına aktar.
            if any(bool(visibility.get(alias)) for alias in aliases):
                visibility[canonical] = True
                for alias in aliases:
                    visibility[alias] = True
    return visibility

def _bys360_perf_rm_v8_apply_main_gate(visibility, role_state, unit_state, user_state):
    child_visible = any(bool(visibility.get(key)) for key in _BYS360_PERF_RM_V8_CANONICAL_CHILD_KEYS)
    child_explicit_true = False
    for canonical, aliases in _BYS360_PERF_RM_V8_ALIAS_GROUPS.items():
        decision = _bys360_perf_rm_v8_state_for_keys([canonical] + [a for a in aliases if a != canonical], role_state, unit_state, user_state)
        if decision is True:
            child_explicit_true = True
            break
    main_decision = _bys360_perf_rm_v8_state_for_keys(list(_BYS360_PERF_RM_V8_MAIN_KEYS), role_state, unit_state, user_state)

    if child_visible or child_explicit_true:
        main_enabled = True
    elif main_decision is not None:
        main_enabled = bool(main_decision)
    else:
        main_enabled = False

    for key in _BYS360_PERF_RM_V8_MAIN_KEYS:
        visibility[key] = bool(main_enabled)
    if not main_enabled:
        for key in _BYS360_PERF_RM_V8_CHILD_KEYS | _BYS360_PERF_RM_V8_CANONICAL_CHILD_KEYS:
            visibility[key] = False
    return visibility

def _bys360_person_matrix_user_is_admin_v1(user: Any) -> bool:
    role = normalize_role_name(getattr(user, "role", ""))
    return bool(
        role in {"admin", "super_admin", "system_admin", "sistem_yoneticisi"}
        or getattr(user, "is_admin", False)
        or getattr(user, "is_superuser", False)
    )

def _bys360_person_matrix_can_open_v1(key: str, item: dict[str, Any] | None, user: Any) -> bool:
    """Kişiye özel matrisin hangi menüleri açabileceğini denetler.

    Kural:
    - Kaldırılmış/kapsam dışı menüler hiçbir şekilde açılamaz.
    - admin_only olarak işaretlenen çekirdek yönetim ekranları admin olmayan kişiye
      menüde açılmaz; backend yetki koruması ayrıca devam eder.
    - Bunun dışındaki canlı menüler kişi bazlı rol matrisiyle açılıp kapatılabilir.
    """
    if not key or is_removed_menu_key(key):
        return False
    item = item or {}
    return not (item.get("admin_only") and not _bys360_person_matrix_user_is_admin_v1(user))

def _bys360_general_category_bool_v1(value):
    return bool(value is True or str(value or "").strip().lower() in {"1", "true", "evet", "yes", "on", "aktif", "visible", "acik", "açık"})

def _bys360_general_category_state_v1(user, role_name, *, rollback=None):
    state = {}
    try:
        state.update(_load_role_matrix_state(role_name, rollback=rollback) or {})
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        __import__("logging").getLogger(__name__).exception("BYS360 kalite denetimi: sessiz except/pass yakalandi (app/services/settings/effective_menu.py:1668)")
    try:
        state.update(_load_unit_profile_state(user, rollback=rollback) or {})
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        __import__("logging").getLogger(__name__).exception("BYS360 kalite denetimi: sessiz except/pass yakalandi (app/services/settings/effective_menu.py:1672)")
    try:
        state.update(_load_user_override_state(user, rollback=rollback) or {})
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        __import__("logging").getLogger(__name__).exception("BYS360 kalite denetimi: sessiz except/pass yakalandi (app/services/settings/effective_menu.py:1676)")
    return state

def _bys360_apply_general_category_visibility_fix_v1(visibility, user, *, rollback=None):
    visibility = dict(visibility or {})
    try:
        role_name = normalize_role_name(getattr(user, "role", "")) if user is not None else ""
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        role_name = str(getattr(user, "role", "") if user is not None else "").strip().lower()

    state = _bys360_general_category_state_v1(user, role_name, rollback=rollback)
    explicit_section_open = any(_bys360_general_category_bool_v1(state.get(key)) or _bys360_general_category_bool_v1(visibility.get(key)) for key in _BYS360_GENERAL_CATEGORY_SECTION_KEYS_V1)
    child_open = any(_bys360_general_category_bool_v1(visibility.get(key)) for key in _BYS360_GENERAL_CATEGORY_CHILD_KEYS_V1)

    # Alt sekme aciksa eski general_section=false kaydi kategoriyi saklayamaz.
    if child_open or explicit_section_open:
        visibility["general_section"] = True
        visibility["genel"] = True
        visibility["general"] = True

    # Genel kategori acik ama hic alt satir acik degilse bos kategori yerine guvenli giris satirlari acilir.
    if explicit_section_open and not child_open:
        if state.get("home") is not False:
            visibility["home"] = True
        if state.get("dashboard") is not False:
            visibility["dashboard"] = True

    visibility["account"] = True
    visibility["logout"] = True
    return visibility

def _bys360_force_home_menu_visible_v1(visibility, user):
    visibility = dict(visibility or {})
    visibility["general_section"] = True
    visibility["genel"] = True
    visibility["general"] = True
    visibility["home"] = True
    visibility["account"] = True
    visibility["logout"] = True
    return visibility

def _bys360_portal_role_matrix_v2_12_apply(visibility, user, *, rollback=None):
    visibility = dict(visibility or {})
    role_name = normalize_role_name(getattr(user, "role", "")) if user is not None else ""
    try:
        role_state = _load_role_matrix_state(role_name, rollback=rollback) or {}
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        role_state = {}
    try:
        unit_state = _load_unit_profile_state(user, rollback=rollback) or {}
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        unit_state = {}
    try:
        user_state = _load_user_override_state(user, rollback=rollback) or {}
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        user_state = {}
    defaults = set(PORTAL_ROLE_MATRIX_V2_12_DEFAULTS.get(role_name, set()))
    for key in PORTAL_ROLE_MATRIX_V2_12_KEYS:
        if key in role_state:
            visibility[key] = bool(role_state[key])
        elif key not in visibility:
            visibility[key] = key in defaults
        if key in unit_state:
            if role_state.get(key) is False:
                visibility[key] = False
            else:
                visibility[key] = bool(unit_state[key])
        if key in user_state:
            if role_state.get(key) is False:
                visibility[key] = False
            else:
                visibility[key] = bool(user_state[key])
    return visibility

def _bys360_exec_norm(value: object) -> str:
    try:
        base = normalize_role_name(value)
    except Exception:
        logger = __import__("logging").getLogger(__name__)
        logger.exception("BYS360 effective menu isleminde hata yakalandi")
        base = str(value or "").strip().lower()
    return str(base or "").strip().lower().replace("-", "_").replace(" ", "_")

def _bys360_is_exec_summary_menu_key(key: object) -> bool:
    k = str(key or "").strip().lower()
    if not k:
        return False
    if k in _BYS360_EXEC_KNOWN_KEYS:
        return True
    if "executive_summary" in k or "executive-summary" in k:
        return True
    if "yonetici_ozeti" in k or "yonetici-ozeti" in k:
        return True
    return "daily_weather_mail" in k or "gunluk_hava_maili" in k or "gunluk_personel_bilgilendirme" in k

def _bys360_exec_item_matches(item: dict[str, object]) -> bool:
    try:
        key = item.get("key")
        if _bys360_is_exec_summary_menu_key(key):
            return True
        hay = " ".join(str(item.get(name) or "") for name in ("label", "url", "endpoint"))
        hay_l = hay.lower()
        return any(marker in hay_l for marker in _BYS360_EXEC_URL_MARKERS) or "yönetici özeti" in hay_l or "yonetici ozeti" in hay_l
    except Exception:
        import logging
        logging.getLogger(__name__).exception("BYS360 SAFE V6: sessiz yakalanan hata loglandi.")
        return False

def _bys360_admin_period_reminder_norm_v1(value):
    text = str(value or "").strip().lower()
    return (text
            .replace("İ", "i").replace("ı", "i")
            .replace("ğ", "g").replace("ü", "u").replace("ş", "s")
            .replace("ö", "o").replace("ç", "c")
            .replace("-", "_").replace(" ", "_"))

def _bys360_admin_period_reminder_is_admin_v1(user):
    if not user:
        return False
    for attr in ("is_admin", "is_superuser", "is_system_admin", "is_sistem_yoneticisi"):
        try:
            if bool(getattr(user, attr, False)):
                return True
        except Exception:
            pass
    terms = set()
    for attr in ("role", "role_name", "user_role", "authority_level", "title", "unvan", "position", "gorev", "username"):
        with contextlib.suppress(Exception):
            terms.add(_bys360_admin_period_reminder_norm_v1(getattr(user, attr, "")))
    try:
        role_obj = getattr(user, "role", None)
        terms.add(_bys360_admin_period_reminder_norm_v1(getattr(role_obj, "name", "")))
        terms.add(_bys360_admin_period_reminder_norm_v1(getattr(role_obj, "role_name", "")))
    except Exception:
        pass
    return bool(terms & {
        "admin", "administrator", "super_admin", "system_admin",
        "sistem_yoneticisi", "sistem_yöneticisi", "yonetici", "yönetici"
    })

__all__ = [
    "_bys360_admin_period_reminder_is_admin_v1",
    "_bys360_admin_period_reminder_norm_v1",
    "_bys360_apply_general_category_visibility_fix_v1",
    "_bys360_apply_performance_main_switch",
    "_bys360_apply_performance_shortcut_gate_v4",
    "_bys360_exec_item_matches",
    "_bys360_exec_norm",
    "_bys360_force_home_menu_visible_v1",
    "_bys360_general_category_bool_v1",
    "_bys360_general_category_state_v1",
    "_bys360_is_exec_summary_menu_key",
    "_bys360_perf_rm_v8_apply_aliases",
    "_bys360_perf_rm_v8_apply_main_gate",
    "_bys360_perf_rm_v8_norm_role",
    "_bys360_perf_rm_v8_state_for_keys",
    "_bys360_performance_role_state",
    "_bys360_person_matrix_can_open_v1",
    "_bys360_person_matrix_user_is_admin_v1",
    "_bys360_portal_role_matrix_v2_12_apply",
    "_bys360_press_news_role",
    "_bys360_restore_general_section_v4",
    "_get_unit_name_for_authority",
    "_load_role_matrix_state",
    "_load_unit_profile_state",
    "_load_user_override_state",
    "_rollback",
    "_row_map_by_key",
    "_safe_query_all",
    "normalize_role_name",
]
