"""PHASE3 menu constants split from app.services.settings.effective_menu.

Generated by Phase4J V37C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

PHASE3_PERFORMANCE_MENU_POLICY: dict[str, set[str]] = {
    # Personel: kendi karnesi ve kendi kıyas/ortalama görünümü.
    "performance_scorecard": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},
    "my_performance_comparison": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},

    # Koordinatör/Grup Başkanı: kendi kapsamındaki personel ve ortalamalar.
    "performance_reports": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_team_compare": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "team_performance_comparison_history": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},

    # Yönetim ekranları: genel/teknik yönetim ailesi.
    "performance_criteria": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi"},
    "performance_periods": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi"},
    "performance_task_management": {"admin", "sistem_yoneticisi", "system_admin", "super_admin"},
    "performance_hierarchy_tree": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_hierarchy_assignments": {"admin", "sistem_yoneticisi", "system_admin", "super_admin"},
    "performance_publish": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan"},
    "performance_history_import": {"admin", "sistem_yoneticisi", "system_admin", "super_admin"},
}

PHASE3_2_MENU_VISIBILITY_MARKER = "BYS360_PHASE3_2_MENU_VISIBILITY"

PHASE3_2_PERFORMANCE_MENU_POLICY: dict[str, set[str]] = {
    # Personel: yalnızca kendi karnesi ve kendi grup/kategori ortalaması tarafı.
    "performance_scorecard": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu", "personel", "user", "standart_personel"},
    "my_performance_comparison": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu", "personel", "user", "standart_personel"},

    # Koordinatör ve Grup Başkanı: yalnızca kendi kapsamındaki personel/ortalama ekranları.
    "performance_reports": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_team_compare": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "team_performance_comparison_history": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_evaluation_tasks": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_tasks": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_interim_notes": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_development_guidance": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    # BYS360_MEETING_DEV_P0_NAV_FIX_PHASE3_2_POLICY
    "performance_meeting_development": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_meeting_test_scenarios": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_meeting_development_faz3": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_meeting_final_gate": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    # /BYS360_MEETING_DEV_P0_NAV_FIX_PHASE3_2_POLICY
    "performance_feedback_meetings": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},

    # Başkan/Admin: genel yönetim görünümü.
    "performance_criteria": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "performance_periods": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "performance_hierarchy_tree": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_publish": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president"},
    "performance_president_approvals": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president"},
    "performance_personnel_support_publish_approval": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "grup_baskani", "grup_başkanı"},

    # Teknik yönetim: yalnızca Admin/Sistem Yöneticisi.
    "performance_task_management": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},
    "performance_hierarchy_assignments": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},
    "performance_history_import": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},
    "performance_mail_settings": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},

    # Stratejik Performans — KPI, Hedef, Yetkinlik, Öz Değerlendirme
    "performance_kpi_dashboard": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
    "performance_kpi_management": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
    "performance_competency_library": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_self_assessment": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_kpi_analysis": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
}

PHASE3_2_PERSONNEL_VISIBLE_KEYS = {"performance_scorecard", "my_performance_comparison"}

PHASE3_2_MANAGER_VISIBLE_KEYS = {
    "performance_scorecard", "my_performance_comparison", "performance_reports",
    "performance_team_compare", "team_performance_comparison_history",
    "performance_evaluation_tasks", "performance_tasks", "performance_interim_notes",
    "performance_development_guidance", "performance_feedback_meetings", "performance_hierarchy_tree",
    # BYS360_MEETING_DEV_P0_NAV_FIX_MANAGER_VISIBLE
    "performance_meeting_development", "performance_meeting_test_scenarios",
    "performance_meeting_development_faz3", "performance_meeting_final_gate",
    # /BYS360_MEETING_DEV_P0_NAV_FIX_MANAGER_VISIBLE
}

PHASE3_2_GENERAL_VISIBLE_KEYS = set(PHASE3_2_PERFORMANCE_MENU_POLICY.keys())

__all__ = [
    "PHASE3_2_GENERAL_VISIBLE_KEYS",
    "PHASE3_2_MANAGER_VISIBLE_KEYS",
    "PHASE3_2_MENU_VISIBILITY_MARKER",
    "PHASE3_2_PERFORMANCE_MENU_POLICY",
    "PHASE3_2_PERSONNEL_VISIBLE_KEYS",
    "PHASE3_PERFORMANCE_MENU_POLICY",
]
