"""PHASE3 menu constants split from app.services.settings.effective_menu.

Generated by Phase4J V37C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

from __future__ import annotations
import logging
from collections.abc import Callable
from typing import Any
from app.config import is_removed_menu_key
from app.menu_registry import flatten_menu_definitions
from app.models import UserMenuPermission, RoleMenuDefault
from app.services.settings_service import build_effective_user_menu_context, get_role_default_menu_keys
from app.services.settings.effective_menu_parts.bys360_context import (
    _bys360_admin_period_reminder_is_admin_v1,
    _bys360_admin_period_reminder_norm_v1,
    _bys360_apply_general_category_visibility_fix_v1,
    _bys360_apply_performance_main_switch,
    _bys360_apply_performance_shortcut_gate_v4,
    _bys360_exec_item_matches,
    _bys360_exec_norm,
    _bys360_force_home_menu_visible_v1,
    _bys360_general_category_bool_v1,
    _bys360_general_category_state_v1,
    _bys360_is_exec_summary_menu_key,
    _bys360_perf_rm_v8_apply_aliases,
    _bys360_perf_rm_v8_apply_main_gate,
    _bys360_perf_rm_v8_norm_role,
    _bys360_perf_rm_v8_state_for_keys,
    _bys360_performance_role_state,
    _bys360_person_matrix_can_open_v1,
    _bys360_person_matrix_user_is_admin_v1,
    _bys360_portal_role_matrix_v2_12_apply,
    _bys360_press_news_role,
    _bys360_restore_general_section_v4,
    _get_unit_name_for_authority,
    _load_role_matrix_state,
    _load_unit_profile_state,
    _load_user_override_state,
    _rollback,
    _row_map_by_key,
    _safe_query_all,
    normalize_role_name,
)
from app.services.settings.effective_menu_parts.apply_context import (
    _allowed_by_static_gate,
    _apply_bys360_press_news_admin_only_policy,
    _apply_bys360_settings_live_authority_v1,
    _apply_core_menu_visibility_policy,
    _apply_phase3_2_performance_menu_visibility,
    _apply_phase3_performance_menu_policy,
    _apply_role_gate,
    _apply_role_matrix_closed_guard,
    _get_role_matrix_closed_keys_for_role,
    _menu_item_by_key,
    _phase3_2_ascii_tr,
    _phase3_2_normalize_role_name,
    _role_allowed_for_menu,
    _role_matrix_runtime_closed,
    _settings_explicitly_controls_key,
)
from app.services.settings.effective_menu_parts.bys360_constants import (
    _BYS360_AG5E_AI_TEACHING_MENU_KEY,
    _BYS360_AG5E_AI_TEACHING_ROLES,
    _BYS360_ALL_MENU_ROLE_MATRIX_AUTHORITY_KEYS,
    _BYS360_ALL_MENU_ROLE_MATRIX_POLICY,
    _BYS360_ASSISTANT_TAB_AUTHORITY_KEYS,
    _BYS360_ASSISTANT_TAB_POLICY,
    _BYS360_EXEC_ADMIN_ONLY_ROLES,
    _BYS360_EXEC_KNOWN_KEYS,
    _BYS360_EXEC_URL_MARKERS,
    _BYS360_GENERAL_CATEGORY_CHILD_KEYS_V1,
    _BYS360_GENERAL_CATEGORY_SECTION_KEYS_V1,
    _BYS360_GENERAL_CORE_KEYS_V4,
    _BYS360_MANUAL_POLICY,
    _BYS360_MANUAL_ROLE_MENU_ADDITIONS,
    _BYS360_PERFORMANCE_ALL_KEYS,
    _BYS360_PERFORMANCE_CHILD_KEYS,
    _BYS360_PERFORMANCE_CHILD_KEYS_V4,
    _BYS360_PERFORMANCE_GENERAL_SHORTCUT_KEYS_V4,
    _BYS360_PERFORMANCE_MAIN_KEYS,
    _BYS360_PERFORMANCE_MAIN_KEYS_V4,
    _BYS360_PERFORMANCE_MAIN_SWITCH_POLICY,
    _BYS360_PERFORMANCE_ROLE_MATRIX_NEW_TAB_POLICY,
    _BYS360_PERF_RM_V8_ALIAS_GROUPS,
    _BYS360_PERF_RM_V8_ALL_AUTH_ROLES,
    _BYS360_PERF_RM_V8_ALL_KEYS,
    _BYS360_PERF_RM_V8_CANONICAL_CHILD_KEYS,
    _BYS360_PERF_RM_V8_CHILD_KEYS,
    _BYS360_PERF_RM_V8_MAIN_KEYS,
    _BYS360_PERF_RM_V8_MANAGER_ROLES,
    _BYS360_PERF_RM_V8_ROLE_POLICY,
    _BYS360_PERIOD_CENTER_DEFAULT_ROLES_V221,
    _BYS360_PERIOD_CENTER_MENU_KEY_V221,
    _BYS360_PERSONEL_ALLOWED_POLICY,
    _BYS360_PERSONEL_DISALLOWED_POLICY_KEYS,
    _BYS360_PERSONEL_ROLE_MATRIX_CURRENT_ALLOWED_KEYS,
    _BYS360_PERSONEL_ROLE_MATRIX_CURRENT_MANAGER_ROLES,
    _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_KEYS,
    _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_MANAGER_ROLES,
    _BYS360_PERSONEL_ROLE_MATRIX_VISIBILITY_V7_OBSOLETE_KEYS,
    _BYS360_PROCESS_MENU_KEYS,
    _BYS360_PROCESS_MENU_ROLES,
    _BYS360_REMINDERS_ALLOWED_ROLES,
    _BYS360_REMINDERS_MENU_KEY,
    _BYS360_ROLE_MATRIX_V12_AUTHORITY_KEYS,
    _BYS360_ROLE_MATRIX_V12_POLICY,
    _BYS360_V223_PERIOD_CENTER_KEY_ROLES,
)

PHASE3_PERFORMANCE_MENU_POLICY: dict[str, set[str]] = {
    # Personel: kendi karnesi ve kendi kıyas/ortalama görünümü.
    "performance_scorecard": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},
    "my_performance_comparison": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu", "personel"},

    # Koordinatör/Grup Başkanı: kendi kapsamındaki personel ve ortalamalar.
    "performance_reports": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_team_compare": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "team_performance_comparison_history": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},

    # Yönetim ekranları: genel/teknik yönetim ailesi.
    "performance_criteria": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi"},
    "performance_periods": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi"},
    "performance_task_management": {"admin", "sistem_yoneticisi", "system_admin", "super_admin"},
    "performance_hierarchy_tree": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan", "baskan_yardimcisi", "grup_baskani", "mali_musavir", "koordinator", "birim_sorumlusu"},
    "performance_hierarchy_assignments": {"admin", "sistem_yoneticisi", "system_admin", "super_admin"},
    "performance_publish": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "baskan"},
    "performance_history_import": {"admin", "sistem_yoneticisi", "system_admin", "super_admin"},
}

PHASE3_2_MENU_VISIBILITY_MARKER = "BYS360_PHASE3_2_MENU_VISIBILITY"

PHASE3_2_PERFORMANCE_MENU_POLICY: dict[str, set[str]] = {
    # Personel: yalnızca kendi karnesi ve kendi grup/kategori ortalaması tarafı.
    "performance_scorecard": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu", "personel", "user", "standart_personel"},
    "my_performance_comparison": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu", "personel", "user", "standart_personel"},

    # Koordinatör ve Grup Başkanı: yalnızca kendi kapsamındaki personel/ortalama ekranları.
    "performance_reports": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_team_compare": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "team_performance_comparison_history": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_evaluation_tasks": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_tasks": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_interim_notes": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_development_guidance": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_feedback_meetings": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},

    # Başkan/Admin: genel yönetim görünümü.
    "performance_criteria": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "performance_periods": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı"},
    "performance_hierarchy_tree": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_publish": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president"},
    "performance_president_approvals": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president"},
    "performance_personnel_support_publish_approval": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "grup_baskani", "grup_başkanı"},

    # Teknik yönetim: yalnızca Admin/Sistem Yöneticisi.
    "performance_task_management": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},
    "performance_hierarchy_assignments": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},
    "performance_history_import": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},
    "performance_mail_settings": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator"},

    # Stratejik Performans — KPI, Hedef, Yetkinlik, Öz Değerlendirme
    "performance_kpi_dashboard": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
    "performance_kpi_management": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
    "performance_competency_library": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_self_assessment": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör", "birim_sorumlusu"},
    "performance_kpi_analysis": {"admin", "sistem_yoneticisi", "system_admin", "super_admin", "administrator", "baskan", "başkan", "president", "baskan_yardimcisi", "başkan_yardımcısı", "grup_baskani", "grup_başkanı", "mali_musavir", "mali_müşavir", "koordinator", "koordinatör"},
}

PHASE3_2_PERSONNEL_VISIBLE_KEYS = {"performance_scorecard", "my_performance_comparison"}

PHASE3_2_MANAGER_VISIBLE_KEYS = {
    "performance_scorecard", "my_performance_comparison", "performance_reports",
    "performance_team_compare", "team_performance_comparison_history",
    "performance_evaluation_tasks", "performance_tasks", "performance_interim_notes",
    "performance_development_guidance", "performance_feedback_meetings", "performance_hierarchy_tree",
}

PHASE3_2_GENERAL_VISIBLE_KEYS = set(PHASE3_2_PERFORMANCE_MENU_POLICY.keys())

__all__ = [
    "PHASE3_2_GENERAL_VISIBLE_KEYS",
    "PHASE3_2_MANAGER_VISIBLE_KEYS",
    "PHASE3_2_MENU_VISIBILITY_MARKER",
    "PHASE3_2_PERFORMANCE_MENU_POLICY",
    "PHASE3_2_PERSONNEL_VISIBLE_KEYS",
    "PHASE3_PERFORMANCE_MENU_POLICY",
]
