"""ROLE menu constants split from app.services.settings.effective_menu.

Generated by Phase4J V38C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

ROLE_MATRIX_RUNTIME_AUTHORITY_KEYS: set[str] = {
    "messages",
    "notifications",
    "surveys",
    "survey_manage",
    "survey_results",
    "feedback_dashboard",
    "feedback_pulse",
    "feedback_campaigns",
    "feedback_results",
    "feedback_actions",
    "feedback_manager",
    "feedback_admin",
    "portal_press_news",
    "announcements",
    "assistant_center",
    "assistant_my_reminders",
    "assistant_scheduled_tasks",
    "assistant_report_generate",
    "assistant_report_share",
    "assistant_ai_summary",
    "assistant_process_alerts",
    "assistant_logs",
    "assistant_settings",
}

__all__ = [
    "ROLE_MATRIX_RUNTIME_AUTHORITY_KEYS",
]
