# -*- coding: utf-8 -*-
"""
BYS360 EMERGENCY RESTORE REMOVE EXEC MENU V2.14.18

Amaç:
- Beyaz ekranı düzeltmek için app/templates/base.html içindeki tüm Yönetici Özeti menü denemelerini temizler.
- V2.14.17 veya önceki Yönetici Özeti blokları HTML yapısını bozduysa kaldırır.
- Mümkünse en yakın güvenli backup'tan base.html'i geri alır, sonra yine tüm Yönetici Özeti deneme bloklarını temizler.
- Yeni Yönetici Özeti menüsü eklemez.
- Veritabanına, route'a, diğer modüllere dokunmaz.
- Öncelik: Canlıyı ve sol şeridi eski sağlam hale getirmek.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import sys
from pathlib import Path


VERSION = "V2.14.18"


def read_text(path: Path) -> str:
    for enc in ("utf-8", "utf-8-sig", "cp1254", "latin-1"):
        try:
            return path.read_text(encoding=enc)
        except UnicodeDecodeError:
            continue
    return path.read_text(encoding="utf-8", errors="ignore")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="")


def backup_current(path: Path, project_root: Path) -> str:
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    out = project_root / "backups" / f"emergency_restore_remove_exec_menu_{VERSION}_{stamp}" / path.relative_to(project_root)
    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, out)
    return str(out)


def latest_backup_with_base(project_root: Path) -> Path | None:
    """
    Finds the newest backup folder containing app/templates/base.html.
    Excludes current emergency folder pattern if any.
    """
    bdir = project_root / "backups"
    if not bdir.exists():
        return None

    candidates = []
    for d in bdir.iterdir():
        if not d.is_dir():
            continue
        base = d / "app" / "templates" / "base.html"
        if base.exists():
            candidates.append(d)

    if not candidates:
        return None

    candidates.sort(key=lambda p: p.name, reverse=True)
    return candidates[0]


def strip_exec_blocks(text: str) -> str:
    # Remove all marker-managed executive summary attempts.
    marker_pairs = [
        ("BYS360_EXECUTIVE_SUMMARY_BEFORE_FOOTER_STYLE_START", "BYS360_EXECUTIVE_SUMMARY_BEFORE_FOOTER_STYLE_END"),
        ("BYS360_EXECUTIVE_SUMMARY_BEFORE_FOOTER_MENU_START", "BYS360_EXECUTIVE_SUMMARY_BEFORE_FOOTER_MENU_END"),
        ("BYS360_EXECUTIVE_SUMMARY_BOTTOM_STYLE_START", "BYS360_EXECUTIVE_SUMMARY_BOTTOM_STYLE_END"),
        ("BYS360_EXECUTIVE_SUMMARY_BOTTOM_MENU_START", "BYS360_EXECUTIVE_SUMMARY_BOTTOM_MENU_END"),
        ("BYS360_EXECUTIVE_SUMMARY_STATIC_STYLE_START", "BYS360_EXECUTIVE_SUMMARY_STATIC_STYLE_END"),
        ("BYS360_EXECUTIVE_SUMMARY_STATIC_MENU_START", "BYS360_EXECUTIVE_SUMMARY_STATIC_MENU_END"),
        ("BYS360_EXECUTIVE_SUMMARY_SOLID_MENU_START", "BYS360_EXECUTIVE_SUMMARY_SOLID_MENU_END"),
        ("BYS360_EXECUTIVE_SUMMARY_SAFE_MENU_START", "BYS360_EXECUTIVE_SUMMARY_SAFE_MENU_END"),
        ("BYS360_EXECUTIVE_SUMMARY_MENU_START", "BYS360_EXECUTIVE_SUMMARY_MENU_END"),
    ]

    for start, end in marker_pairs:
        text = re.sub(
            r"\s*<!--\s*" + re.escape(start) + r"[^>]*-->.*?<!--\s*" + re.escape(end) + r"[^>]*-->\s*",
            "\n",
            text,
            flags=re.I | re.S,
        )

    # Remove style/script tags generated by our executive menu attempts.
    text = re.sub(
        r"\s*<style[^>]*(?:bys360-exec|bys360-executive-summary|executive-summary)[^>]*>.*?</style>\s*",
        "\n",
        text,
        flags=re.I | re.S,
    )
    text = re.sub(
        r"\s*<script[^>]*(?:bys360-exec|bys360-executive-summary|executive-summary)[^>]*>.*?</script>\s*",
        "\n",
        text,
        flags=re.I | re.S,
    )

    # Remove standalone menu groups/classes if marker was damaged.
    class_patterns = [
        r"\s*<div\b[^>]*(?:bys360-executive-summary-before-footer|bys360-executive-summary-bottom|bys360-executive-summary-static|bys360-exec-solid-group|bys360-exec-safe-group)[^>]*>.*?</div>\s*",
    ]
    for pat in class_patterns:
        text = re.sub(pat, "\n", text, flags=re.I | re.S)

    # Remove old single link to Yönetici Özeti only if it is a direct anchor.
    text = re.sub(
        r"\n[ \t]*<a\b[^>]*href=[\"'][^\"']*yonetici-ozeti[^\"']*[\"'][^>]*>.*?Yönetici\s+Özeti.*?</a>[ \t]*",
        "\n",
        text,
        flags=re.I | re.S,
    )

    return re.sub(r"\n{3,}", "\n\n", text)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    base = project_root / "app" / "templates" / "base.html"

    if not base.exists():
        print(f"ERROR: base.html bulunamadı: {base}", file=sys.stderr)
        return 2

    current_backup = backup_current(base, project_root)

    # Try restoring from newest backup that has base.html, but avoid using the just-created backup folder
    # by finding after current backup creation and excluding current backup root name.
    backup_root = latest_backup_with_base(project_root)
    restored_from = None

    if backup_root and (backup_root / "app" / "templates" / "base.html").exists():
        # If newest is our just-created emergency backup, use current file cleanup only.
        if "emergency_restore_remove_exec_menu" not in backup_root.name:
            shutil.copy2(backup_root / "app" / "templates" / "base.html", base)
            restored_from = str(backup_root / "app" / "templates" / "base.html")

    cleaned = strip_exec_blocks(read_text(base))
    write_text(base, cleaned)

    print({
        "ok": True,
        "version": VERSION,
        "message": "Yönetici Özeti menü denemeleri temizlendi. Yeni menü eklenmedi. Beyaz ekran için base.html sadeleştirildi.",
        "base": str(base),
        "backup_before_change": current_backup,
        "restored_from": restored_from,
    })
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
