
"""BYS360 schema guard - çekirdek tablo onarım tanımları.

audit_logs, message_*, leave_balances, personnel_leaves,
attendance_exceptions, delegation_assignments,
ai_*, assignment_coverage_logs tablolarını kapsar.
"""
from __future__ import annotations

from app.schema_guard_types import TableRepair

TABLE_REPAIRS: tuple[TableRepair, ...] = (
    TableRepair(
        table="audit_logs",
        create_sql="""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NULL REFERENCES users(id),
            action VARCHAR(100) NOT NULL DEFAULT 'bilinmiyor',
            entity_type VARCHAR(100) NOT NULL DEFAULT 'genel',
            entity_id INTEGER NULL,
            old_data_json TEXT NULL,
            new_data_json TEXT NULL,
            summary VARCHAR(255) NULL,
            endpoint VARCHAR(255) NULL,
            ip_address VARCHAR(64) NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_id INTEGER NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS action VARCHAR(100) NOT NULL DEFAULT 'bilinmiyor'",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_type VARCHAR(100) NOT NULL DEFAULT 'genel'",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_id INTEGER NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS old_data_json TEXT NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS new_data_json TEXT NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS summary VARCHAR(255) NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS endpoint VARCHAR(255) NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address VARCHAR(64) NULL",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs (action)",
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON audit_logs (created_at)",
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_id ON audit_logs (entity_id)",
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_type ON audit_logs (entity_type)",
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_endpoint ON audit_logs (endpoint)",
            "CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON audit_logs (user_id)",
        ),
    ),
    TableRepair(
        table="message_threads",
        create_sql="""
        CREATE TABLE IF NOT EXISTS message_threads (
            id SERIAL PRIMARY KEY,
            thread_type VARCHAR(30) NOT NULL DEFAULT 'direct',
            subject VARCHAR(255) NULL,
            badge_label VARCHAR(120) NULL,
            icon_name VARCHAR(100) NULL,
            accent_color VARCHAR(20) NULL,
            created_by_user_id INTEGER NOT NULL REFERENCES users(id),
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            last_message_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS thread_type VARCHAR(30) NOT NULL DEFAULT 'direct'",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS subject VARCHAR(255) NULL",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS badge_label VARCHAR(120) NULL",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS icon_name VARCHAR(100) NULL",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20) NULL",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER NULL",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMP NULL",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE message_threads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_message_threads_thread_type ON message_threads (thread_type)",
            "CREATE INDEX IF NOT EXISTS ix_message_threads_created_by_user_id ON message_threads (created_by_user_id)",
            "CREATE INDEX IF NOT EXISTS ix_message_threads_is_active ON message_threads (is_active)",
            "CREATE INDEX IF NOT EXISTS ix_message_threads_last_message_at ON message_threads (last_message_at)",
        ),
    ),

TableRepair(
    table="message_reactions",
    create_sql="""
    CREATE TABLE IF NOT EXISTS message_reactions (
        id SERIAL PRIMARY KEY,
        message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        reaction_value VARCHAR(16) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_message_reaction_user_message UNIQUE (message_id, user_id)
    )
    """,
    column_sql=(
        "ALTER TABLE message_reactions ADD COLUMN IF NOT EXISTS message_id INTEGER",
        "ALTER TABLE message_reactions ADD COLUMN IF NOT EXISTS user_id INTEGER",
        "ALTER TABLE message_reactions ADD COLUMN IF NOT EXISTS reaction_value VARCHAR(16) NOT NULL DEFAULT '👍'",
        "ALTER TABLE message_reactions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
        "ALTER TABLE message_reactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
    ),
    index_sql=(
        "CREATE INDEX IF NOT EXISTS ix_message_reactions_message_id ON message_reactions (message_id)",
        "CREATE INDEX IF NOT EXISTS ix_message_reactions_user_id ON message_reactions (user_id)",
        "CREATE INDEX IF NOT EXISTS ix_message_reactions_reaction_value ON message_reactions (reaction_value)",
    ),
),
TableRepair(
    table="message_typing_states",
    create_sql="""
    CREATE TABLE IF NOT EXISTS message_typing_states (
        id SERIAL PRIMARY KEY,
        thread_id INTEGER NOT NULL REFERENCES message_threads(id) ON DELETE CASCADE,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        preview_text VARCHAR(120) NULL,
        expires_at TIMESTAMP NOT NULL,
        last_activity_at TIMESTAMP NOT NULL DEFAULT NOW(),
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_message_typing_state_thread_user UNIQUE (thread_id, user_id)
    )
    """,
    column_sql=(
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS thread_id INTEGER",
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS user_id INTEGER",
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS preview_text VARCHAR(120) NULL",
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP NOT NULL DEFAULT NOW()",
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMP NOT NULL DEFAULT NOW()",
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
        "ALTER TABLE message_typing_states ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
    ),
    index_sql=(
        "CREATE INDEX IF NOT EXISTS ix_message_typing_states_thread_id ON message_typing_states (thread_id)",
        "CREATE INDEX IF NOT EXISTS ix_message_typing_states_user_id ON message_typing_states (user_id)",
        "CREATE INDEX IF NOT EXISTS ix_message_typing_states_expires_at ON message_typing_states (expires_at)",
        "CREATE INDEX IF NOT EXISTS ix_message_typing_states_last_activity_at ON message_typing_states (last_activity_at)",
    ),
),
    TableRepair(
        table="leave_balances",
        create_sql="""
        CREATE TABLE IF NOT EXISTS leave_balances (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            leave_type VARCHAR(50) NOT NULL,
            year INTEGER NULL,
            total_days DOUBLE PRECISION NOT NULL DEFAULT 0,
            carried_over_days DOUBLE PRECISION NOT NULL DEFAULT 0,
            used_days DOUBLE PRECISION NOT NULL DEFAULT 0,
            manual_override BOOLEAN NOT NULL DEFAULT FALSE,
            note TEXT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS user_id INTEGER",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS leave_type VARCHAR(50) NOT NULL DEFAULT 'yillik'",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS year INTEGER NULL",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS total_days DOUBLE PRECISION NOT NULL DEFAULT 0",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS carried_over_days DOUBLE PRECISION NOT NULL DEFAULT 0",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS used_days DOUBLE PRECISION NOT NULL DEFAULT 0",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS manual_override BOOLEAN NOT NULL DEFAULT FALSE",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS note TEXT NULL",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE leave_balances ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_leave_balances_user_id ON leave_balances (user_id)",
            "CREATE INDEX IF NOT EXISTS ix_leave_balances_leave_type ON leave_balances (leave_type)",
            "CREATE INDEX IF NOT EXISTS ix_leave_balances_year ON leave_balances (year)",
        ),
    ),
    TableRepair(
        table="personnel_leaves",
        create_sql="""
        CREATE TABLE IF NOT EXISTS personnel_leaves (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            period_id INTEGER NULL REFERENCES performance_periods(id) ON DELETE SET NULL,
            leave_type VARCHAR(50) NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'onayli',
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            approved_day_count DOUBLE PRECISION NULL,
            start_half_day BOOLEAN NOT NULL DEFAULT FALSE,
            end_half_day BOOLEAN NOT NULL DEFAULT FALSE,
            blocks_performance_evaluation BOOLEAN NOT NULL DEFAULT TRUE,
            performance_mode VARCHAR(20) NOT NULL DEFAULT 'partial',
            blocks_manager_duties BOOLEAN NOT NULL DEFAULT TRUE,
            description TEXT NULL,
            approved_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS user_id INTEGER",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS period_id INTEGER NULL",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS leave_type VARCHAR(50) NOT NULL DEFAULT 'yillik'",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'onayli'",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS start_date DATE NOT NULL DEFAULT CURRENT_DATE",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS end_date DATE NOT NULL DEFAULT CURRENT_DATE",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS approved_day_count DOUBLE PRECISION NULL",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS start_half_day BOOLEAN NOT NULL DEFAULT FALSE",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS end_half_day BOOLEAN NOT NULL DEFAULT FALSE",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS blocks_performance_evaluation BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS performance_mode VARCHAR(20) NOT NULL DEFAULT 'partial'",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS blocks_manager_duties BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS description TEXT NULL",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS approved_by_id INTEGER NULL",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP NULL",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE personnel_leaves ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_user_id ON personnel_leaves (user_id)",
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_period_id ON personnel_leaves (period_id)",
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_leave_type ON personnel_leaves (leave_type)",
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_status ON personnel_leaves (status)",
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_performance_mode ON personnel_leaves (performance_mode)",
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_start_date ON personnel_leaves (start_date)",
            "CREATE INDEX IF NOT EXISTS ix_personnel_leaves_end_date ON personnel_leaves (end_date)",
        ),
    ),
    TableRepair(
        table="attendance_exceptions",
        create_sql="""
        CREATE TABLE IF NOT EXISTS attendance_exceptions (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            period_id INTEGER NULL REFERENCES performance_periods(id) ON DELETE SET NULL,
            record_date DATE NOT NULL,
            exception_type VARCHAR(50) NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'onayli',
            day_fraction DOUBLE PRECISION NOT NULL DEFAULT 1,
            blocks_performance_evaluation BOOLEAN NOT NULL DEFAULT TRUE,
            performance_mode VARCHAR(20) NOT NULL DEFAULT 'partial',
            blocks_manager_duties BOOLEAN NOT NULL DEFAULT TRUE,
            description TEXT NULL,
            approved_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS user_id INTEGER",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS period_id INTEGER NULL",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS record_date DATE NOT NULL DEFAULT CURRENT_DATE",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS exception_type VARCHAR(50) NOT NULL DEFAULT 'devamsizlik'",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'onayli'",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS day_fraction DOUBLE PRECISION NOT NULL DEFAULT 1",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS blocks_performance_evaluation BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS performance_mode VARCHAR(20) NOT NULL DEFAULT 'partial'",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS blocks_manager_duties BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS description TEXT NULL",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS approved_by_id INTEGER NULL",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP NULL",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE attendance_exceptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_attendance_exceptions_user_id ON attendance_exceptions (user_id)",
            "CREATE INDEX IF NOT EXISTS ix_attendance_exceptions_period_id ON attendance_exceptions (period_id)",
            "CREATE INDEX IF NOT EXISTS ix_attendance_exceptions_record_date ON attendance_exceptions (record_date)",
            "CREATE INDEX IF NOT EXISTS ix_attendance_exceptions_exception_type ON attendance_exceptions (exception_type)",
            "CREATE INDEX IF NOT EXISTS ix_attendance_exceptions_status ON attendance_exceptions (status)",
            "CREATE INDEX IF NOT EXISTS ix_attendance_exceptions_performance_mode ON attendance_exceptions (performance_mode)",
        ),
    ),
    TableRepair(
        table="delegation_assignments",
        create_sql="""
        CREATE TABLE IF NOT EXISTS delegation_assignments (
            id SERIAL PRIMARY KEY,
            delegator_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            delegate_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            source_leave_id INTEGER NULL REFERENCES personnel_leaves(id) ON DELETE SET NULL,
            source_attendance_id INTEGER NULL REFERENCES attendance_exceptions(id) ON DELETE SET NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'aktif',
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            scope_type VARCHAR(30) NOT NULL DEFAULT 'performance',
            applies_level_1 BOOLEAN NOT NULL DEFAULT TRUE,
            applies_level_2 BOOLEAN NOT NULL DEFAULT TRUE,
            applies_level_3 BOOLEAN NOT NULL DEFAULT TRUE,
            note TEXT NULL,
            approved_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            approved_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS delegator_user_id INTEGER",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS delegate_user_id INTEGER",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS source_leave_id INTEGER NULL",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS source_attendance_id INTEGER NULL",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'aktif'",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS start_date DATE NOT NULL DEFAULT CURRENT_DATE",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS end_date DATE NOT NULL DEFAULT CURRENT_DATE",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS scope_type VARCHAR(30) NOT NULL DEFAULT 'performance'",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS applies_level_1 BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS applies_level_2 BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS applies_level_3 BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS note TEXT NULL",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS approved_by_id INTEGER NULL",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP NULL",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE delegation_assignments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_delegator_user_id ON delegation_assignments (delegator_user_id)",
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_delegate_user_id ON delegation_assignments (delegate_user_id)",
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_source_leave_id ON delegation_assignments (source_leave_id)",
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_source_attendance_id ON delegation_assignments (source_attendance_id)",
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_status ON delegation_assignments (status)",
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_start_date ON delegation_assignments (start_date)",
            "CREATE INDEX IF NOT EXISTS ix_delegation_assignments_end_date ON delegation_assignments (end_date)",
        ),
    ),
    TableRepair(
        table="ai_request_logs",
        create_sql="""
        CREATE TABLE IF NOT EXISTS ai_request_logs (
            id SERIAL PRIMARY KEY,
            module_type VARCHAR(50) NOT NULL,
            feature_type VARCHAR(50) NOT NULL,
            target_table VARCHAR(100) NULL,
            target_id INTEGER NULL,
            user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            request_text TEXT NULL,
            response_text TEXT NULL,
            provider_name VARCHAR(100) NULL,
            model_name VARCHAR(100) NULL,
            prompt_version VARCHAR(50) NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'completed',
            latency_ms INTEGER NULL,
            token_in INTEGER NULL,
            token_out INTEGER NULL,
            was_masked BOOLEAN NOT NULL DEFAULT TRUE,
            was_user_visible BOOLEAN NOT NULL DEFAULT TRUE,
            error_message TEXT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS module_type VARCHAR(50) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS feature_type VARCHAR(50) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS target_table VARCHAR(100) NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS target_id INTEGER NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS user_id INTEGER NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS request_text TEXT NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS response_text TEXT NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS provider_name VARCHAR(100) NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS model_name VARCHAR(100) NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS prompt_version VARCHAR(50) NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'completed'",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS latency_ms INTEGER NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS token_in INTEGER NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS token_out INTEGER NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS was_masked BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS was_user_visible BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS error_message TEXT NULL",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE ai_request_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_module_type ON ai_request_logs (module_type)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_feature_type ON ai_request_logs (feature_type)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_status ON ai_request_logs (status)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_prompt_version ON ai_request_logs (prompt_version)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_user_id ON ai_request_logs (user_id)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_was_masked ON ai_request_logs (was_masked)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_was_user_visible ON ai_request_logs (was_user_visible)",
            "CREATE INDEX IF NOT EXISTS ix_ai_request_logs_module_target ON ai_request_logs (module_type, target_table, target_id)",
        ),
    ),
    TableRepair(
        table="ai_recommendations",
        create_sql="""
        CREATE TABLE IF NOT EXISTS ai_recommendations (
            id SERIAL PRIMARY KEY,
            module_type VARCHAR(50) NOT NULL,
            target_table VARCHAR(100) NOT NULL,
            target_id INTEGER NOT NULL,
            recommendation_type VARCHAR(50) NOT NULL,
            title VARCHAR(255) NOT NULL,
            body TEXT NULL,
            severity VARCHAR(20) NULL DEFAULT 'info',
            status VARCHAR(30) NOT NULL DEFAULT 'open',
            ai_request_log_id INTEGER NULL REFERENCES ai_request_logs(id) ON DELETE SET NULL,
            reviewed_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            reviewed_at TIMESTAMP NULL,
            created_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            updated_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS module_type VARCHAR(50) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS target_table VARCHAR(100) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS target_id INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS recommendation_type VARCHAR(50) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '-'",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS body TEXT NULL",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS severity VARCHAR(20) NULL DEFAULT 'info'",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'open'",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS ai_request_log_id INTEGER NULL",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS reviewed_by_user_id INTEGER NULL",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP NULL",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS created_by_id INTEGER NULL",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS updated_by_id INTEGER NULL",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE ai_recommendations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_module_type ON ai_recommendations (module_type)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_target_table ON ai_recommendations (target_table)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_target_id ON ai_recommendations (target_id)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_recommendation_type ON ai_recommendations (recommendation_type)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_severity ON ai_recommendations (severity)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_status ON ai_recommendations (status)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_ai_request_log_id ON ai_recommendations (ai_request_log_id)",
            "CREATE INDEX IF NOT EXISTS ix_ai_recommendations_target ON ai_recommendations (module_type, target_table, target_id)",
        ),
    ),
    TableRepair(
        table="ai_feedback_logs",
        create_sql="""
        CREATE TABLE IF NOT EXISTS ai_feedback_logs (
            id SERIAL PRIMARY KEY,
            ai_request_log_id INTEGER NOT NULL REFERENCES ai_request_logs(id) ON DELETE CASCADE,
            user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            feedback_type VARCHAR(30) NOT NULL,
            feedback_note TEXT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE ai_feedback_logs ADD COLUMN IF NOT EXISTS ai_request_log_id INTEGER",
            "ALTER TABLE ai_feedback_logs ADD COLUMN IF NOT EXISTS user_id INTEGER NULL",
            "ALTER TABLE ai_feedback_logs ADD COLUMN IF NOT EXISTS feedback_type VARCHAR(30) NOT NULL DEFAULT 'helpful'",
            "ALTER TABLE ai_feedback_logs ADD COLUMN IF NOT EXISTS feedback_note TEXT NULL",
            "ALTER TABLE ai_feedback_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE ai_feedback_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_ai_feedback_logs_ai_request_log_id ON ai_feedback_logs (ai_request_log_id)",
            "CREATE INDEX IF NOT EXISTS ix_ai_feedback_logs_user_id ON ai_feedback_logs (user_id)",
            "CREATE INDEX IF NOT EXISTS ix_ai_feedback_logs_feedback_type ON ai_feedback_logs (feedback_type)",
        ),
    ),
    TableRepair(
        table="ai_redaction_rules",
        create_sql="""
        CREATE TABLE IF NOT EXISTS ai_redaction_rules (
            id SERIAL PRIMARY KEY,
            module_type VARCHAR(50) NOT NULL,
            field_name VARCHAR(100) NOT NULL,
            redaction_type VARCHAR(50) NOT NULL,
            replacement_text VARCHAR(100) NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            updated_by_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_ai_redaction_rules_module_field UNIQUE (module_type, field_name)
        )
        """,
        column_sql=(
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS module_type VARCHAR(50) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS field_name VARCHAR(100) NOT NULL DEFAULT 'field'",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS redaction_type VARCHAR(50) NOT NULL DEFAULT 'mask'",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS replacement_text VARCHAR(100) NULL",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS created_by_id INTEGER NULL",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS updated_by_id INTEGER NULL",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE ai_redaction_rules ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_ai_redaction_rules_module_type ON ai_redaction_rules (module_type)",
            "CREATE INDEX IF NOT EXISTS ix_ai_redaction_rules_field_name ON ai_redaction_rules (field_name)",
            "CREATE INDEX IF NOT EXISTS ix_ai_redaction_rules_is_active ON ai_redaction_rules (is_active)",
        ),
    ),
    TableRepair(
        table="ai_summary_cache",
        create_sql="""
        CREATE TABLE IF NOT EXISTS ai_summary_cache (
            id SERIAL PRIMARY KEY,
            module_type VARCHAR(50) NOT NULL,
            target_table VARCHAR(100) NOT NULL,
            target_id INTEGER NOT NULL,
            summary_kind VARCHAR(50) NOT NULL,
            summary_text TEXT NOT NULL,
            source_hash VARCHAR(128) NULL,
            expires_at TIMESTAMP NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_ai_summary_cache_target_kind UNIQUE (module_type, target_table, target_id, summary_kind)
        )
        """,
        column_sql=(
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS module_type VARCHAR(50) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS target_table VARCHAR(100) NOT NULL DEFAULT 'general'",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS target_id INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS summary_kind VARCHAR(50) NOT NULL DEFAULT 'summary'",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS summary_text TEXT NOT NULL DEFAULT '-'",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS source_hash VARCHAR(128) NULL",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP NULL",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE ai_summary_cache ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_ai_summary_cache_module_type ON ai_summary_cache (module_type)",
            "CREATE INDEX IF NOT EXISTS ix_ai_summary_cache_target_table ON ai_summary_cache (target_table)",
            "CREATE INDEX IF NOT EXISTS ix_ai_summary_cache_target_id ON ai_summary_cache (target_id)",
            "CREATE INDEX IF NOT EXISTS ix_ai_summary_cache_summary_kind ON ai_summary_cache (summary_kind)",
            "CREATE INDEX IF NOT EXISTS ix_ai_summary_cache_source_hash ON ai_summary_cache (source_hash)",
            "CREATE INDEX IF NOT EXISTS ix_ai_summary_cache_expires_at ON ai_summary_cache (expires_at)",
        ),
    ),
    TableRepair(
        table="assignment_coverage_logs",
        create_sql="""
        CREATE TABLE IF NOT EXISTS assignment_coverage_logs (
            id SERIAL PRIMARY KEY,
            period_id INTEGER NOT NULL REFERENCES performance_periods(id) ON DELETE CASCADE,
            employee_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            manager_level INTEGER NULL,
            event_scope VARCHAR(30) NOT NULL DEFAULT 'generation',
            event_type VARCHAR(30) NOT NULL,
            severity VARCHAR(20) NOT NULL DEFAULT 'warning',
            reason VARCHAR(255) NULL,
            run_key VARCHAR(40) NULL,
            original_evaluator_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            acting_evaluator_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            delegation_id INTEGER NULL REFERENCES delegation_assignments(id) ON DELETE SET NULL,
            created_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        )
        """,
        column_sql=(
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS period_id INTEGER",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS employee_id INTEGER",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS manager_level INTEGER NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS event_scope VARCHAR(30) NOT NULL DEFAULT 'generation'",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS event_type VARCHAR(30) NOT NULL DEFAULT 'info'",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS severity VARCHAR(20) NOT NULL DEFAULT 'warning'",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS reason VARCHAR(255) NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS run_key VARCHAR(40) NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS original_evaluator_id INTEGER NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS acting_evaluator_id INTEGER NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS delegation_id INTEGER NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER NULL",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE assignment_coverage_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
        ),
        index_sql=(
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_period_id ON assignment_coverage_logs (period_id)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_employee_id ON assignment_coverage_logs (employee_id)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_manager_level ON assignment_coverage_logs (manager_level)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_event_scope ON assignment_coverage_logs (event_scope)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_event_type ON assignment_coverage_logs (event_type)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_severity ON assignment_coverage_logs (severity)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_run_key ON assignment_coverage_logs (run_key)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_original_evaluator_id ON assignment_coverage_logs (original_evaluator_id)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_acting_evaluator_id ON assignment_coverage_logs (acting_evaluator_id)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_delegation_id ON assignment_coverage_logs (delegation_id)",
            "CREATE INDEX IF NOT EXISTS ix_assignment_coverage_logs_created_by_user_id ON assignment_coverage_logs (created_by_user_id)",
        ),
    ),
)

