
"""initial clean setup

Revision ID: fae32fb68b1b
Revises:
Create Date: 2026-...

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae32fb68b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_request_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_start', sa.Time(), nullable=False),
    sa.Column('meeting_end', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_request_id'], ['feedback_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_request_id')
    )
    op.create_table('feedback_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('level_1_manager_id', sa.Integer(), nullable=True),
    sa.Column('level_2_manager_id', sa.Integer(), nullable=True),
    sa.Column('level_3_manager_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_by_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_meeting_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['performance_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_1_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_2_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_3_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['performance_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_meeting_id'], ['feedback_meetings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_meeting_id')
    )
    with op.batch_alter_table('feedback_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_requests_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_requests_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_requests_status'), ['status'], unique=False)

    op.create_table('organization_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_units_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_units_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_units_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_units_unit_type'), ['unit_type'], unique=False)

    op.create_table('performance_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_criteria_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_criteria_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_performance_criteria_sort_order'), ['sort_order'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sicil_no', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ad', sa.String(length=120), nullable=False),
    sa.Column('soyad', sa.String(length=120), nullable=False),
    sa.Column('full_name_cache', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_path', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_updated_at', sa.DateTime(), nullable=True),
    sa.Column('unvan', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('birim', sa.String(length=255), nullable=True),
    sa.Column('ust_birim', sa.String(length=255), nullable=True),
    sa.Column('yonetici_sicil', sa.String(length=50), nullable=True),
    sa.Column('ikinci_yonetici_sicil', sa.String(length=50), nullable=True),
    sa.Column('ucuncu_yonetici_sicil', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('captcha_required', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('must_set_security_question', sa.Boolean(), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer_hash', sa.String(length=255), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_birim'), ['birim'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_full_name_cache'), ['full_name_cache'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ikinci_yonetici_sicil'), ['ikinci_yonetici_sicil'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_unit_id'), ['organization_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_sicil_no'), ['sicil_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_ucuncu_yonetici_sicil'), ['ucuncu_yonetici_sicil'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ust_birim'), ['ust_birim'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_yonetici_sicil'), ['yonetici_sicil'], unique=False)

    op.create_table('performance_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('results_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('allow_feedback_requests', sa.Boolean(), nullable=False),
    sa.Column('feedback_request_deadline', sa.Date(), nullable=True),
    sa.Column('enable_level_3', sa.Boolean(), nullable=False),
    sa.Column('enable_level_3_scoring', sa.Boolean(), nullable=False),
    sa.Column('require_level_3_completion_for_final', sa.Boolean(), nullable=False),
    sa.Column('level_1_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('level_2_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('level_3_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_periods_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_periods_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_periods_period_type'), ['period_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_periods_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_periods_title'), ['title'], unique=False)

    op.create_table('user_menu_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_key', sa.String(length=100), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'menu_key', name='uq_user_menu_permission_user_menu')
    )
    with op.batch_alter_table('user_menu_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_menu_permissions_menu_key'), ['menu_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_menu_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('evaluation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('manager_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['performance_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'employee_id', 'evaluator_id', 'manager_level', name='uq_period_employee_evaluator_level_assignment')
    )
    with op.batch_alter_table('evaluation_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_evaluator_id'), ['evaluator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_manager_level'), ['manager_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_status'), ['status'], unique=False)

    op.create_table('mail_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_type', sa.String(length=50), nullable=False),
    sa.Column('related_period_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_feedback_request_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['related_feedback_request_id'], ['feedback_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_period_id'], ['performance_periods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_logs_mail_type'), ['mail_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_logs_recipient_email'), ['recipient_email'], unique=False)

    op.create_table('performance_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('level_1_evaluator_id', sa.Integer(), nullable=True),
    sa.Column('level_2_evaluator_id', sa.Integer(), nullable=True),
    sa.Column('level_3_evaluator_id', sa.Integer(), nullable=True),
    sa.Column('level_1_total_100', sa.Float(), nullable=False),
    sa.Column('level_2_total_100', sa.Float(), nullable=False),
    sa.Column('level_3_total_100', sa.Float(), nullable=False),
    sa.Column('final_total_100', sa.Float(), nullable=False),
    sa.Column('level_1_general_comment', sa.Text(), nullable=True),
    sa.Column('level_2_general_comment', sa.Text(), nullable=True),
    sa.Column('level_3_general_comment', sa.Text(), nullable=True),
    sa.Column('level_1_completed', sa.Boolean(), nullable=False),
    sa.Column('level_2_completed', sa.Boolean(), nullable=False),
    sa.Column('level_3_completed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_published_to_employee', sa.Boolean(), nullable=False),
    sa.Column('published_to_employee_at', sa.DateTime(), nullable=True),
    sa.Column('published_to_employee_by_id', sa.Integer(), nullable=True),
    sa.Column('feedback_request_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_1_evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_2_evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_3_evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['performance_periods.id'], ),
    sa.ForeignKeyConstraint(['published_to_employee_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'employee_id', name='uq_period_employee_evaluation')
    )
    with op.batch_alter_table('performance_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_evaluations_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluations_level_1_evaluator_id'), ['level_1_evaluator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluations_level_2_evaluator_id'), ['level_2_evaluator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluations_level_3_evaluator_id'), ['level_3_evaluator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluations_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluations_status'), ['status'], unique=False)

    op.create_table('performance_weight_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('evaluator_1_weight', sa.Float(), nullable=False),
    sa.Column('evaluator_2_weight', sa.Float(), nullable=False),
    sa.Column('evaluator_3_weight', sa.Float(), nullable=False),
    sa.Column('level_3_enabled', sa.Boolean(), nullable=False),
    sa.Column('level_3_mode', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['performance_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_weight_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_weight_configs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_weight_configs_period_id'), ['period_id'], unique=False)

    op.create_table('evaluation_publish_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('acted_by_id', sa.Integer(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['performance_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['performance_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_publish_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_publish_logs_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_publish_logs_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_publish_logs_period_id'), ['period_id'], unique=False)

    op.create_table('performance_evaluation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('manager_level', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_100', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('strength_note', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['performance_criteria.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['performance_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'criteria_id', 'manager_level', name='uq_eval_criteria_level_item')
    )
    with op.batch_alter_table('performance_evaluation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_evaluation_items_criteria_id'), ['criteria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluation_items_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_evaluation_items_manager_level'), ['manager_level'], unique=False)

    op.create_table('performance_publish_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['performance_evaluations.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['performance_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_publish_logs')
    with op.batch_alter_table('performance_evaluation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_evaluation_items_manager_level'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluation_items_evaluation_id'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluation_items_criteria_id'))

    op.drop_table('performance_evaluation_items')
    with op.batch_alter_table('evaluation_publish_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_publish_logs_period_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_publish_logs_evaluation_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_publish_logs_employee_id'))

    op.drop_table('evaluation_publish_logs')
    with op.batch_alter_table('performance_weight_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_weight_configs_period_id'))
        batch_op.drop_index(batch_op.f('ix_performance_weight_configs_is_active'))

    op.drop_table('performance_weight_configs')
    with op.batch_alter_table('performance_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_evaluations_status'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluations_period_id'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluations_level_3_evaluator_id'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluations_level_2_evaluator_id'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluations_level_1_evaluator_id'))
        batch_op.drop_index(batch_op.f('ix_performance_evaluations_employee_id'))

    op.drop_table('performance_evaluations')
    with op.batch_alter_table('mail_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_logs_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_mail_logs_mail_type'))

    op.drop_table('mail_logs')
    with op.batch_alter_table('evaluation_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_period_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_manager_level'))
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_evaluator_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_employee_id'))

    op.drop_table('evaluation_assignments')
    with op.batch_alter_table('user_menu_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_menu_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_menu_permissions_menu_key'))

    op.drop_table('user_menu_permissions')
    with op.batch_alter_table('performance_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_periods_title'))
        batch_op.drop_index(batch_op.f('ix_performance_periods_start_date'))
        batch_op.drop_index(batch_op.f('ix_performance_periods_period_type'))
        batch_op.drop_index(batch_op.f('ix_performance_periods_is_active'))
        batch_op.drop_index(batch_op.f('ix_performance_periods_end_date'))

    op.drop_table('performance_periods')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_yonetici_sicil'))
        batch_op.drop_index(batch_op.f('ix_users_ust_birim'))
        batch_op.drop_index(batch_op.f('ix_users_ucuncu_yonetici_sicil'))
        batch_op.drop_index(batch_op.f('ix_users_sicil_no'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_organization_unit_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_ikinci_yonetici_sicil'))
        batch_op.drop_index(batch_op.f('ix_users_full_name_cache'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_birim'))

    op.drop_table('users')
    with op.batch_alter_table('performance_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_criteria_sort_order'))
        batch_op.drop_index(batch_op.f('ix_performance_criteria_name'))
        batch_op.drop_index(batch_op.f('ix_performance_criteria_is_active'))

    op.drop_table('performance_criteria')
    with op.batch_alter_table('organization_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_units_unit_type'))
        batch_op.drop_index(batch_op.f('ix_organization_units_parent_id'))
        batch_op.drop_index(batch_op.f('ix_organization_units_name'))
        batch_op.drop_index(batch_op.f('ix_organization_units_is_active'))

    op.drop_table('organization_units')
    with op.batch_alter_table('feedback_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_requests_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_requests_period_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_requests_evaluation_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_requests_employee_id'))

    op.drop_table('feedback_requests')
    op.drop_table('feedback_meetings')
    # ### end Alembic commands ###
