"""AI dashboard panel public facade.

This module keeps the legacy import path stable while the actual panel
builders live in focused dashboard_panel_* modules.
"""
from __future__ import annotations

from app.services.ai.dashboard_panel_communication import (
    build_announcement_form_ai_panel,
    build_announcements_ai_panel,
    build_message_compose_ai_panel,
    build_message_inbox_ai_panel,
    build_message_thread_ai_panel,
    build_notification_priority_ai_panel,
    build_portal_analytics_ai_panel,
    build_portal_announcement_center_ai_panel,
    build_portal_announcement_receipts_ai_panel,
    build_portal_feed_ai_panel,
    build_portal_file_share_ai_panel,
    build_portal_group_detail_ai_panel,
    build_portal_groups_ai_panel,
    build_portal_hashtag_ai_panel,
    build_portal_moderation_ai_panel,
    build_portal_notifications_ai_panel,
    build_portal_post_detail_ai_panel,
    build_portal_search_ai_panel,
)
from app.services.ai.dashboard_panel_hr import build_hr_attendance_ai_panel, build_hr_leave_ai_panel
from app.services.ai.dashboard_panel_operations import (
    DASHBOARD_AI_MODULE_META,
    build_dashboard_ai_operations_bridge,
)
from app.services.ai.dashboard_panel_performance import (
    build_dashboard_ai_panel,
    build_feedback_meetings_ai_panel,
    build_feedback_requests_ai_panel,
    build_feedback_schedule_ai_panel,
    build_hierarchy_ai_panel,
    build_mail_reminder_ai_panel,
    build_management_ai_panel,
    build_period_form_ai_panel,
    build_periods_ai_panel,
    build_portal_admin_ai_panel,
    build_portal_digest_ai_panel,
    build_publish_ai_panel,
    build_scorecard_ai_panel,
    build_task_generation_ai_panel,
    build_task_preflight_ai_panel,
)
from app.services.ai.dashboard_panel_personnel import (
    build_admin_user_form_ai_panel,
    build_admin_users_risk_ai_panel,
    build_assignment_delegation_pressure_ai_panel,
    build_assignment_recommendation_center_ai_panel,
    build_excel_fix_preview_ai_panel,
    build_hierarchy_assignment_person_ai_panel,
    build_hierarchy_bulk_edit_ai_panel,
    build_hierarchy_tree_ai_panel,
    build_import_health_priority_ai_panel,
    build_import_health_simulation_ai_panel,
    build_org_unit_detail_ai_panel,
    build_org_units_risk_map_ai_panel,
    build_personnel_density_ai_panel,
    build_personnel_list_ai_panel,
    build_personnel_profile_chain_ai_panel,
)
from app.services.ai.dashboard_panel_repository import build_repository_dashboard_ai_panel

__all__ = [
    "DASHBOARD_AI_MODULE_META",
    "build_repository_dashboard_ai_panel",
    "build_dashboard_ai_panel",
    "build_management_ai_panel",
    "build_scorecard_ai_panel",
    "build_publish_ai_panel",
    "build_periods_ai_panel",
    "build_period_form_ai_panel",
    "build_task_generation_ai_panel",
    "build_task_preflight_ai_panel",
    "build_hierarchy_ai_panel",
    "build_mail_reminder_ai_panel",
    "build_feedback_requests_ai_panel",
    "build_feedback_schedule_ai_panel",
    "build_feedback_meetings_ai_panel",
    "build_portal_admin_ai_panel",
    "build_portal_digest_ai_panel",
    "build_personnel_profile_chain_ai_panel",
    "build_admin_user_form_ai_panel",
    "build_excel_fix_preview_ai_panel",
    "build_personnel_list_ai_panel",
    "build_admin_users_risk_ai_panel",
    "build_import_health_priority_ai_panel",
    "build_org_unit_detail_ai_panel",
    "build_personnel_density_ai_panel",
    "build_import_health_simulation_ai_panel",
    "build_hierarchy_tree_ai_panel",
    "build_hierarchy_bulk_edit_ai_panel",
    "build_hierarchy_assignment_person_ai_panel",
    "build_org_units_risk_map_ai_panel",
    "build_assignment_recommendation_center_ai_panel",
    "build_assignment_delegation_pressure_ai_panel",
    "build_hr_leave_ai_panel",
    "build_hr_attendance_ai_panel",
    "build_message_compose_ai_panel",
    "build_message_inbox_ai_panel",
    "build_message_thread_ai_panel",
    "build_notification_priority_ai_panel",
    "build_announcements_ai_panel",
    "build_announcement_form_ai_panel",
    "build_portal_feed_ai_panel",
    "build_portal_notifications_ai_panel",
    "build_portal_search_ai_panel",
    "build_portal_hashtag_ai_panel",
    "build_portal_groups_ai_panel",
    "build_portal_group_detail_ai_panel",
    "build_portal_post_detail_ai_panel",
    "build_portal_file_share_ai_panel",
    "build_portal_analytics_ai_panel",
    "build_portal_moderation_ai_panel",
    "build_portal_announcement_center_ai_panel",
    "build_portal_announcement_receipts_ai_panel",
    "build_dashboard_ai_operations_bridge",
]
