
"""Public facade for the staged Corporate Information Center split.

Use this module for new internal calls while old imports continue to work.
"""
from __future__ import annotations


# BYS360 P17A FACADE EXPORT BRIDGE BEGIN
from .task_contract import BASE_KEY, TASK_DEFINITIONS
# BYS360 P17A FACADE EXPORT BRIDGE END

from .repository import _cic_auto_bool, _cic_auto_last_run_key, _cic_is_weekend, _cic_phase3_actor_label, _cic_phase3_last_result, _cic_phase3_make_result, _cic_phase3_public_error, _cic_phase3_store_result, _cic_phase5_actor, _cic_phase5_audit_list, _cic_phase5_last_result, _cic_phase5_log_metrics, _cic_phase5_now_label, _cic_phase5_readiness, _cic_phase5_safe_int, _cic_phase5_store_audit, _cic_phase6_bool, _cic_phase6_build, _cic_phase6_item, _cic_phase6_log_quality, _cic_phase6_status, _cic_v11_bool, _cic_v11_clean_header, _cic_v40_bool, _cic_v40_create_system_notifications, _cic_v40_date_input, _cic_v40_days_until, _cic_v40_mmdd, _cic_v40_parse_date, _cic_v40_setting_bool, _cic_v40_special_days, _cic_v40_special_days_today, _cic_v40_today, _cic_v40_upcoming_special_days, _cic_v40_user_date, _cic_v45_bool, _cic_v45_build_user_indexes, _cic_v45_ensure_schema, _cic_v45_existing_user_rows, _cic_v45_header_key, _cic_v45_norm, _cic_v45_norm_name, _cic_v45_parse_date, _cic_v45_text, _cic_weekday_name_tr, _clean_ids, _clothing, _dashboard_counts, _dumps_json, _has_settings_table, _loads_json, _now, _tomorrow_note, _user_name, can_manage, context, get_recent_logs  # noqa: F401
from .query_service import _active_staff_users, _cic_v40_active_staff_candidates, _cic_v40_special_day_users, _cic_v40_upcoming_users, _users_by_ids, list_users  # noqa: F401
from .template_service import _cic_phase6_template_quality, _render_template_text, get_template, save_templates  # noqa: F401
from .mail_scheduler_service import _cic_phase3_task_label, _cic_phase5_mail_health, _cic_phase5_task_preview, _cic_phase6_missing_email_count, _cic_v11_get_setting_value, _cic_v11_mail_settings, _cic_v11_normalize_email, _cic_v11_send_email_direct, _format_weather, _recipients_for_task, _weather, ensure_defaults, get_auto_scheduler_config, get_config, get_recipients, get_setting, run_due_tasks, save_recipients, save_system, save_tasks, send_task, set_auto_scheduler_config, set_setting  # noqa: F401
from .celebration_service import _cic_v40_anniversary_users, _cic_v40_birthday_users, _cic_v40_run_weekend_celebrations, _cic_v40_service_year, celebration_context, ensure_celebration_schema, import_celebration_dates_from_excel, save_celebration_settings  # noqa: F401

__all__ = [
    "BASE_KEY",
    "TASK_DEFINITIONS",
    "_active_staff_users",
    "_cic_auto_bool",
    "_cic_auto_last_run_key",
    "_cic_is_weekend",
    "_cic_phase3_actor_label",
    "_cic_phase3_last_result",
    "_cic_phase3_make_result",
    "_cic_phase3_public_error",
    "_cic_phase3_store_result",
    "_cic_phase3_task_label",
    "_cic_phase5_actor",
    "_cic_phase5_audit_list",
    "_cic_phase5_last_result",
    "_cic_phase5_log_metrics",
    "_cic_phase5_mail_health",
    "_cic_phase5_now_label",
    "_cic_phase5_readiness",
    "_cic_phase5_safe_int",
    "_cic_phase5_store_audit",
    "_cic_phase5_task_preview",
    "_cic_phase6_bool",
    "_cic_phase6_build",
    "_cic_phase6_item",
    "_cic_phase6_log_quality",
    "_cic_phase6_missing_email_count",
    "_cic_phase6_status",
    "_cic_phase6_template_quality",
    "_cic_v11_bool",
    "_cic_v11_clean_header",
    "_cic_v11_get_setting_value",
    "_cic_v11_mail_settings",
    "_cic_v11_normalize_email",
    "_cic_v11_send_email_direct",
    "_cic_v40_active_staff_candidates",
    "_cic_v40_anniversary_users",
    "_cic_v40_birthday_users",
    "_cic_v40_bool",
    "_cic_v40_create_system_notifications",
    "_cic_v40_date_input",
    "_cic_v40_days_until",
    "_cic_v40_mmdd",
    "_cic_v40_parse_date",
    "_cic_v40_run_weekend_celebrations",
    "_cic_v40_service_year",
    "_cic_v40_setting_bool",
    "_cic_v40_special_day_users",
    "_cic_v40_special_days",
    "_cic_v40_special_days_today",
    "_cic_v40_today",
    "_cic_v40_upcoming_special_days",
    "_cic_v40_upcoming_users",
    "_cic_v40_user_date",
    "_cic_v45_bool",
    "_cic_v45_build_user_indexes",
    "_cic_v45_ensure_schema",
    "_cic_v45_existing_user_rows",
    "_cic_v45_header_key",
    "_cic_v45_norm",
    "_cic_v45_norm_name",
    "_cic_v45_parse_date",
    "_cic_v45_text",
    "_cic_weekday_name_tr",
    "_clean_ids",
    "_clothing",
    "_dashboard_counts",
    "_dumps_json",
    "_format_weather",
    "_has_settings_table",
    "_loads_json",
    "_now",
    "_recipients_for_task",
    "_render_template_text",
    "_tomorrow_note",
    "_user_name",
    "_users_by_ids",
    "_weather",
    "can_manage",
    "celebration_context",
    "context",
    "ensure_celebration_schema",
    "ensure_defaults",
    "get_auto_scheduler_config",
    "get_config",
    "get_recent_logs",
    "get_recipients",
    "get_setting",
    "get_template",
    "import_celebration_dates_from_excel",
    "list_users",
    "run_due_tasks",
    "save_celebration_settings",
    "save_recipients",
    "save_system",
    "save_tasks",
    "save_templates",
    "send_task",
    "set_auto_scheduler_config",
    "set_setting",
]
