"""Misc/context helpers split from app.services.corporate_information_center.

Generated by Phase4J V27C. Kept API-compatible through facade imports.
"""

from __future__ import annotations
from typing import Any
from app.services.cic.config_context import (
    _has_settings_table,
    _loads_json,
    ensure_defaults,
    get_config,
    get_setting,
)
from app.services.cic.query_service import list_users
import app.services.cic.template_service as _template_service
from app.services.cic.mail_service import (
    _cic_phase5_mail_health,
    _cic_phase6_missing_email_count,
    get_recipients,
)


BASE_KEY = "corporate_information_center"

TASK_DEFINITIONS: dict[str, dict[str, Any]] = {
    "staff_morning": {
        "category": "personel",
        "label": "Personel Sabah Bilgilendirmesi",
        "short_label": "Sabah Personel",
        "default_hour": 8,
        "default_minute": 0,
        "icon": "fa-sun",
        "description": "Günaydın mesajı, bugünkü hava durumu, kıyafet önerisi ve iyi dilek.",
        "recipient_group": "staff",
        "subject": "Günaydın | BYS360 Günlük Bilgilendirme",
        "body": """Sayın {ad_soyad},

Günaydın.

Bugün {konum} için hava durumu özeti:
{bugun_hava}

Kıyafet önerisi:
{kiyafet_onerisi}

Başarılı, verimli ve güzel bir gün geçirmenizi dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    # BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE6_1_STAFF_NOON_MESSAGE
    "staff_noon": {
        "category": "personel",
        "label": "Personel Öğlen Bilgilendirmesi",
        "short_label": "Öğlen Personel",
        "default_hour": 12,
        "default_minute": 30,
        "icon": "fa-mug-hot",
        "description": "Gün ortası iyi dilek, mesai kontrolü ve geri bildirim hatırlatması.",
        "recipient_group": "staff",
        "subject": "BYS360 Gün Ortası Destek Hatırlatması",
        "body": """Sayın {ad_soyad},

Gününüz nasıl geçiyor?

Sistemde destek ihtiyacı duyduğunuz bir konu var mı?

BYS360 kullanımı sırasında destek, öneri, hata bildirimi veya geliştirme ihtiyacı oluşursa Geri Bildirim Merkezi üzerinden bize iletebilirsiniz.

Geri bildirim bağlantısı:
{geri_bildirim_baglantisi}

İyi çalışmalar dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    "staff_evening": {
        "category": "personel",
        "label": "Personel Akşam Bilgilendirmesi",
        "short_label": "Akşam Personel",
        "default_hour": 17,
        "default_minute": 30,
        "icon": "fa-cloud-moon",
        "description": "İyi akşamlar mesajı, yarın hava durumu ve ertesi gün hazırlık notu.",
        "recipient_group": "staff",
        "subject": "İyi Akşamlar | BYS360 Yarın İçin Bilgilendirme",
        "body": """Sayın {ad_soyad},

İyi akşamlar.

Yarın {konum} için beklenen hava durumu:
{yarin_hava}

Yarın için öneri:
{yarin_oneri}

Bugünkü emekleriniz için teşekkür eder, güzel bir akşam dileriz.

BYS360""",
    },
    "manager_morning": {
        "category": "yonetici",
        "label": "Yönetici Sabah Özeti",
        "short_label": "Sabah Yönetici",
        "default_hour": 7,
        "default_minute": 45,
        "icon": "fa-chart-line",
        "description": "Yöneticiler için gün başlangıcı kısa kurum içi durum özeti.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Sabah Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün başlangıcı yönetici özeti aşağıdadır.

Tarih: {tarih}
Aktif personel sayısı: {aktif_personel_sayisi}
Son bilgilendirme durumu: {son_gonderim_durumu}
Bugün takip edilecek ana başlık: {gunun_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi çalışmalar dileriz.

BYS360""",
    },
    "manager_evening": {
        "category": "yonetici",
        "label": "Yönetici Akşam Özeti",
        "short_label": "Akşam Yönetici",
        "default_hour": 17,
        "default_minute": 45,
        "icon": "fa-clipboard-check",
        "description": "Yöneticiler için gün sonu kısa durum ve ertesi gün dikkat notu.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Akşam Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün sonu yönetici özeti aşağıdadır.

Tarih: {tarih}
Son gönderim durumu: {son_gonderim_durumu}
Yarın için dikkat notu: {yarin_yonetici_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi akşamlar dileriz.

BYS360""",
    },
}




def get_recent_logs(limit: int = 120) -> list[Any]:
    try:
        from app.models import MailLog
        return MailLog.query.filter(MailLog.mail_type.like("corporate_information_%")).order_by(MailLog.sent_at.desc(), MailLog.id.desc()).limit(limit).all()
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:818")
        return []

def _cic_phase5_safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value or 0)
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:868")
        return default

def _cic_phase5_last_result() -> dict[str, Any]:
    try:
        value = _loads_json(f"{BASE_KEY}.phase3.last_result", {})
        return value if isinstance(value, dict) else {}
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:892")
        return {}

def _cic_phase5_audit_list() -> list[dict[str, Any]]:
    try:
        value = _loads_json(f"{BASE_KEY}.phase5.audit", [])
        return value if isinstance(value, list) else []
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:900")
        return []

def _cic_phase5_log_metrics(logs: list[Any]) -> dict[str, Any]:
    total = len(logs or [])
    success = 0
    fail = 0
    dry_run = 0
    real_send = 0
    last_success_at = ""
    last_error = ""
    by_type: dict[str, dict[str, Any]] = {}
    for log in logs or []:
        ok = bool(getattr(log, "is_success", False))
        mail_type = str(getattr(log, "mail_type", "") or "bilinmeyen")
        is_dry = "dry_run" in mail_type
        if ok:
            success += 1
            if not last_success_at and getattr(log, "sent_at", None):
                try:
                    last_success_at = log.sent_at.strftime("%d.%m.%Y %H:%M")
                except Exception:
                    __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:966")
                    last_success_at = str(log.sent_at)
        else:
            fail += 1
            if not last_error:
                last_error = str(getattr(log, "error_message", "") or "Gönderim tamamlanamadı.")[:180]
        if is_dry:
            dry_run += 1
        else:
            real_send += 1
        row = by_type.setdefault(mail_type, {"mail_type": mail_type, "total": 0, "success": 0, "fail": 0, "dry_run": is_dry})
        row["total"] += 1
        if ok:
            row["success"] += 1
        else:
            row["fail"] += 1
    success_rate = round((success / total) * 100, 1) if total else 0
    grouped = sorted(by_type.values(), key=lambda x: x.get("total", 0), reverse=True)[:12]
    return {
        "total": total,
        "success": success,
        "fail": fail,
        "dry_run": dry_run,
        "real_send": real_send,
        "success_rate": success_rate,
        "last_success_at": last_success_at or "Henüz yok",
        "last_error": last_error or "Kayıtlı hata yok",
        "by_type": grouped,
    }

def _cic_phase5_readiness(*, cfg: dict[str, Any], tasks: list[dict[str, Any]], recipients: dict[str, Any], logs: list[Any]) -> dict[str, Any]:
    score = 0
    checks: list[dict[str, Any]] = []

    active_tasks = sum(1 for t in tasks if t.get("enabled"))
    manager_count = len(recipients.get("managers") or [])
    staff_count = len(recipients.get("staff") or [])
    mail = _cic_phase5_mail_health()
    last = _cic_phase5_last_result()

    def add(ok: bool, title: str, detail: str, weight: int) -> None:
        nonlocal score
        if ok:
            score += weight
        checks.append({"ok": bool(ok), "title": title, "detail": detail, "weight": weight})

    add(active_tasks > 0, "Görev planı", f"{active_tasks} aktif görev var." if active_tasks else "Aktif görev bulunmuyor.", 18)
    add(manager_count > 0, "Yönetici alıcıları", f"{manager_count} yönetici alıcısı seçili." if manager_count else "Yönetici alıcı listesi boş.", 16)
    add(staff_count > 0, "Personel alıcıları", f"{staff_count} personel alıcısı seçili." if staff_count else "Personel alıcı listesi boş.", 16)
    add(mail.get("status") == "ok", "Mail altyapısı", "Mail altyapısı hazır görünüyor." if mail.get("status") == "ok" else "; ".join(mail.get("problems") or ["Mail altyapısı kontrol edilmeli."]), 20)
    add(bool(last), "Kuru çalışma kaydı", "Son test/gönderim özeti var." if last else "Henüz kuru çalışma sonucu oluşmamış.", 16)
    add(len(logs) > 0, "Gönderim geçmişi", f"{len(logs)} log kaydı izleniyor." if logs else "Henüz log kaydı oluşmamış.", 14)

    if score >= 85:
        status = "ok"
        label = "Gönderime hazır"
    elif score >= 55:
        status = "warn"
        label = "Kontrol ederek ilerle"
    else:
        status = "danger"
        label = "Ön kontrol gerekli"
    return {"score": min(score, 100), "status": status, "label": label, "checks": checks}

def _cic_phase5_task_preview(tasks: list[dict[str, Any]], recipients: dict[str, Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    managers = recipients.get("managers") or []
    staff = recipients.get("staff") or []
    for task in tasks:
        group = task.get("recipient_group") or "staff"
        target_users = managers if group == "managers" else staff
        out.append({
            "key": task.get("key"),
            "label": task.get("label"),
            "enabled": bool(task.get("enabled")),
            "recipient_group": group,
            "recipient_count": len(target_users),
            "risk": "Yüksek" if len(target_users) >= 100 else ("Orta" if len(target_users) >= 25 else "Düşük"),
            "time": f"{_cic_phase5_safe_int(task.get('hour')):02d}:{_cic_phase5_safe_int(task.get('minute')):02d}",
            "subject": task.get("subject") or "",
        })
    return out

def _context_base(search: str | None = None) -> dict[str, Any]:
    ensure_defaults()
    cfg = get_config()
    rec = get_recipients()
    users = list_users(search=search, limit=1000)
    tasks: list[dict[str, Any]] = []
    for key, meta in TASK_DEFINITIONS.items():
        tcfg = cfg.get("tasks", {}).get(key, {})
        tmpl = _template_service.get_template(key)
        tasks.append({"key": key, **meta, **tcfg, "subject": tmpl.get("subject", ""), "body": tmpl.get("body", "")})
    try:
        logs = get_recent_logs(300)
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1101")
        logs = []
    phase3_last_result = _cic_phase5_last_result()
    metrics = _cic_phase5_log_metrics(logs)
    readiness = _cic_phase5_readiness(cfg=cfg, tasks=tasks, recipients=rec, logs=logs)
    phase5 = {
        "version": "BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE5_CONTROL_PANEL",
        "mail_health": _cic_phase5_mail_health(),
        "metrics": metrics,
        "readiness": readiness,
        "task_preview": _cic_phase5_task_preview(tasks, rec),
        "audit": _cic_phase5_audit_list()[:30],
        "last_dispatch": _loads_json(f"{BASE_KEY}.phase5.last_dispatch", {}) if _has_settings_table() else {},
    }
    return {
        "version": "BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE5_CONTROL_PANEL",
        "config": cfg,
        "tasks": tasks,
        "task_definitions": TASK_DEFINITIONS,
        "manager_recipients": rec.get("managers", []),
        "staff_recipients": rec.get("staff", []),
        "staff_mode": rec.get("staff_mode", "all"),
        "users": users,
        "search": search or "",
        "logs": logs,
        "location": cfg.get("location_name", "Çanakkale"),
        "phase3_last_result": phase3_last_result,
        "phase5": phase5,
        "stats": {
            "active_tasks": sum(1 for t in tasks if t.get("enabled")),
            "manager_count": len(rec.get("managers") or []),
            "staff_count": len(rec.get("staff") or []),
            "last_status": get_setting(f"{BASE_KEY}.last_status", "Henüz gönderim yapılmadı"),
            "last_phase3_status": phase3_last_result.get("message") or "Henüz gönderim testi yapılmadı.",
            "phase5_success_rate": metrics.get("success_rate", 0),
            "phase5_total_logs": metrics.get("total", 0),
            "phase5_fail_logs": metrics.get("fail", 0),
            "phase5_readiness_score": readiness.get("score", 0),
        },
    }



def _cic_phase6_log_quality(logs: list[Any], metrics: dict[str, Any]) -> dict[str, Any]:
    has_logs = len(logs or []) > 0
    has_dry = int(metrics.get("dry_run") or 0) > 0
    has_error_visibility = int(metrics.get("fail") or 0) >= 0
    items = [
        _template_service._cic_phase6_item("Log kaydı", has_logs, f"{len(logs or [])} kayıt izleniyor.", warn=True),
        _template_service._cic_phase6_item("Kuru çalışma izi", has_dry, "Kuru çalışma logu var." if has_dry else "Önce kuru çalışma yapın.", warn=True),
        _template_service._cic_phase6_item("Hata görünürlüğü", has_error_visibility, "Hatalı kayıtlar filtrelenebilir.", warn=True),
    ]
    return {"status": "ok" if has_logs and has_dry else "warn", "label": "İzlenebilir" if has_logs and has_dry else "Kayıt bekleniyor", "items": items}

def _cic_phase6_build(data: dict[str, Any]) -> dict[str, Any]:
    tasks = data.get("tasks") or []
    logs = data.get("logs") or []
    managers = data.get("manager_recipients") or []
    staff = data.get("staff_recipients") or []
    phase5 = data.get("phase5") or {}
    readiness = phase5.get("readiness") or {}
    metrics = phase5.get("metrics") or {}
    mail = phase5.get("mail_health") or {}
    last = data.get("phase3_last_result") or {}

    active_tasks = sum(1 for t in tasks if t.get("enabled"))
    missing_email = _cic_phase6_missing_email_count(managers) + _cic_phase6_missing_email_count(staff)
    has_templates = all((t.get("subject") or "").strip() and (t.get("body") or "").strip() for t in tasks if t.get("enabled")) if active_tasks else False
    has_csrf_safe = True
    try:
        # Runtime tarafında form CSRF kontrolü template gate ile de doğrulanıyor; contextte engel üretmeyelim.
        has_csrf_safe = True
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1227")
        has_csrf_safe = False

    scenarios = [
        _template_service._cic_phase6_item("Kuru çalışma testi", bool(last), "Son test/gönderim özeti oluşmuş." if last else "Test Merkezi’nde kuru çalışma yapılmalı.", warn=True),
        _template_service._cic_phase6_item("Gerçek gönderim uyarısı", True, "Gerçek gönderim öncesi onay uyarısı aktif."),
        _template_service._cic_phase6_item("E-postası olmayan personel", missing_email == 0, f"{missing_email} seçili alıcıda e-posta eksikliği var.", warn=True),
        _template_service._cic_phase6_item("Pasif personel kontrolü", True, "Alıcı listesi yetkili seçimle yönetiliyor."),
        _template_service._cic_phase6_item("Boş şablon kontrolü", has_templates, "Aktif görevlerde konu ve metin kontrol edildi." if has_templates else "Aktif görevlerde konu/metin kontrol edilmeli.", warn=True),
        _template_service._cic_phase6_item("Eksik konu kontrolü", _template_service._cic_phase6_template_quality(tasks).get("problem_count", 0) == 0, "Şablon kalite kontrolü tamam.", warn=True),
        _template_service._cic_phase6_item("Büyük alıcı grubu", True, "Alıcı sayısı ve risk seviyesi ön izleme panelinde gösteriliyor."),
        _template_service._cic_phase6_item("SMTP ayarı", mail.get("status") == "ok", "; ".join(mail.get("problems") or ["Mail altyapısı hazır."]), warn=True),
        _template_service._cic_phase6_item("Başarılı gönderim logu", int(metrics.get("success") or 0) > 0, "Başarılı log kaydı var." if int(metrics.get("success") or 0) > 0 else "Henüz başarılı log kaydı yok.", warn=True),
        _template_service._cic_phase6_item("Başarısız gönderim logu", True, "Hatalı kayıtlar log ekranında filtrelenebilir."),
    ]
    passed = sum(1 for s in scenarios if s.get("status") == "ok")
    warn_count = sum(1 for s in scenarios if s.get("status") == "warn")
    danger_count = sum(1 for s in scenarios if s.get("status") == "danger")
    score = round((passed / len(scenarios)) * 100) if scenarios else 0
    blockers: list[str] = []
    if mail.get("status") == "danger":
        blockers.append("Mail altyapısı gerçek gönderim için hazır değil.")
    if active_tasks <= 0:
        blockers.append("Aktif bilgilendirme görevi yok.")
    if not managers and not staff:
        blockers.append("Seçili alıcı grubu bulunmuyor.")
    if missing_email > 0:
        blockers.append(f"{missing_email} alıcıda e-posta eksikliği var.")

    if blockers:
        live_status = "danger" if mail.get("status") == "danger" or not managers and not staff else "warn"
        live_label = "Canlı öncesi kontrol gerekli"
        live_note = "Kritik uyarılar kapanmadan gerçek gönderim yapılmamalıdır. İlk gerçek deneme pilot alıcı grubu ile yapılmalıdır."
    elif score >= 85 and readiness.get("score", 0) >= 70:
        live_status = "ok"
        live_label = "Canlıya hazır"
        live_note = "Kritik engel görünmüyor. İlk gerçek gönderimi yine pilot grupla başlatıp logları kontrol edin."
    else:
        live_status = "warn"
        live_label = "Pilot test önerilir"
        live_note = "Temel yapı çalışıyor; canlı öncesi kuru çalışma ve log kontrolünü tekrarlayın."

    template_quality = _template_service._cic_phase6_template_quality(tasks)
    log_quality = _cic_phase6_log_quality(logs, metrics)
    final_send_checks = [
        _template_service._cic_phase6_item("Görev seçimi", active_tasks > 0, f"{active_tasks} aktif görev var.", warn=True),
        _template_service._cic_phase6_item("Alıcı sayısı", (len(managers) + len(staff)) > 0, f"{len(managers) + len(staff)} seçili alıcı var.", warn=True),
        _template_service._cic_phase6_item("Mail altyapısı", mail.get("status") == "ok", mail.get("label") or "Mail altyapısı kontrol edilmeli.", warn=True),
        _template_service._cic_phase6_item("Kuru çalışma", bool(last), "Son kuru çalışma/gönderim özeti var." if last else "Önce kuru çalışma yapın.", warn=True),
    ]
    top_checks = [
        _template_service._cic_phase6_item("CSRF formları", has_csrf_safe, "Form güvenlik token kontrolü aktif."),
        _template_service._cic_phase6_item("Alıcı özeti", (len(managers) + len(staff)) > 0, "Alıcı grupları tanımlı.", warn=True),
        _template_service._cic_phase6_item("Denetim izi", bool(phase5.get("audit")), "İşlem kayıtları izleniyor." if phase5.get("audit") else "İlk işlem sonrası denetim izi oluşacak.", warn=True),
    ]
    return {
        "version": "BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE6_FINAL_UAT_LIVE_READY",
        "scenarios": scenarios,
        "uat_score": score,
        "passed_count": passed,
        "warn_count": warn_count,
        "danger_count": danger_count,
        "total_count": len(scenarios),
        "blockers": blockers,
        "live": {"status": live_status, "label": live_label, "score": min(100, round((score + int(readiness.get("score") or 0)) / 2)), "note": live_note},
        "recipient_quality": {"managers": len(managers), "staff": len(staff), "missing_email": missing_email, "passive_hint": "Yetki kapsamına göre"},
        "template_quality": template_quality,
        "log_quality": log_quality,
        "final_send_checks": final_send_checks,
        "top_checks": top_checks,
    }

def _cic_auto_bool(value: object, default: bool = False) -> bool:
    if value is None:
        return default
    text = str(value).strip().lower()
    if text == "":
        return default
    return text in {"1", "true", "on", "yes", "aktif", "evet", "checked"}

def context(search: str | None = None) -> dict[str, Any]:
    from app.services.cic.scheduler_service import get_auto_scheduler_config

    """Build CIC management context through one explicit public layer.

    Flattened legacy wrapper chain:
    - Core Phase 5 control-panel context is produced by _context_base.
    - Phase 6 UAT/live readiness data is added explicitly.
    - Auto scheduler configuration is added once.
    """
    data = _context_base(search=search)

    phase6 = _cic_phase6_build(data)
    data["phase6"] = phase6

    stats = data.setdefault("stats", {})
    stats["phase6_uat_score"] = phase6.get("uat_score", 0)
    stats["phase6_live_score"] = (phase6.get("live") or {}).get("score", 0)
    stats["phase6_blocker_count"] = len(phase6.get("blockers") or [])

    data["auto_scheduler"] = get_auto_scheduler_config()
    data["version"] = "BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE6_FINAL_UAT_LIVE_READY"

    return data

__all__ = [
    "_cic_auto_bool",
    "_cic_phase5_audit_list",
    "_cic_phase5_last_result",
    "_cic_phase5_log_metrics",
    "_cic_phase5_mail_health",
    "_cic_phase5_readiness",
    "_cic_phase5_safe_int",
    "_cic_phase5_task_preview",
    "_cic_phase6_build",
    "_cic_phase6_log_quality",
    "_cic_phase6_missing_email_count",
    "_context_base",
    "context",
    "get_recent_logs",
    "get_recipients",
]
