
"""BYS360 CIC facade slice.

This module temporarily preserves the historical repository import surface.
Legacy forwarding wrappers are removed; every imported name resolves to its canonical owner.
Routes, template names, endpoint contracts and public function names are not changed.
"""
from __future__ import annotations

from app.services.cic.access_policy import can_manage
from app.services.cic.celebration_dates import (
    _cic_v40_bool,
    _cic_v40_days_until,
    _cic_v40_mmdd,
    _cic_v40_parse_date,
    _cic_v40_setting_bool,
    _cic_v40_special_days,
    _cic_v40_special_days_today,
    _cic_v40_today,
    _cic_v40_user_date,
)
from app.services.cic.cic_context import (
    _cic_auto_last_run_key,
    _cic_is_weekend,
    _cic_phase3_actor_label,
    _cic_phase3_last_result,
    _cic_phase3_make_result,
    _cic_phase3_public_error,
    _cic_phase3_store_result,
    _cic_phase5_actor,
    _cic_phase5_now_label,
    _cic_phase5_store_audit,
    _cic_phase6_bool,
    _cic_v40_create_system_notifications,
    _cic_v40_date_input,
    _cic_v40_upcoming_special_days,
    _cic_v45_bool,
    _cic_v45_build_user_indexes,
    _cic_v45_ensure_schema,
    _cic_v45_existing_user_rows,
    _cic_v45_header_key,
    _cic_v45_norm,
    _cic_v45_norm_name,
    _cic_v45_parse_date,
    _cic_v45_text,
    _cic_weekday_name_tr,
)
from app.services.cic.config_context import (
    _clean_ids,
    _clothing,
    _dumps_json,
    _has_settings_table,
    _loads_json,
    _now,
    _tomorrow_note,
    get_setting,  # noqa: F401 - historical repository compatibility attribute
)
from app.services.cic.mail_service import (
    _cic_v11_bool,
    _cic_v11_clean_header,
    _cic_v11_normalize_email,  # noqa: F401 - historical repository compatibility attribute
)
from app.services.cic.misc_context import (
    _cic_auto_bool,
    _cic_phase5_audit_list,
    _cic_phase5_last_result,
    _cic_phase5_log_metrics,
    _cic_phase5_readiness,
    _cic_phase5_safe_int,
    _cic_phase6_build,
    _cic_phase6_log_quality,
    context,
    get_recent_logs,
)

__all__ = [
    "_cic_auto_bool",
    "_cic_auto_last_run_key",
    "_cic_is_weekend",
    "_cic_phase3_actor_label",
    "_cic_phase3_last_result",
    "_cic_phase3_make_result",
    "_cic_phase3_public_error",
    "_cic_phase3_store_result",
    "_cic_phase5_actor",
    "_cic_phase5_audit_list",
    "_cic_phase5_last_result",
    "_cic_phase5_log_metrics",
    "_cic_phase5_now_label",
    "_cic_phase5_readiness",
    "_cic_phase5_safe_int",
    "_cic_phase5_store_audit",
    "_cic_phase6_bool",
    "_cic_phase6_build",
    "_cic_phase6_log_quality",
    "_cic_v11_bool",
    "_cic_v11_clean_header",
    "_cic_v40_bool",
    "_cic_v40_create_system_notifications",
    "_cic_v40_date_input",
    "_cic_v40_days_until",
    "_cic_v40_mmdd",
    "_cic_v40_parse_date",
    "_cic_v40_setting_bool",
    "_cic_v40_special_days",
    "_cic_v40_special_days_today",
    "_cic_v40_today",
    "_cic_v40_upcoming_special_days",
    "_cic_v40_user_date",
    "_cic_v45_bool",
    "_cic_v45_build_user_indexes",
    "_cic_v45_ensure_schema",
    "_cic_v45_existing_user_rows",
    "_cic_v45_header_key",
    "_cic_v45_norm",
    "_cic_v45_norm_name",
    "_cic_v45_parse_date",
    "_cic_v45_text",
    "_cic_weekday_name_tr",
    "_clean_ids",
    "_clothing",
    "_dumps_json",
    "_has_settings_table",
    "_loads_json",
    "_now",
    "_tomorrow_note",
    "can_manage",
    "context",
    "get_recent_logs",
]
