"""Run/scheduler helpers split from app.services.corporate_information_center.

Generated by Phase4J V31C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

from __future__ import annotations
from typing import Any
from app.extensions import db
from app.services.cic.config_context import (
    _now,
    ensure_defaults,
    get_config,
    get_setting,
    set_setting,
)
from app.services.cic.misc_context import (
    get_auto_scheduler_config,
)
from app.services.cic.cic_context import (
    _cic_auto_last_run_key,
    _cic_is_weekend,
    _cic_v40_run_weekend_celebrations,
    _cic_weekday_name_tr,
    send_task,
)
from datetime import datetime as _cic_dt_datetime
from typing import Any as _cic_typing_any
from datetime import date as _cic_v40_date, datetime as _cic_v40_datetime
from typing import Any as _cic_v40_Any

TASK_DEFINITIONS: dict[str, dict[str, Any]] = {
    "staff_morning": {
        "category": "personel",
        "label": "Personel Sabah Bilgilendirmesi",
        "short_label": "Sabah Personel",
        "default_hour": 8,
        "default_minute": 0,
        "icon": "fa-sun",
        "description": "Günaydın mesajı, bugünkü hava durumu, kıyafet önerisi ve iyi dilek.",
        "recipient_group": "staff",
        "subject": "Günaydın | BYS360 Günlük Bilgilendirme",
        "body": """Sayın {ad_soyad},

Günaydın.

Bugün {konum} için hava durumu özeti:
{bugun_hava}

Kıyafet önerisi:
{kiyafet_onerisi}

Başarılı, verimli ve güzel bir gün geçirmenizi dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    # BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE6_1_STAFF_NOON_MESSAGE
    "staff_noon": {
        "category": "personel",
        "label": "Personel Öğlen Bilgilendirmesi",
        "short_label": "Öğlen Personel",
        "default_hour": 12,
        "default_minute": 30,
        "icon": "fa-mug-hot",
        "description": "Gün ortası iyi dilek, mesai kontrolü ve geri bildirim hatırlatması.",
        "recipient_group": "staff",
        "subject": "BYS360 Gün Ortası Destek Hatırlatması",
        "body": """Sayın {ad_soyad},

Gününüz nasıl geçiyor?

Sistemde destek ihtiyacı duyduğunuz bir konu var mı?

BYS360 kullanımı sırasında destek, öneri, hata bildirimi veya geliştirme ihtiyacı oluşursa Geri Bildirim Merkezi üzerinden bize iletebilirsiniz.

Geri bildirim bağlantısı:
{geri_bildirim_baglantisi}

İyi çalışmalar dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    "staff_evening": {
        "category": "personel",
        "label": "Personel Akşam Bilgilendirmesi",
        "short_label": "Akşam Personel",
        "default_hour": 17,
        "default_minute": 30,
        "icon": "fa-cloud-moon",
        "description": "İyi akşamlar mesajı, yarın hava durumu ve ertesi gün hazırlık notu.",
        "recipient_group": "staff",
        "subject": "İyi Akşamlar | BYS360 Yarın İçin Bilgilendirme",
        "body": """Sayın {ad_soyad},

İyi akşamlar.

Yarın {konum} için beklenen hava durumu:
{yarin_hava}

Yarın için öneri:
{yarin_oneri}

Bugünkü emekleriniz için teşekkür eder, güzel bir akşam dileriz.

BYS360""",
    },
    "manager_morning": {
        "category": "yonetici",
        "label": "Yönetici Sabah Özeti",
        "short_label": "Sabah Yönetici",
        "default_hour": 7,
        "default_minute": 45,
        "icon": "fa-chart-line",
        "description": "Yöneticiler için gün başlangıcı kısa kurum içi durum özeti.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Sabah Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün başlangıcı yönetici özeti aşağıdadır.

Tarih: {tarih}
Aktif personel sayısı: {aktif_personel_sayisi}
Son bilgilendirme durumu: {son_gonderim_durumu}
Bugün takip edilecek ana başlık: {gunun_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi çalışmalar dileriz.

BYS360""",
    },
    "manager_evening": {
        "category": "yonetici",
        "label": "Yönetici Akşam Özeti",
        "short_label": "Akşam Yönetici",
        "default_hour": 17,
        "default_minute": 45,
        "icon": "fa-clipboard-check",
        "description": "Yöneticiler için gün sonu kısa durum ve ertesi gün dikkat notu.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Akşam Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün sonu yönetici özeti aşağıdadır.

Tarih: {tarih}
Son gönderim durumu: {son_gonderim_durumu}
Yarın için dikkat notu: {yarin_yonetici_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi akşamlar dileriz.

BYS360""",
    },
}

def _run_due_tasks_base(*, now: _cic_dt_datetime | None = None, dry_run: bool = False, actor_user_id: int | None = None, force: bool = False) -> dict[str, _cic_typing_any]:  # type: ignore[override]
    """Zamanı gelen aktif mail görevlerini çalıştırır; hafta sonu otomatik gönderimi engeller."""
    ensure_defaults(actor_user_id=actor_user_id)
    scheduler = get_auto_scheduler_config()
    current = now or _now()
    today = current.strftime("%Y-%m-%d")
    weekday_name = _cic_weekday_name_tr(current)

    if not scheduler.get("enabled") and not force:
        return {
            "ok": True,
            "scheduler_enabled": False,
            "message": "Otomatik mail zamanlayıcısı BYS360 Sistem ekranında pasif.",
            "now": current.strftime("%Y-%m-%d %H:%M:%S"),
            "weekday": weekday_name,
            "ran": [],
            "skipped": [],
        }

    if bool(scheduler.get("weekdays_only", True)) and _cic_is_weekend(current) and not force:
        return {
            "ok": True,
            "scheduler_enabled": True,
            "weekdays_only": True,
            "weekend_blocked": True,
            "dry_run": dry_run,
            "force": force,
            "now": current.strftime("%Y-%m-%d %H:%M:%S"),
            "weekday": weekday_name,
            "message": "Bugün hafta sonu olduğu için otomatik mail gönderimi yapılmadı.",
            "results": [],
            "ran": [],
            "skipped": [{"action": "skipped", "reason": "Hafta sonu otomatik gönderim kapalı", "weekday": weekday_name}],
            "ran_any": False,
        }

    cfg = get_config()
    tasks_cfg = cfg.get("tasks", {}) if isinstance(cfg, dict) else {}
    late_window = int(scheduler.get("late_window_minutes") or 20)
    results: list[dict[str, _cic_typing_any]] = []
    ran_any = False

    for task_key, meta in TASK_DEFINITIONS.items():
        task_cfg = tasks_cfg.get(task_key, {}) if isinstance(tasks_cfg, dict) else {}
        enabled = bool(task_cfg.get("enabled", False))
        try:
            hour = int(task_cfg.get("hour", meta.get("default_hour", 12)))
            minute = int(task_cfg.get("minute", meta.get("default_minute", 0)))
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1884")
            hour = int(meta.get("default_hour", 12))
            minute = int(meta.get("default_minute", 0))
        scheduled = current.replace(hour=max(0, min(23, hour)), minute=max(0, min(59, minute)), second=0, microsecond=0)
        diff_minutes = (current - scheduled).total_seconds() / 60.0
        last_run = get_setting(_cic_auto_last_run_key(task_key), "") or ""
        already_today = last_run.startswith(today)

        row: dict[str, _cic_typing_any] = {
            "task_key": task_key,
            "task_label": meta.get("label", task_key),
            "enabled": enabled,
            "scheduled_time": f"{hour:02d}:{minute:02d}",
            "last_auto_run": last_run,
            "weekday": weekday_name,
        }

        if not enabled:
            row.update({"action": "skipped", "reason": "Görev pasif"})
            results.append(row)
            continue
        if already_today and not force:
            row.update({"action": "skipped", "reason": "Bugün zaten otomatik çalıştı"})
            results.append(row)
            continue
        if not force and not (0 <= diff_minutes <= late_window):
            row.update({"action": "waiting", "reason": f"Zamanı gelmedi veya {late_window} dk tolerans dışında"})
            results.append(row)
            continue

        result = send_task(task_key, dry_run=dry_run, actor_user_id=actor_user_id)
        set_setting(_cic_auto_last_run_key(task_key), current.strftime("%Y-%m-%d %H:%M:%S"), label=f"{meta.get('label', task_key)} son otomatik çalışma", actor_user_id=actor_user_id)
        try:
            db.session.commit()
        except Exception:
            db.session.rollback()
        row.update({"action": "ran", "result": result})
        results.append(row)
        ran_any = True

    return {
        "ok": True,
        "scheduler_enabled": True,
        "weekdays_only": bool(scheduler.get("weekdays_only", True)),
        "weekend_blocked": False,
        "dry_run": dry_run,
        "force": force,
        "now": current.strftime("%Y-%m-%d %H:%M:%S"),
        "weekday": weekday_name,
        "late_window_minutes": late_window,
        "ran_any": ran_any,
        "results": results,
        "ran": [r for r in results if r.get("action") == "ran"],
        "skipped": [r for r in results if r.get("action") != "ran"],
    }

def run_due_tasks(*, now: _cic_v40_datetime | None = None, dry_run: bool = False, actor_user_id: int | None = None, force: bool = False) -> dict[str, _cic_v40_Any]:
    """Run due CIC mail tasks through one explicit public layer.

    Flattened legacy wrapper chain:
    - Base scheduler execution is handled by _run_due_tasks_base.
    - Weekend celebration exception tasks are applied explicitly after the base result.
    """
    result = _run_due_tasks_base(now=now, dry_run=dry_run, actor_user_id=actor_user_id, force=force)

    current = now or _now()
    if result.get("weekend_blocked") and not force:
        extra = _cic_v40_run_weekend_celebrations(current, dry_run=dry_run, actor_user_id=actor_user_id)
        if extra:
            result["weekend_blocked"] = False
            result["message"] = "Hafta sonu genel gonderimler engellendi; kutlama gorevleri ayar geregi calistirildi."
            result.setdefault("results", []).extend(extra)
            result["ran"] = list(result.get("ran") or []) + extra
            result["ran_any"] = True

    return result

__all__ = [
    "_run_due_tasks_base",
    "run_due_tasks",
]
