"""Save/update helpers split from app.services.corporate_information_center.

Generated by Phase4J V30C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

from __future__ import annotations
import json
import ssl
import time
from datetime import datetime
from typing import Any
from urllib.request import urlopen
from flask import current_app
from sqlalchemy import or_
from app.extensions import db
from app.models import SystemSetting, User
from app.services.cic.config_context import (
    _clean_ids,
    _clothing,
    _dumps_json,
    _ensure_defaults_base,
    _format_weather,
    _has_settings_table,
    _loads_json,
    _now,
    _tomorrow_note,
    _weather,
    ensure_defaults,
    get_config,
    get_setting,
    set_setting,
)
from app.services.cic.send_context import (
    _cic_v11_bool,
    _cic_v11_clean_header,
    _cic_v11_get_setting_value,
    _cic_v11_mail_settings,
    _cic_v11_normalize_email,
    _cic_v11_send_email_direct,
    _cic_v40_active_staff_candidates,
    _cic_v40_anniversary_users,
    _cic_v40_birthday_users,
    _cic_v40_bool,
    _cic_v40_mmdd,
    _cic_v40_parse_date,
    _cic_v40_service_year,
    _cic_v40_setting_bool,
    _cic_v40_special_day_users,
    _cic_v40_special_days,
    _cic_v40_special_days_today,
    _cic_v40_today,
    _cic_v40_user_date,
    _dashboard_counts,
    _recipients_for_task,
    _recipients_for_task_base,
    _render_template_text,
    _render_template_text_base,
    _send_task_base,
    _user_name,
)
from app.services.cic.misc_context import (
    _active_staff_users,
    _cic_auto_bool,
    _cic_phase5_audit_list,
    _cic_phase5_last_result,
    _cic_phase5_log_metrics,
    _cic_phase5_mail_health,
    _cic_phase5_readiness,
    _cic_phase5_safe_int,
    _cic_phase5_task_preview,
    _cic_phase6_build,
    _cic_phase6_item,
    _cic_phase6_log_quality,
    _cic_phase6_missing_email_count,
    _cic_phase6_status,
    _cic_phase6_template_quality,
    _context_base,
    _users_by_ids,
    context,
    get_auto_scheduler_config,
    get_recent_logs,
    get_recipients,
    get_template,
    list_users,
)
from app.services.cic.cic_context import (
    _cic_auto_last_run_key,
    _cic_is_weekend,
    _cic_phase3_actor_label,
    _cic_phase3_last_result,
    _cic_phase3_make_result,
    _cic_phase3_public_error,
    _cic_phase3_store_result,
    _cic_phase3_task_label,
    _cic_phase5_actor,
    _cic_phase5_now_label,
    _cic_phase5_store_audit,
    _cic_phase6_bool,
    _cic_v40_create_system_notifications,
    _cic_v40_date_input,
    _cic_v40_days_until,
    _cic_v40_run_weekend_celebrations,
    _cic_v40_upcoming_special_days,
    _cic_v40_upcoming_users,
    _cic_v45_bool,
    _cic_v45_build_user_indexes,
    _cic_v45_ensure_schema,
    _cic_v45_existing_user_rows,
    _cic_v45_header_key,
    _cic_v45_norm,
    _cic_v45_norm_name,
    _cic_v45_parse_date,
    _cic_v45_text,
    _cic_weekday_name_tr,
    send_task,
)

BASE_KEY = "corporate_information_center"

TASK_DEFINITIONS: dict[str, dict[str, Any]] = {
    "staff_morning": {
        "category": "personel",
        "label": "Personel Sabah Bilgilendirmesi",
        "short_label": "Sabah Personel",
        "default_hour": 8,
        "default_minute": 0,
        "icon": "fa-sun",
        "description": "Günaydın mesajı, bugünkü hava durumu, kıyafet önerisi ve iyi dilek.",
        "recipient_group": "staff",
        "subject": "Günaydın | BYS360 Günlük Bilgilendirme",
        "body": """Sayın {ad_soyad},

Günaydın.

Bugün {konum} için hava durumu özeti:
{bugun_hava}

Kıyafet önerisi:
{kiyafet_onerisi}

Başarılı, verimli ve güzel bir gün geçirmenizi dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    # BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE6_1_STAFF_NOON_MESSAGE
    "staff_noon": {
        "category": "personel",
        "label": "Personel Öğlen Bilgilendirmesi",
        "short_label": "Öğlen Personel",
        "default_hour": 12,
        "default_minute": 30,
        "icon": "fa-mug-hot",
        "description": "Gün ortası iyi dilek, mesai kontrolü ve geri bildirim hatırlatması.",
        "recipient_group": "staff",
        "subject": "BYS360 Gün Ortası Destek Hatırlatması",
        "body": """Sayın {ad_soyad},

Gününüz nasıl geçiyor?

Sistemde destek ihtiyacı duyduğunuz bir konu var mı?

BYS360 kullanımı sırasında destek, öneri, hata bildirimi veya geliştirme ihtiyacı oluşursa Geri Bildirim Merkezi üzerinden bize iletebilirsiniz.

Geri bildirim bağlantısı:
{geri_bildirim_baglantisi}

İyi çalışmalar dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    "staff_evening": {
        "category": "personel",
        "label": "Personel Akşam Bilgilendirmesi",
        "short_label": "Akşam Personel",
        "default_hour": 17,
        "default_minute": 30,
        "icon": "fa-cloud-moon",
        "description": "İyi akşamlar mesajı, yarın hava durumu ve ertesi gün hazırlık notu.",
        "recipient_group": "staff",
        "subject": "İyi Akşamlar | BYS360 Yarın İçin Bilgilendirme",
        "body": """Sayın {ad_soyad},

İyi akşamlar.

Yarın {konum} için beklenen hava durumu:
{yarin_hava}

Yarın için öneri:
{yarin_oneri}

Bugünkü emekleriniz için teşekkür eder, güzel bir akşam dileriz.

BYS360""",
    },
    "manager_morning": {
        "category": "yonetici",
        "label": "Yönetici Sabah Özeti",
        "short_label": "Sabah Yönetici",
        "default_hour": 7,
        "default_minute": 45,
        "icon": "fa-chart-line",
        "description": "Yöneticiler için gün başlangıcı kısa kurum içi durum özeti.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Sabah Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün başlangıcı yönetici özeti aşağıdadır.

Tarih: {tarih}
Aktif personel sayısı: {aktif_personel_sayisi}
Son bilgilendirme durumu: {son_gonderim_durumu}
Bugün takip edilecek ana başlık: {gunun_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi çalışmalar dileriz.

BYS360""",
    },
    "manager_evening": {
        "category": "yonetici",
        "label": "Yönetici Akşam Özeti",
        "short_label": "Akşam Yönetici",
        "default_hour": 17,
        "default_minute": 45,
        "icon": "fa-clipboard-check",
        "description": "Yöneticiler için gün sonu kısa durum ve ertesi gün dikkat notu.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Akşam Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün sonu yönetici özeti aşağıdadır.

Tarih: {tarih}
Son gönderim durumu: {son_gonderim_durumu}
Yarın için dikkat notu: {yarin_yonetici_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi akşamlar dileriz.

BYS360""",
    },
}

def save_tasks(payload: dict[str, Any], actor_user_id: int | None = None) -> None:
    cfg = get_config()
    tasks = cfg["tasks"]
    for key, meta in TASK_DEFINITIONS.items():
        t = tasks.setdefault(key, {})
        t["enabled"] = str(payload.get(f"enabled_{key}", "")).lower() in {"1", "true", "on", "yes"}
        try:
            t["hour"] = max(0, min(23, int(payload.get(f"hour_{key}", meta["default_hour"]))))
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:301")
            t["hour"] = meta["default_hour"]
        try:
            t["minute"] = max(0, min(59, int(payload.get(f"minute_{key}", meta["default_minute"]))))
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:305")
            t["minute"] = meta["default_minute"]
        t["recipient_group"] = meta["recipient_group"]
    set_setting(f"{BASE_KEY}.tasks", _dumps_json(tasks), label="Kurumsal bilgilendirme görevleri", value_type="json", actor_user_id=actor_user_id)
    db.session.commit()

def save_templates(payload: dict[str, Any], actor_user_id: int | None = None) -> None:
    for key, meta in TASK_DEFINITIONS.items():
        subject = (payload.get(f"subject_{key}") or meta["subject"]).strip()
        body = (payload.get(f"body_{key}") or meta["body"]).strip()
        set_setting(f"{BASE_KEY}.template.{key}.subject", subject, label=f"{meta['label']} konusu", actor_user_id=actor_user_id)
        set_setting(f"{BASE_KEY}.template.{key}.body", body, label=f"{meta['label']} metni", value_type="text", actor_user_id=actor_user_id)
    db.session.commit()

def _save_system_base(payload: dict[str, Any], actor_user_id: int | None = None) -> None:
    set_setting(f"{BASE_KEY}.location_name", (payload.get("location_name") or "Çanakkale").strip(), label="Hava durumu konumu", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.latitude", (payload.get("latitude") or "40.1553").strip(), label="Enlem", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.longitude", (payload.get("longitude") or "26.4142").strip(), label="Boylam", actor_user_id=actor_user_id)
    db.session.commit()

def save_recipients(payload: dict[str, Any], actor_user_id: int | None = None) -> None:  # noqa: F811
    def getlist_all(*names: str) -> list[Any]:
        values: list[Any] = []
        for name in names:
            try:
                if hasattr(payload, "getlist"):
                    part = payload.getlist(name)
                else:
                    raw = payload.get(name, []) if hasattr(payload, "get") else []
                    part = raw if isinstance(raw, list) else ([raw] if raw else [])
            except Exception:
                __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1570")
                part = []
            for item in part or []:
                if item not in values:
                    values.append(item)
        return values

    manager_ids = _clean_ids(getlist_all("manager_ids", "manager_user_ids", "manager_recipient_ids", "selected_manager_ids"))
    staff_ids = _clean_ids(getlist_all("staff_ids", "staff_user_ids", "staff_recipient_ids", "selected_staff_ids"))
    mode = str(payload.get("staff_recipient_mode") or "manual").strip() if hasattr(payload, "get") else "manual"
    if mode not in {"manual", "all_active"}:
        mode = "manual"

    set_setting(f"{BASE_KEY}.manager_recipient_ids", _dumps_json(manager_ids), label="Yönetici alıcıları", value_type="json", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.staff_recipient_ids", _dumps_json(staff_ids), label="Personel alıcıları", value_type="json", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.staff_recipient_mode", mode, label="Personel alıcı modu", value_type="string", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.last_recipient_save_summary", _dumps_json({"manager_count": len(manager_ids), "staff_count": len(staff_ids), "mode": mode}), label="Son alıcı kayıt özeti", value_type="json", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.last_recipient_save_at", _now().isoformat(timespec="seconds"), label="Son alıcı kayıt zamanı", value_type="string", actor_user_id=actor_user_id)
    db.session.commit()

def set_auto_scheduler_config(payload: dict[str, object], actor_user_id: int | None = None) -> None:  # type: ignore[override]
    enabled = "true" if _cic_auto_bool(payload.get("auto_scheduler_enabled"), default=False) else "false"
    if "auto_scheduler_weekdays_only" in payload:
        weekdays_only = "true" if _cic_auto_bool(payload.get("auto_scheduler_weekdays_only"), default=True) else "false"
    else:
        weekdays_only = str(get_setting(f"{BASE_KEY}.auto_scheduler_weekdays_only", "true") or "true").lower()
        if weekdays_only not in {"true", "false"}:
            weekdays_only = "true"
    try:
        late_window = int(payload.get("auto_scheduler_late_window_minutes") or 20)
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1793")
        late_window = 20
    late_window = max(1, min(120, late_window))

    set_setting(f"{BASE_KEY}.auto_scheduler_enabled", enabled, label="Otomatik mail zamanlayıcı", value_type="boolean", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.auto_scheduler_weekdays_only", weekdays_only, label="Otomatik mail yalnızca hafta içi", value_type="boolean", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.auto_scheduler_late_window_minutes", str(late_window), label="Otomatik mail gecikme toleransı", value_type="integer", actor_user_id=actor_user_id)
    try:
        db.session.commit()
    except Exception:
        db.session.rollback()

def save_system(payload: dict[str, object], actor_user_id: int | None = None) -> None:
    """Persist CIC system settings through one explicit public layer.

    Flattened legacy wrapper chain:
    - Base weather/location settings are saved by _save_system_base.
    - Auto scheduler settings are saved once by set_auto_scheduler_config.
    """
    _save_system_base(payload, actor_user_id=actor_user_id)
    set_auto_scheduler_config(payload, actor_user_id=actor_user_id)

def ensure_celebration_schema() -> dict[str, object]:
    """Kullanici tablosunda kutlama motoru icin gerekli tarih alanlarini guvenli sekilde olusturur."""
    result: dict[str, object] = {"ok": True, "added": [], "warnings": []}
    try:
        from sqlalchemy import inspect as _sa_inspect, text as _sa_text
        inspector = _sa_inspect(db.engine)
        if not inspector.has_table("users"):
            result["ok"] = False
            result["warnings"] = ["users tablosu bulunamadı."]
            return result
        cols = {c.get("name") for c in inspector.get_columns("users")}
        dialect = getattr(db.engine.dialect, "name", "")
        needed = {
            "birth_date": "DATE",
            "hire_date": "DATE",
            "celebration_opt_out": "BOOLEAN DEFAULT FALSE",
        }
        with db.engine.begin() as conn:
            for col, sql_type in needed.items():
                if col in cols:
                    continue
                if dialect == "postgresql":
                    conn.execute(_sa_text(f"ALTER TABLE users ADD COLUMN IF NOT EXISTS {col} {sql_type}"))
                else:
                    conn.execute(_sa_text(f"ALTER TABLE users ADD COLUMN {col} {sql_type}"))
                result.setdefault("added", []).append(col)
    except Exception as exc:
        result["ok"] = False
        result.setdefault("warnings", []).append(str(exc))
    return result

def save_celebration_settings(payload: dict[str, object], actor_user_id: int | None = None) -> None:
    ensure_celebration_schema()
    bool_fields = [
        "celebrations_enabled",
        "birthday_enabled",
        "work_anniversary_enabled",
        "special_day_enabled",
        "celebration_system_notifications_enabled",
        "celebrations_include_weekend",
    ]
    for field in bool_fields:
        set_setting(f"{BASE_KEY}.{field}", "true" if _cic_v40_bool(payload.get(field), False) else "false", label=field, value_type="boolean", actor_user_id=actor_user_id)
    mode = str(payload.get("special_day_recipient_mode") or "all_active").strip()
    if mode not in {"all_active", "manual"}:
        mode = "all_active"
    set_setting(f"{BASE_KEY}.special_day_recipient_mode", mode, label="Özel gün hedef kitlesi", value_type="string", actor_user_id=actor_user_id)

    raw_days = str(payload.get("special_days_json") or "").strip()
    if raw_days:
        try:
            parsed = json.loads(raw_days)
            if isinstance(parsed, list):
                set_setting(f"{BASE_KEY}.special_days", _dumps_json(parsed), label="Özel gün takvimi", value_type="json", actor_user_id=actor_user_id)
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 CIC kontrollü geri dönüş bloğu çalıştı")
            set_setting(f"{BASE_KEY}.special_days.last_error", "Özel gün JSON formatı geçerli değil; eski takvim korundu.", label="Özel gün son hata", value_type="text", actor_user_id=actor_user_id)

    ids = []
    try:
        ids = payload.getlist("user_ids") if hasattr(payload, "getlist") else payload.get("user_ids", [])
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2452")
        ids = []
    for raw_id in ids or []:
        try:
            uid = int(raw_id)
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2457")
            continue
        user = db.session.get(User, uid)
        if not user:
            continue
        birth_value = str(payload.get(f"birth_date_{uid}") or "").strip()
        hire_value = str(payload.get(f"hire_date_{uid}") or "").strip()
        opt_out = _cic_v40_bool(payload.get(f"celebration_opt_out_{uid}"), False)
        if hasattr(user, "birth_date"):
            setattr(user, "birth_date", _cic_v40_parse_date(birth_value))
        if hasattr(user, "hire_date"):
            setattr(user, "hire_date", _cic_v40_parse_date(hire_value))
        if hasattr(user, "celebration_opt_out"):
            setattr(user, "celebration_opt_out", opt_out)
    try:
        db.session.commit()
    except Exception:
        db.session.rollback()
        raise

__all__ = [
    "_save_system_base",
    "ensure_celebration_schema",
    "save_celebration_settings",
    "save_recipients",
    "save_system",
    "save_tasks",
    "save_templates",
    "set_auto_scheduler_config",
]
