"""Send/mail helpers split from app.services.corporate_information_center.

Generated by Phase4J V28C. Kept API-compatible through facade imports.
"""

from __future__ import annotations

from __future__ import annotations
import json
import ssl
import time
from datetime import datetime
from typing import Any
from urllib.request import urlopen
from flask import current_app
from sqlalchemy import or_
from app.extensions import db
from app.models import SystemSetting, User
from app.services.cic.config_context import (
    _clean_ids,
    _clothing,
    _dumps_json,
    _ensure_defaults_base,
    _format_weather,
    _has_settings_table,
    _loads_json,
    _now,
    _tomorrow_note,
    _weather,
    ensure_defaults,
    get_config,
    get_setting,
    set_setting,
)
from app.services.cic.misc_context import (
    _active_staff_users,
    _cic_auto_bool,
    _cic_phase5_audit_list,
    _cic_phase5_last_result,
    _cic_phase5_log_metrics,
    _cic_phase5_mail_health,
    _cic_phase5_readiness,
    _cic_phase5_safe_int,
    _cic_phase5_task_preview,
    _cic_phase6_build,
    _cic_phase6_item,
    _cic_phase6_log_quality,
    _cic_phase6_missing_email_count,
    _cic_phase6_status,
    _cic_phase6_template_quality,
    _context_base,
    _users_by_ids,
    context,
    get_auto_scheduler_config,
    get_recent_logs,
    get_recipients,
    get_template,
    list_users,
)
from datetime import datetime as _cic_dt_datetime
from typing import Any as _cic_typing_any
from datetime import date as _cic_v40_date, datetime as _cic_v40_datetime
from typing import Any as _cic_v40_Any
from datetime import date as _cic_v45_date, datetime as _cic_v45_datetime, timedelta as _cic_v45_timedelta
import re as _cic_v45_re
import unicodedata as _cic_v45_unicodedata

BASE_KEY = "corporate_information_center"

TASK_DEFINITIONS: dict[str, dict[str, Any]] = {
    "staff_morning": {
        "category": "personel",
        "label": "Personel Sabah Bilgilendirmesi",
        "short_label": "Sabah Personel",
        "default_hour": 8,
        "default_minute": 0,
        "icon": "fa-sun",
        "description": "Günaydın mesajı, bugünkü hava durumu, kıyafet önerisi ve iyi dilek.",
        "recipient_group": "staff",
        "subject": "Günaydın | BYS360 Günlük Bilgilendirme",
        "body": """Sayın {ad_soyad},

Günaydın.

Bugün {konum} için hava durumu özeti:
{bugun_hava}

Kıyafet önerisi:
{kiyafet_onerisi}

Başarılı, verimli ve güzel bir gün geçirmenizi dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    # BYS360_CORPORATE_INFORMATION_CENTER_V3_0_PHASE6_1_STAFF_NOON_MESSAGE
    "staff_noon": {
        "category": "personel",
        "label": "Personel Öğlen Bilgilendirmesi",
        "short_label": "Öğlen Personel",
        "default_hour": 12,
        "default_minute": 30,
        "icon": "fa-mug-hot",
        "description": "Gün ortası iyi dilek, mesai kontrolü ve geri bildirim hatırlatması.",
        "recipient_group": "staff",
        "subject": "BYS360 Gün Ortası Destek Hatırlatması",
        "body": """Sayın {ad_soyad},

Gününüz nasıl geçiyor?

Sistemde destek ihtiyacı duyduğunuz bir konu var mı?

BYS360 kullanımı sırasında destek, öneri, hata bildirimi veya geliştirme ihtiyacı oluşursa Geri Bildirim Merkezi üzerinden bize iletebilirsiniz.

Geri bildirim bağlantısı:
{geri_bildirim_baglantisi}

İyi çalışmalar dileriz.

BYS360
Çanakkale Savaşları Gelibolu Tarihi Alan Başkanlığı""",
    },
    "staff_evening": {
        "category": "personel",
        "label": "Personel Akşam Bilgilendirmesi",
        "short_label": "Akşam Personel",
        "default_hour": 17,
        "default_minute": 30,
        "icon": "fa-cloud-moon",
        "description": "İyi akşamlar mesajı, yarın hava durumu ve ertesi gün hazırlık notu.",
        "recipient_group": "staff",
        "subject": "İyi Akşamlar | BYS360 Yarın İçin Bilgilendirme",
        "body": """Sayın {ad_soyad},

İyi akşamlar.

Yarın {konum} için beklenen hava durumu:
{yarin_hava}

Yarın için öneri:
{yarin_oneri}

Bugünkü emekleriniz için teşekkür eder, güzel bir akşam dileriz.

BYS360""",
    },
    "manager_morning": {
        "category": "yonetici",
        "label": "Yönetici Sabah Özeti",
        "short_label": "Sabah Yönetici",
        "default_hour": 7,
        "default_minute": 45,
        "icon": "fa-chart-line",
        "description": "Yöneticiler için gün başlangıcı kısa kurum içi durum özeti.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Sabah Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün başlangıcı yönetici özeti aşağıdadır.

Tarih: {tarih}
Aktif personel sayısı: {aktif_personel_sayisi}
Son bilgilendirme durumu: {son_gonderim_durumu}
Bugün takip edilecek ana başlık: {gunun_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi çalışmalar dileriz.

BYS360""",
    },
    "manager_evening": {
        "category": "yonetici",
        "label": "Yönetici Akşam Özeti",
        "short_label": "Akşam Yönetici",
        "default_hour": 17,
        "default_minute": 45,
        "icon": "fa-clipboard-check",
        "description": "Yöneticiler için gün sonu kısa durum ve ertesi gün dikkat notu.",
        "recipient_group": "managers",
        "subject": "BYS360 Yönetici Akşam Özeti",
        "body": """Sayın {ad_soyad},

BYS360 gün sonu yönetici özeti aşağıdadır.

Tarih: {tarih}
Son gönderim durumu: {son_gonderim_durumu}
Yarın için dikkat notu: {yarin_yonetici_notu}

Sistem bağlantısı:
{bys360_baglanti}

İyi akşamlar dileriz.

BYS360""",
    },
}

_CIC_V40_SPECIAL_DAY_DEFAULTS = [
    {"date": "03-18", "name": "18 Mart Çanakkale Zaferi ve Şehitleri Anma Günü", "enabled": True, "target": "all_staff"},
    {"date": "04-23", "name": "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı", "enabled": True, "target": "all_staff"},
    {"date": "05-19", "name": "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı", "enabled": True, "target": "all_staff"},
    {"date": "08-30", "name": "30 Ağustos Zafer Bayramı", "enabled": True, "target": "all_staff"},
    {"date": "10-29", "name": "29 Ekim Cumhuriyet Bayramı", "enabled": True, "target": "all_staff"},
    {"date": "12-01", "name": "Seyit Onbaşı Anma Günü", "enabled": True, "target": "all_staff"},
]

def _user_name(user: User | None) -> str:
    if not user:
        return "-"
    return (f"{getattr(user, 'ad', '') or ''} {getattr(user, 'soyad', '') or ''}".strip()
            or getattr(user, "full_name_cache", None)
            or getattr(user, "email", None)
            or f"Kullanıcı #{getattr(user, 'id', '-')}")

def _dashboard_counts() -> dict[str, str]:
    try:
        active_count = User.query.filter(User.is_active.is_(True)).count() if hasattr(User, "is_active") else User.query.count()
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:468")
        active_count = "-"
    return {
        "aktif_personel_sayisi": active_count,
        "son_gonderim_durumu": get_setting(f"{BASE_KEY}.last_status", "Henüz gönderim yapılmadı") or "Henüz gönderim yapılmadı",
        "gunun_notu": "BYS360 süreçlerinin gün içinde düzenli izlenmesi önerilir.",
        "yarin_yonetici_notu": "Ertesi gün için bekleyen görev ve geri bildirimlerin kontrol edilmesi önerilir.",
    }

def _render_template_text_base(text: str, user: User | None, task_key: str) -> str:
    cfg = get_config()
    w = _weather() if task_key.startswith("staff_") else {"bugun_hava": "-", "yarin_hava": "-", "kiyafet_onerisi": "-", "yarin_oneri": "-"}
    counts = _dashboard_counts()
    context = {
        "ad_soyad": _user_name(user),
        "email": getattr(user, "email", "") if user else "",
        "tarih": _now().strftime("%d.%m.%Y"),
        "saat": _now().strftime("%H:%M"),
        "konum": cfg["location_name"],
        "bys360_baglanti": "https://bys360.canakkaletarihialan.gov.tr/",
        "geri_bildirim_baglantisi": "https://bys360.canakkaletarihialan.gov.tr/feedback",
        **w,
        **counts,
    }
    rendered = text or ""
    for k, v in context.items():
        rendered = rendered.replace("{" + k + "}", str(v))
    return rendered

def _recipients_for_task_base(task_key: str, override_users: list[User] | None = None) -> list[User]:
    if override_users is not None:
        return override_users
    group = TASK_DEFINITIONS[task_key]["recipient_group"]
    rec = get_recipients()
    return rec["managers"] if group == "managers" else rec["staff"]

def _cic_v11_bool(value, default=False):
    if value is None or value == "":
        return bool(default)
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "on", "yes", "evet", "tls", "ssl"}:
        return True
    if normalized in {"0", "false", "off", "no", "hayir", "hayır", "none", "null"}:
        return False
    return bool(default)

def _cic_v11_get_setting_value(keys, default=""):
    try:
        from flask import current_app as _ca
        for key in keys:
            try:
                value = _ca.config.get(key)
                if value is not None and str(value).strip() != "":
                    return value
            except Exception:
                __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1344")
                pass
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1346")
        pass
    for key in keys:
        try:
            value = get_setting(key, "")
            if value is not None and str(value).strip() != "":
                return value
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1353")
            pass
    # Geniş uyumluluk için noktalı/alt çizgili varyasyonları da dene
    aliases = []
    for key in keys:
        aliases.extend([key.lower(), key.lower().replace("_", "."), key.lower().replace("_", "-")])
    for key in aliases:
        try:
            value = get_setting(key, "")
            if value is not None and str(value).strip() != "":
                return value
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1364")
            pass
    return default

def _cic_v11_clean_header(value):
    return str(value or "").replace("\r", " ").replace("\n", " ").strip()

def _cic_v11_normalize_email(value):
    email = _cic_v11_clean_header(value).strip().strip(",;")
    if not email or "@" not in email or " " in email:
        return ""
    return email

def _cic_v11_mail_settings():
    server = _cic_v11_get_setting_value(["MAIL_SERVER", "SMTP_SERVER", "mail_server", "smtp_server", "corporate_information_center.mail_server", "corporate_information_center.smtp_server"], "")
    port = _cic_v11_get_setting_value(["MAIL_PORT", "SMTP_PORT", "mail_port", "smtp_port", "corporate_information_center.mail_port", "corporate_information_center.smtp_port"], 587)
    username = _cic_v11_get_setting_value(["MAIL_USERNAME", "SMTP_USERNAME", "mail_username", "smtp_username", "corporate_information_center.mail_username", "corporate_information_center.smtp_username"], "")
    password = _cic_v11_get_setting_value(["MAIL_PASSWORD", "SMTP_PASSWORD", "mail_password", "smtp_password", "corporate_information_center.mail_password", "corporate_information_center.smtp_password"], "")
    sender = _cic_v11_get_setting_value(["MAIL_DEFAULT_SENDER", "SMTP_SENDER", "MAIL_SENDER", "mail_default_sender", "mail_sender", "smtp_sender", "corporate_information_center.mail_sender", "corporate_information_center.smtp_sender"], "") or username
    use_tls = _cic_v11_bool(_cic_v11_get_setting_value(["MAIL_USE_TLS", "SMTP_USE_TLS", "mail_use_tls", "smtp_use_tls", "corporate_information_center.mail_use_tls"], True), True)
    use_ssl = _cic_v11_bool(_cic_v11_get_setting_value(["MAIL_USE_SSL", "SMTP_USE_SSL", "mail_use_ssl", "smtp_use_ssl", "corporate_information_center.mail_use_ssl"], False), False)
    suppress = _cic_v11_bool(_cic_v11_get_setting_value(["MAIL_SUPPRESS_SEND", "mail_suppress_send", "corporate_information_center.mail_suppress_send"], False), False)
    try:
        port = int(str(port).strip())
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1391")
        port = 587
    return {
        "server": str(server or "").strip(),
        "port": port,
        "username": str(username or "").strip(),
        "password": password or "",
        "sender": str(sender or "").strip(),
        "use_tls": bool(use_tls),
        "use_ssl": bool(use_ssl),
        "suppress_send": bool(suppress),
    }

def _cic_v11_send_email_direct(to_email, subject, body):
    import smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    settings = _cic_v11_mail_settings()
    target = _cic_v11_normalize_email(to_email)
    sender = _cic_v11_normalize_email(settings.get("sender"))
    subject_line = _cic_v11_clean_header(subject)

    if settings.get("suppress_send"):
        return True, "MAIL_SUPPRESS_SEND aktif: gerçek gönderim yapılmadı."
    if not settings.get("server"):
        return False, "MAIL_SERVER / SMTP_SERVER sistem ayarı bulunamadı."
    if not sender:
        return False, "MAIL_DEFAULT_SENDER / SMTP_SENDER sistem ayarı bulunamadı veya geçersiz."
    if not target:
        return False, "Alıcı e-posta adresi geçersiz ya da boş."
    if not subject_line:
        return False, "Mail konusu boş bırakılamaz."

    msg = MIMEMultipart()
    msg["From"] = sender
    msg["To"] = target
    msg["Subject"] = subject_line
    msg.attach(MIMEText((body or "").strip() or "BYS360 bildirimi", "plain", "utf-8"))

    try:
        if settings.get("use_ssl"):
            smtp = smtplib.SMTP_SSL(settings["server"], settings["port"], timeout=30)
        else:
            smtp = smtplib.SMTP(settings["server"], settings["port"], timeout=30)
        with smtp as server:
            server.ehlo()
            if settings.get("use_tls") and not settings.get("use_ssl"):
                server.starttls()
                server.ehlo()
            if settings.get("username") and settings.get("password"):
                server.login(settings["username"], settings["password"])
            server.sendmail(sender, [target], msg.as_string())
        return True, "Mail başarıyla gönderildi."
    except Exception as exc:
        detail = f"{type(exc).__name__}: {exc}"
        try:
            current_app.logger.warning(
                "Kurumsal Bilgilendirme mail gönderim hatası | to=%s | server=%s:%s | detail=%s",
                target, settings.get("server"), settings.get("port"), detail,
            )
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1453")
            pass
        return False, detail

def _send_task_base(task_key: str, *, dry_run: bool = False, override_users=None, actor_user_id: int | None = None):
    ensure_defaults(actor_user_id=actor_user_id)
    if task_key not in TASK_DEFINITIONS:
        return {"ok": False, "message": "Bilinmeyen görev.", "task_key": task_key}

    cfg = get_config()
    task_cfg = cfg["tasks"].get(task_key, {})
    if not task_cfg.get("enabled", False) and not dry_run:
        return {"ok": False, "skipped": True, "message": "Görev pasif.", "task_key": task_key}

    raw_users = _recipients_for_task(task_key, override_users)
    users = [u for u in raw_users if _cic_v11_normalize_email(getattr(u, "email", None))]
    missing_mail = max(0, len(raw_users) - len(users))
    tmpl = get_template(task_key)
    started = time.time()
    ok_count = 0
    fail_count = 0
    errors = []
    sent_preview = []
    mail_settings = _cic_v11_mail_settings()

    for user in users:
        email = _cic_v11_normalize_email(getattr(user, "email", ""))
        subject = _render_template_text(tmpl["subject"], user, task_key)
        body = _render_template_text(tmpl["body"], user, task_key)
        if dry_run:
            ok, msg = True, "Kuru çalışma: gönderim yapılmadı."
        else:
            ok, msg = _cic_v11_send_email_direct(email, subject, body)

        if ok:
            ok_count += 1
        else:
            fail_count += 1
            errors.append(f"{email}: {msg}")
        sent_preview.append(email)

        try:
            if create_mail_log is not None:
                create_mail_log(
                    mail_type=f"corporate_information_{task_key}",
                    recipient_email=email,
                    subject=subject,
                    body=body,
                    user_id=getattr(user, "id", None),
                    sent_by_id=actor_user_id,
                    is_success=ok,
                    error_message=None if ok else msg,
                )
        except Exception as log_exc:
            try:
                current_app.logger.warning("Kurumsal Bilgilendirme mail log yazılamadı | detail=%s", log_exc)
            except Exception:
                __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:1510")
                pass

    elapsed = round(time.time() - started, 2)
    status = f"Başarılı: {ok_count}, Hatalı: {fail_count}, Eksik e-posta: {missing_mail}, Süre: {elapsed} sn"
    tasks = cfg["tasks"]
    tasks.setdefault(task_key, {}).update({
        "last_status": status,
        "last_run_at": _now().strftime("%d.%m.%Y %H:%M"),
        "last_error": errors[0] if errors else "",
    })
    set_setting(f"{BASE_KEY}.tasks", _dumps_json(tasks), label="Kurumsal bilgilendirme görevleri", value_type="json", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.last_status", f"{TASK_DEFINITIONS[task_key]['label']}: {status}", label="Son kurumsal bilgilendirme durumu", actor_user_id=actor_user_id)
    set_setting(f"{BASE_KEY}.last_error", errors[0] if errors else "", label="Son kurumsal bilgilendirme hatası", value_type="text", actor_user_id=actor_user_id)
    try:
        db.session.commit()
    except Exception:
        db.session.rollback()

    label = TASK_DEFINITIONS[task_key]["label"]
    if dry_run:
        message = f"{label} kuru çalışma tamamlandı: {len(users)} alıcı kontrol edildi, {missing_mail} eksik e-posta."
    else:
        message = f"{label} çalıştırıldı: {ok_count} başarılı, {fail_count} hatalı."
        if missing_mail:
            message += f" Eksik e-posta: {missing_mail}."
        if errors:
            message += f" İlk hata: {errors[0]}"

    return {
        "ok": fail_count == 0,
        "message": message,
        "task_key": task_key,
        "task_label": label,
        "dry_run": dry_run,
        "recipient_count": len(users),
        "success_count": ok_count,
        "fail_count": fail_count,
        "missing_mail_count": missing_mail,
        "errors": errors[:20],
        "recipients": sent_preview[:20],
        "elapsed_seconds": elapsed,
        "mail_server": mail_settings.get("server"),
        "mail_port": mail_settings.get("port"),
        "mail_sender": mail_settings.get("sender"),
    }

def _cic_v40_bool(value: object, default: bool = False) -> bool:
    if value is None:
        return default
    text = str(value).strip().lower()
    if text == "":
        return default
    return text in {"1", "true", "on", "yes", "evet", "aktif", "checked"}

def _cic_v40_parse_date(value: object) -> _cic_v40_date | None:
    if value is None:
        return None
    if isinstance(value, _cic_v40_datetime):
        return value.date()
    if isinstance(value, _cic_v40_date):
        return value
    text = str(value).strip()
    if not text:
        return None
    for fmt in ("%Y-%m-%d", "%d.%m.%Y", "%d/%m/%Y", "%Y/%m/%d"):
        try:
            return _cic_v40_datetime.strptime(text, fmt).date()
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2033")
            pass
    return None

def _cic_v40_user_date(user: object, *names: str) -> _cic_v40_date | None:
    for name in names:
        try:
            value = getattr(user, name, None)
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2042")
            value = None
        parsed = _cic_v40_parse_date(value)
        if parsed:
            return parsed
    return None

def _cic_v40_today(now: object = None) -> _cic_v40_date:
    if isinstance(now, _cic_v40_datetime):
        return now.date()
    if isinstance(now, _cic_v40_date):
        return now
    try:
        return _now().date()
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2057")
        return _cic_v40_date.today()

def _cic_v40_mmdd(d: _cic_v40_date | None) -> str:
    return d.strftime("%m-%d") if d else ""

def _cic_v40_setting_bool(name: str, default: bool = True) -> bool:
    return _cic_v40_bool(get_setting(f"{BASE_KEY}.{name}", "true" if default else "false"), default)

def _cic_v40_special_days() -> list[dict[str, object]]:
    data = _loads_json(f"{BASE_KEY}.special_days", _CIC_V40_SPECIAL_DAY_DEFAULTS)
    if not isinstance(data, list):
        return list(_CIC_V40_SPECIAL_DAY_DEFAULTS)
    out: list[dict[str, object]] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        date_value = str(item.get("date") or "").strip()
        name = str(item.get("name") or "").strip()
        if not date_value or not name:
            continue
        out.append({
            "date": date_value,
            "name": name,
            "enabled": _cic_v40_bool(item.get("enabled"), True),
            "target": str(item.get("target") or "all_staff"),
        })
    return out or list(_CIC_V40_SPECIAL_DAY_DEFAULTS)

def _cic_v40_special_days_today(now: object = None) -> list[dict[str, object]]:
    today_key = _cic_v40_mmdd(_cic_v40_today(now))
    return [d for d in _cic_v40_special_days() if d.get("enabled") and str(d.get("date")) == today_key]

def _cic_v40_active_staff_candidates() -> list[User]:
    try:
        users = _active_staff_users()
    except Exception:
        __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2175")
        users = []
    clean: list[User] = []
    for user in users or []:
        if bool(getattr(user, "celebration_opt_out", False)):
            continue
        clean.append(user)
    return clean

def _cic_v40_birthday_users(now: object = None) -> list[User]:
    if not _cic_v40_setting_bool("celebrations_enabled", True) or not _cic_v40_setting_bool("birthday_enabled", True):
        return []
    today_key = _cic_v40_mmdd(_cic_v40_today(now))
    users: list[User] = []
    for user in _cic_v40_active_staff_candidates():
        birth = _cic_v40_user_date(user, "birth_date", "dogum_tarihi", "date_of_birth")
        if birth and _cic_v40_mmdd(birth) == today_key:
            users.append(user)
    return users

def _cic_v40_service_year(user: object, now: object = None) -> int:
    today = _cic_v40_today(now)
    hire = _cic_v40_user_date(user, "hire_date", "goreve_baslama_tarihi", "ise_baslama_tarihi", "start_date")
    if not hire:
        return 0
    years = today.year - hire.year
    if (today.month, today.day) < (hire.month, hire.day):
        years -= 1
    return max(0, years)

def _cic_v40_anniversary_users(now: object = None) -> list[User]:
    if not _cic_v40_setting_bool("celebrations_enabled", True) or not _cic_v40_setting_bool("work_anniversary_enabled", True):
        return []
    today_key = _cic_v40_mmdd(_cic_v40_today(now))
    users: list[User] = []
    for user in _cic_v40_active_staff_candidates():
        hire = _cic_v40_user_date(user, "hire_date", "goreve_baslama_tarihi", "ise_baslama_tarihi", "start_date")
        if hire and _cic_v40_mmdd(hire) == today_key and _cic_v40_service_year(user, now) > 0:
            users.append(user)
    return users

def _cic_v40_special_day_users(now: object = None) -> list[User]:
    if not _cic_v40_setting_bool("celebrations_enabled", True) or not _cic_v40_setting_bool("special_day_enabled", True):
        return []
    if not _cic_v40_special_days_today(now):
        return []
    mode = get_setting(f"{BASE_KEY}.special_day_recipient_mode", "all_active") or "all_active"
    if mode == "manual":
        try:
            return list(get_recipients().get("staff") or [])
        except Exception:
            __import__("logging").getLogger(__name__).exception("BYS360 SAFE V5: sessiz except loglandi: app/services/corporate_information_center.py:2229")
            return []
    return _cic_v40_active_staff_candidates()

def _recipients_for_task(task_key: str, override_users: list[User] | None = None) -> list[User]:
    """Resolve CIC task recipients through one explicit public layer."""
    if override_users is not None:
        return override_users
    if task_key == "staff_birthday":
        return _cic_v40_birthday_users()
    if task_key == "work_anniversary":
        return _cic_v40_anniversary_users()
    if task_key == "special_day":
        return _cic_v40_special_day_users()
    return _recipients_for_task_base(task_key, override_users)

def _render_template_text(text: str, user: User | None, task_key: str) -> str:
    """Render CIC mail template text through one explicit public layer."""
    rendered = _render_template_text_base(text, user, task_key)
    special_names = ", ".join(str(d.get("name")) for d in _cic_v40_special_days_today()) or "\u00d6zel G\u00fcn"
    service_year = _cic_v40_service_year(user) if user is not None else 0
    extra = {
        "ozel_gun_adi": special_names,
        "hizmet_yili": service_year or "de\u011ferli",
        "kutlama_notu": "Ya\u015f bilgisi g\u00f6sterilmeden, KVKK uyumlu kutlama metni olu\u015fturulmu\u015ftur.",
    }
    for key, value in extra.items():
        rendered = rendered.replace("{" + key + "}", str(value))
    return rendered

__all__ = [
    "_cic_v11_bool",
    "_cic_v11_clean_header",
    "_cic_v11_get_setting_value",
    "_cic_v11_mail_settings",
    "_cic_v11_normalize_email",
    "_cic_v11_send_email_direct",
    "_cic_v40_active_staff_candidates",
    "_cic_v40_anniversary_users",
    "_cic_v40_birthday_users",
    "_cic_v40_bool",
    "_cic_v40_mmdd",
    "_cic_v40_parse_date",
    "_cic_v40_service_year",
    "_cic_v40_setting_bool",
    "_cic_v40_special_day_users",
    "_cic_v40_special_days",
    "_cic_v40_special_days_today",
    "_cic_v40_today",
    "_cic_v40_user_date",
    "_dashboard_counts",
    "_recipients_for_task",
    "_recipients_for_task_base",
    "_render_template_text",
    "_render_template_text_base",
    "_send_task_base",
    "_user_name",
]
