from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
from pathlib import Path
from typing import Any


TARGET_REL = "app/static/js/bys360_assistant_module.js"
HELPER_REL = "app/static/js/bys360_assistant_helpers_v1.js"
P14_D_REL = "reports/quality/bys360_quality_10_10_p14_d_assistant_js_split_readiness_v1.json"

READY_STATUSES = {
    "READY_FOR_OPTIONAL_P14_E",
    "READY_FOR_REVIEWED_P14_E",
    "GROUPED_READY_REVIEW",
}

FORBIDDEN_STATUSES = {
    "NOT_READY_FOR_APPLY",
    "REVIEW_BEFORE_APPLY",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8", errors="ignore"))


def source_by_lines(text: str, start_line: int, end_line: int) -> str:
    lines = text.splitlines()
    if start_line < 1 or end_line < start_line or end_line > len(lines):
        raise SystemExit(f"INVALID_LINE_RANGE: {start_line}-{end_line}")
    return "\n".join(lines[start_line - 1:end_line]).rstrip() + "\n"


def parse_function_signature(source: str, name: str) -> dict[str, str]:
    stripped = source.strip()

    m = re.match(
        r"function\s+" + re.escape(name) + r"\s*\((?P<params>[^)]*)\)\s*\{",
        stripped,
        flags=re.DOTALL,
    )
    if m:
        return {
            "kind": "function_decl",
            "params": m.group("params").strip(),
        }

    m = re.match(
        r"(?:const|let|var)\s+" + re.escape(name) + r"\s*=\s*(?:async\s*)?function\s*\((?P<params>[^)]*)\)",
        stripped,
        flags=re.DOTALL,
    )
    if m:
        return {
            "kind": "var_function",
            "params": m.group("params").strip(),
        }

    m = re.match(
        r"(?:const|let|var)\s+" + re.escape(name) + r"\s*=\s*(?:async\s*)?(?:\((?P<params1>[^)]*)\)|(?P<params2>[A-Za-z_$][\w$]*))\s*=>",
        stripped,
        flags=re.DOTALL,
    )
    if m:
        return {
            "kind": "var_arrow",
            "params": (m.group("params1") or m.group("params2") or "").strip(),
        }

    raise SystemExit(f"FUNCTION_SIGNATURE_NOT_RECOGNIZED: {name}")


def make_wrapper(source: str, name: str) -> str:
    sig = parse_function_signature(source, name)
    params = sig["params"]
    params_for_call = "arguments"

    if sig["kind"] == "function_decl":
        return (
            f"function {name}({params}) {{\n"
            f"  return window.BYS360AssistantHelpersV1.{name}.apply(this, {params_for_call});\n"
            f"}}\n"
        )

    # Preserve const style for non-hoisted originals.
    return (
        f"const {name} = function({params}) {{\n"
        f"  return window.BYS360AssistantHelpersV1.{name}.apply(this, arguments);\n"
        f"}};\n"
    )


def make_helper_file(candidates: list[dict[str, Any]], target_text: str) -> str:
    parts = []
    parts.append("/*")
    parts.append(" * BYS360 Assistant Helpers V1")
    parts.append(" * Generated by P14-E from low-risk helper candidates.")
    parts.append(" * This file contains small helper functions extracted from bys360_assistant_module.js.")
    parts.append(" */")
    parts.append("")
    parts.append("(function (window) {")
    parts.append("  'use strict';")
    parts.append("  const helpers = window.BYS360AssistantHelpersV1 || {};")
    parts.append("")

    for item in candidates:
        name = item["name"]
        source = source_by_lines(target_text, int(item["start_line"]), int(item["end_line"]))
        indented = "\n".join("  " + line for line in source.rstrip().splitlines())
        parts.append(f"  // P14-E helper: {name} lines {item['start_line']}-{item['end_line']}")
        parts.append(indented)
        parts.append(f"  helpers.{name} = {name};")
        parts.append("")

    parts.append("  window.BYS360AssistantHelpersV1 = helpers;")
    parts.append("})(window);")
    parts.append("")
    return "\n".join(parts)


def replace_sources_with_wrappers(target_text: str, candidates: list[dict[str, Any]]) -> tuple[str, list[dict[str, Any]]]:
    lines = target_text.splitlines()
    replacements = []

    # Validate and prepare exact ranges.
    for item in candidates:
        name = item["name"]
        start = int(item["start_line"])
        end = int(item["end_line"])
        source = source_by_lines(target_text, start, end)
        wrapper = make_wrapper(source, name)
        replacements.append({
            "name": name,
            "start": start,
            "end": end,
            "source": source,
            "wrapper": wrapper,
            "source_line_count": len(source.splitlines()),
            "wrapper_line_count": len(wrapper.splitlines()),
        })

    # Apply bottom-up by line range.
    new_lines = list(lines)
    for repl in sorted(replacements, key=lambda x: int(x["start"]), reverse=True):
        start_idx = int(repl["start"]) - 1
        end_idx = int(repl["end"])
        wrapper_lines = repl["wrapper"].rstrip().splitlines()
        new_lines[start_idx:end_idx] = wrapper_lines

    updated = "\n".join(new_lines) + ("\n" if target_text.endswith("\n") else "")
    return updated, replacements


def find_template_updates(project_root: Path) -> list[dict[str, Any]]:
    template_root = project_root / "app" / "templates"
    if not template_root.exists():
        return []

    updates = []
    for path in sorted(template_root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in {".html", ".jinja", ".jinja2"}:
            continue
        text = read_text(path)
        if "bys360_assistant_module.js" not in text:
            continue
        if "bys360_assistant_helpers_v1.js" in text:
            updates.append({
                "path": path.relative_to(project_root).as_posix(),
                "already_has_helper": True,
                "changed": False,
                "new_text": text,
            })
            continue

        lines = text.splitlines()
        new_lines = []
        changed = False
        for line in lines:
            if (not changed) and "bys360_assistant_module.js" in line:
                helper_line = line.replace("bys360_assistant_module.js", "bys360_assistant_helpers_v1.js")
                new_lines.append(helper_line)
                new_lines.append(line)
                changed = True
            else:
                new_lines.append(line)

        updates.append({
            "path": path.relative_to(project_root).as_posix(),
            "already_has_helper": False,
            "changed": changed,
            "new_text": "\n".join(new_lines) + ("\n" if text.endswith("\n") else ""),
        })

    return updates


def basic_js_sanity(text: str) -> dict[str, Any]:
    # Lightweight sanity: brace/paren balance with string/comment awareness.
    state = "code"
    quote = ""
    braces = 0
    parens = 0
    brackets = 0

    i = 0
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if state == "code":
            if ch == "/" and nxt == "/":
                state = "line_comment"
                i += 2
                continue
            if ch == "/" and nxt == "*":
                state = "block_comment"
                i += 2
                continue
            if ch in ("'", '"', "`"):
                state = "string"
                quote = ch
                i += 1
                continue
            if ch == "{":
                braces += 1
            elif ch == "}":
                braces -= 1
            elif ch == "(":
                parens += 1
            elif ch == ")":
                parens -= 1
            elif ch == "[":
                brackets += 1
            elif ch == "]":
                brackets -= 1
            i += 1
            continue

        if state == "line_comment":
            if ch == "\n":
                state = "code"
            i += 1
            continue

        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = "code"
                i += 2
            else:
                i += 1
            continue

        if state == "string":
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                state = "code"
                quote = ""
            i += 1
            continue

    return {
        "brace_balance": braces,
        "paren_balance": parens,
        "bracket_balance": brackets,
        "final_state": state,
        "ok": braces == 0 and parens == 0 and brackets == 0 and state == "code",
    }


def apply(project_root: Path, dry_run: bool, apply_changes: bool) -> None:
    print("BYS360_QUALITY_10_10_P14_E_ASSISTANT_JS_HELPER_SPLIT_APPLY_START")
    print(f"project_root={project_root}")
    print(f"mode={'APPLY' if apply_changes else 'DRY_RUN'}")

    target_path = project_root / TARGET_REL
    helper_path = project_root / HELPER_REL
    p14_d_path = project_root / P14_D_REL

    if not target_path.exists():
        raise SystemExit(f"TARGET_NOT_FOUND: {target_path}")
    if not p14_d_path.exists():
        raise SystemExit(f"P14_D_REPORT_NOT_FOUND: {p14_d_path}")
    if dry_run and apply_changes:
        raise SystemExit("INVALID_FLAGS: dry_run and apply both set")

    p14_d = load_json(p14_d_path)
    readiness_items = list(p14_d.get("readiness_items") or [])
    selected = [
        item for item in readiness_items
        if item.get("readiness") in READY_STATUSES
    ]

    blocked = [
        item for item in readiness_items
        if item.get("readiness") in FORBIDDEN_STATUSES
    ]

    if blocked:
        raise SystemExit("P14_D_HAS_BLOCKED_ITEMS; refusing to prepare apply")
    if not selected:
        raise SystemExit("NO_READY_ITEMS_IN_P14_D")

    # This P14-E intentionally uses exactly P14-D selected candidates.
    target_text = read_text(target_path)
    helper_text = make_helper_file(selected, target_text)
    updated_target, replacements = replace_sources_with_wrappers(target_text, selected)
    template_updates = find_template_updates(project_root)

    helper_sanity = basic_js_sanity(helper_text)
    target_sanity = basic_js_sanity(updated_target)

    if not helper_sanity["ok"]:
        raise SystemExit(f"HELPER_JS_SANITY_FAILED: {helper_sanity}")
    if not target_sanity["ok"]:
        raise SystemExit(f"TARGET_JS_SANITY_FAILED: {target_sanity}")

    before_lines = len(target_text.splitlines())
    after_lines = len(updated_target.splitlines())
    helper_lines = len(helper_text.splitlines())

    report = {
        "mode": "APPLY" if apply_changes else "DRY_RUN",
        "target_file": TARGET_REL,
        "helper_file": HELPER_REL,
        "candidate_count": len(selected),
        "candidates": [
            {
                "name": item.get("name"),
                "start_line": item.get("start_line"),
                "end_line": item.get("end_line"),
                "line_count": item.get("line_count"),
                "readiness": item.get("readiness"),
                "risk": item.get("risk"),
            }
            for item in selected
        ],
        "target_line_count_before": before_lines,
        "target_line_count_after_estimate": after_lines,
        "target_line_delta_estimate": after_lines - before_lines,
        "helper_line_count": helper_lines,
        "replacement_summary": [
            {
                "name": r["name"],
                "start": r["start"],
                "end": r["end"],
                "source_line_count": r["source_line_count"],
                "wrapper_line_count": r["wrapper_line_count"],
            }
            for r in replacements
        ],
        "template_updates": [
            {
                "path": u["path"],
                "already_has_helper": u["already_has_helper"],
                "changed": u["changed"],
            }
            for u in template_updates
        ],
        "helper_sanity": helper_sanity,
        "target_sanity": target_sanity,
        "backup_root": None,
        "next_steps_after_apply": [
            "python -m compileall app scripts",
            "Kalite audit çalıştır",
            "Tarayıcıda BYS360 ana sayfa + asistan paneli smoke test",
            "F12 console kontrol",
            "P14-E sonrası P14-F verification raporu",
        ],
    }

    out_dir = project_root / "reports" / "quality"
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = "applied" if apply_changes else "dryrun"
    report_json = out_dir / f"bys360_quality_10_10_p14_e_assistant_js_helper_split_apply_{suffix}_v1.json"
    report_md = out_dir / f"bys360_quality_10_10_p14_e_assistant_js_helper_split_apply_{suffix}_v1.md"
    helper_preview = out_dir / f"bys360_quality_10_10_p14_e_assistant_helpers_v1_{suffix}_preview.js"
    target_preview = out_dir / f"bys360_quality_10_10_p14_e_assistant_module_{suffix}_preview.js"

    write_text(helper_preview, helper_text)
    write_text(target_preview, updated_target)

    if apply_changes:
        stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_root = project_root / ".quality_backup" / f"p14_e_assistant_js_helper_split_{stamp}"
        report["backup_root"] = str(backup_root)

        for rel in [TARGET_REL]:
            src = project_root / rel
            backup = backup_root / rel
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, backup)

        if helper_path.exists():
            backup = backup_root / HELPER_REL
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(helper_path, backup)

        for update in template_updates:
            if update["changed"]:
                rel = update["path"]
                src = project_root / rel
                backup = backup_root / rel
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, backup)

        helper_path.parent.mkdir(parents=True, exist_ok=True)
        write_text(helper_path, helper_text)
        write_text(target_path, updated_target)

        for update in template_updates:
            if update["changed"]:
                write_text(project_root / update["path"], update["new_text"])

    write_text(report_json, json.dumps(report, ensure_ascii=False, indent=2))

    md = []
    md.append("# BYS360 P14-E Assistant JS Helper Split Apply")
    md.append("")
    md.append(f"- Mod: `{report['mode']}`")
    md.append(f"- Aday sayısı: {len(selected)}")
    md.append(f"- Target satır önce: {before_lines}")
    md.append(f"- Target satır tahmini sonra: {after_lines}")
    md.append(f"- Target delta: {after_lines - before_lines}")
    md.append(f"- Helper satırı: {helper_lines}")
    if report["backup_root"]:
        md.append(f"- Yedek: `{report['backup_root']}`")
    md.append("")
    md.append("## Adaylar")
    md.append("")
    for item in report["candidates"]:
        md.append(f"- `{item['name']}` line {item['start_line']}-{item['end_line']} ({item['line_count']} satır), readiness={item['readiness']}")
    md.append("")
    md.append("## Template Güncellemeleri")
    md.append("")
    if report["template_updates"]:
        for item in report["template_updates"]:
            md.append(f"- `{item['path']}` changed={item['changed']} already_has_helper={item['already_has_helper']}")
    else:
        md.append("- Assistant module script tag bulunamadı; helper dosyası yükleme yolu ayrıca kontrol edilmeli.")
    md.append("")
    md.append("## Kontrol")
    md.append("")
    for item in report["next_steps_after_apply"]:
        md.append(f"- {item}")
    write_text(report_md, "\n".join(md) + "\n")

    print(f"mode={report['mode']}")
    print(f"candidate_count={len(selected)}")
    print(f"target_line_count_before={before_lines}")
    print(f"target_line_count_after_estimate={after_lines}")
    print(f"target_line_delta_estimate={after_lines - before_lines}")
    print(f"helper_line_count={helper_lines}")
    print("BYS360_QUALITY_10_10_P14_E_CANDIDATES")
    for item in report["candidates"]:
        print(f"{str(item['start_line']).rjust(5)}-{str(item['end_line']).ljust(5)} | {str(item['line_count']).rjust(4)} | {item['readiness']} | {item['name']}")
    print("BYS360_QUALITY_10_10_P14_E_TEMPLATE_UPDATES")
    for item in report["template_updates"]:
        print(f"{item['path']} | changed={item['changed']} | already_has_helper={item['already_has_helper']}")
    print(f"helper_sanity_ok={helper_sanity['ok']}")
    print(f"target_sanity_ok={target_sanity['ok']}")
    print(f"assistant_js_helper_split_apply_json={report_json}")
    print(f"assistant_js_helper_split_apply_md={report_md}")
    print(f"helper_preview_js={helper_preview}")
    print(f"target_preview_js={target_preview}")
    print("BYS360_QUALITY_10_10_P14_E_ASSISTANT_JS_HELPER_SPLIT_APPLY_OK")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    apply(Path(args.project_root).resolve(), dry_run=not args.apply, apply_changes=args.apply)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
