
"""Degerlendirme is akisi sabitleri."""
from __future__ import annotations

WORKFLOW_WAITING_LEVEL3 = "bekliyor_3_amir"
WORKFLOW_LEVEL3_DONE = "tamamlandi_3_amir"
WORKFLOW_DRAFT = "taslak_1_amir"
WORKFLOW_SUBMITTED = "gonderildi_2_amir"
WORKFLOW_SEEN = "goruldu_2_amir"
WORKFLOW_RETURNED = "iade_1_amir"
WORKFLOW_RESUBMITTED = "yeniden_gonderildi_2_amir"
WORKFLOW_LEVEL2_DONE = "tamamlandi_2_amir"
WORKFLOW_WITHDRAWN = "geri_cekildi_1_amir"

SUBMITTED_STATES = {
    WORKFLOW_SUBMITTED,
    WORKFLOW_SEEN,
    WORKFLOW_RESUBMITTED,
    WORKFLOW_LEVEL2_DONE,
}
VISIBLE_TO_LEVEL_2 = set(SUBMITTED_STATES)
LEVEL_1_EDITABLE = {WORKFLOW_DRAFT, WORKFLOW_RETURNED, WORKFLOW_WITHDRAWN}

__all__ = [
    'WORKFLOW_WAITING_LEVEL3',
    'WORKFLOW_LEVEL3_DONE',
    'WORKFLOW_DRAFT',
    'WORKFLOW_SUBMITTED',
    'WORKFLOW_SEEN',
    'WORKFLOW_RETURNED',
    'WORKFLOW_RESUBMITTED',
    'WORKFLOW_LEVEL2_DONE',
    'WORKFLOW_WITHDRAWN',
    'SUBMITTED_STATES',
    'VISIBLE_TO_LEVEL_2',
    'LEVEL_1_EDITABLE',
]