"""BYS360 veri modeli paketi.

Bu paket, eski tek parca ``app/models.py`` dosyasinin davranisini koruyarak
modelleri alan bazli modullere ayirir. Disaridan hala
``from app.models import User, PerformancePeriod`` kullanimlari calismaya devam eder.
"""

from .ai_models import (
    AIFeedbackLog,
    AIRecommendation,
    AIRedactionRule,
    AIRequestLog,
    AISummaryCache,
)
from .announcement_popup_models import Announcement, AnnouncementRead
from .audit_misc_models import AuditLog, PerformanceEvaluationHistory
from .base import TimestampMixin, db
from .communication_models import (
    EvaluationPublishLog,
    FeedbackMeeting,
    FeedbackRequest,
    MailLog,
    Message,
    MessageAttachment,
    MessageComment,
    MessageReaction,
    MessageThread,
    MessageThreadParticipant,
    MessageTypingState,
    Notification,
    Survey,
    SurveyAnswer,
    SurveyAssignment,
    SurveyQuestion,
    SurveyQuestionOption,
    SurveyResponse,
)
from .core_models import PersonnelCategory, User, UserMenuPermission
from .feedback_models import (
    FeedbackActionPlan,
    FeedbackAnswer,
    FeedbackCampaign,
    FeedbackCampaignAssignment,
    FeedbackPulseEntry,
    FeedbackQuestion,
    FeedbackQuestionOption,
    FeedbackSubmission,
)
from .hr_models import (
    AttendanceException,
    DelegationAssignment,
    LeaveBalance,
    PersonnelApprovalStation,
    PersonnelAssetAssignment,
    PersonnelAssetTransferLog,
    PersonnelChecklistReview,
    PersonnelChecklistTemplateItem,
    PersonnelDigitalHandoverDocument,
    PersonnelDocument,
    PersonnelDocumentCategory,
    PersonnelDocumentReminderLog,
    PersonnelDocumentUploadBatch,
    PersonnelExitInterview,
    PersonnelExitRiskAssessment,
    PersonnelHandoverItem,
    PersonnelHandoverRecord,
    PersonnelLeave,
    PersonnelLifecycleCase,
    PersonnelLifecycleTask,
    PersonnelPositionHistory,
    PersonnelProcessNote,
    PersonnelSelfServiceRequest,
    PersonnelSelfServiceRequestAttachment,
    PersonnelSelfServiceRequestEscalation,
    PersonnelSelfServiceRequestLog,
    PersonnelSelfServiceRequestSlaPolicy,
    PersonnelSelfServiceRequestTask,
    PersonnelSelfServiceRequestTemplate,
    PersonnelStatusHistory,
)
from .org_models import EmployeeOrgAssignmentHistory, OrganizationUnit, OrganizationUnitVersion
from .performance_archive_models import (
    PerformanceArchivedResult,  # BYS360_PHASE7_PERFORMANCE_ARCHIVE_MODEL_IMPORT
)
from .performance_low_score_models import (
    PerformanceLowScoreProcess,
    PerformanceLowScoreProcessEvent,
)
from .performance_models import (
    AssignmentCoverageLog,
    EvaluationAssignment,
    PerformanceCriteria,
    PerformanceEvaluation,
    PerformanceEvaluationItem,
    PerformanceImportBatch,
    PerformanceImportBatchRow,
    PerformancePeriod,
    PerformancePublishLog,
    PerformanceResultSnapshot,
    PerformanceWeightConfig,
)
from .performance_process_engine_models import (
    PerformanceFeedbackPipelineFlow,
    PerformanceFeedbackPipelineStep,
    PerformancePresidentApproval,
    PerformanceProcessFlow,
    PerformanceProcessFlowStep,
    PerformanceProcessNotification,
    PerformanceScoringHistory,
)  # BYS360_MAINTENANCE_FEEDBACK_STATE_MACHINE_MODEL_IMPORT

# BYS360_CORPORATE_PORTAL_V1_MODEL_IMPORTS
from .portal_models import (
    PortalActivityLog,
    PortalCommentMention,
    PortalCommentReaction,
    PortalGroup,
    PortalGroupMember,
    PortalModerationLog,
    PortalPinnedPost,
    PortalPost,
    PortalPostAttachment,
    PortalPostAudience,
    PortalPostComment,
    PortalPostReaction,
    PortalPostReport,
    PortalProfile,
    PortalSavedPost,
)
from .publication_models import PublicationIssue
from .settings_models import (
    ModuleSetting,
    RoleMenuDefault,
    SettingsChangeLog,
    SystemSetting,
    UnitMenuProfile,
)
from .support_models import (
    SupportCategory,
    SupportFeedbackRating,
    SupportHelpArticle,
    SupportTicket,
    SupportTicketAttachment,
    SupportTicketMessage,
    SupportTicketStatusHistory,
)

# Kaldirilan moduller icin startup uyumluluk katmani

__all__ = [
    "db",
    "TimestampMixin",
    "AuditLog",
    "PerformanceEvaluationHistory",
    "User",
    "UserMenuPermission",
    "PersonnelCategory",
    "RoleMenuDefault",
    "SystemSetting",
    "ModuleSetting",
    "UnitMenuProfile",
    "SettingsChangeLog",
    "Announcement",
    "AnnouncementRead",
    "OrganizationUnit",
    "OrganizationUnitVersion",
    "EmployeeOrgAssignmentHistory",
    "PerformancePeriod",
    "PerformanceCriteria",
    "PerformanceWeightConfig",
    "PerformanceLowScoreProcessEvent",
    "PerformanceLowScoreProcess",
    "PerformanceArchivedResult",
    "PerformanceProcessFlow",
    "PerformanceProcessFlowStep",
    "PerformanceScoringHistory",
    "PerformancePresidentApproval",
    "PerformanceProcessNotification",
    "PerformanceFeedbackPipelineFlow",
    "PerformanceFeedbackPipelineStep",
    "PerformanceEvaluation",
    "PerformanceEvaluationItem",
    "EvaluationAssignment",
    "AssignmentCoverageLog",
    "LeaveBalance",
    "PersonnelAssetAssignment",
    "PersonnelChecklistReview",
    "PersonnelChecklistTemplateItem",
    "PersonnelDocumentReminderLog",
    "PersonnelAssetTransferLog",
    "PersonnelLeave",
    "AttendanceException",
    "DelegationAssignment",
    "PersonnelDocument",
    "PersonnelDocumentCategory",
    "PersonnelDocumentUploadBatch",
    "PersonnelPositionHistory",
    "PersonnelProcessNote",
    "PersonnelStatusHistory",
    "PersonnelSelfServiceRequest",
    "PersonnelSelfServiceRequestAttachment",
    "PersonnelSelfServiceRequestLog",
    "PersonnelSelfServiceRequestTask",
    "PersonnelSelfServiceRequestTemplate",
    "PersonnelSelfServiceRequestEscalation",
    "PersonnelSelfServiceRequestSlaPolicy",
    "PersonnelLifecycleCase",
    "PersonnelLifecycleTask",
    "PersonnelExitInterview",
    "PersonnelHandoverRecord",
    "PersonnelHandoverItem",
    "PersonnelApprovalStation",
    "PersonnelDigitalHandoverDocument",
    "PersonnelExitRiskAssessment",
    "FeedbackRequest",
    "MailLog",
    "EvaluationPublishLog",
    "FeedbackMeeting",
    "PerformanceResultSnapshot",
    "PerformanceImportBatch",
    "PerformanceImportBatchRow",
    "PerformancePublishLog",
    "MessageThread",
    "MessageThreadParticipant",
    "Message",
    "MessageReaction",
    "MessageComment",  # BYS360_MESSAGE_INTERACTIONS_V1
    "MessageTypingState",
    "Notification",
    "Survey",
    "SurveyQuestion",
    "SurveyQuestionOption",
    "SurveyAssignment",
    "SurveyResponse",
    "SurveyAnswer",
    "MessageAttachment",
    "PublicationIssue",
    "FeedbackCampaign",
    "FeedbackQuestion",
    "FeedbackQuestionOption",
    "FeedbackCampaignAssignment",
    "FeedbackSubmission",
    "FeedbackAnswer",
    "FeedbackPulseEntry",
    "FeedbackActionPlan",
    "SupportCategory",
    "SupportHelpArticle",
    "SupportTicket",
    "SupportTicketMessage",
    "SupportTicketAttachment",
    "SupportTicketStatusHistory",
    "SupportFeedbackRating",
    "AIRequestLog",
    "AIRecommendation",
    "AIFeedbackLog",
    "AIRedactionRule",
    "AISummaryCache",
    # BYS360_CORPORATE_PORTAL_V1_MODEL_EXPORTS
    "PortalProfile",
    "PortalGroup",
    "PortalGroupMember",
    "PortalPost",
    "PortalPostAudience",
    "PortalPostAttachment",
    "PortalPostReaction",
    "PortalPostComment",
    "PortalCommentReaction",
    "PortalCommentMention",
    "PortalSavedPost",
    "PortalPostReport",
    "PortalModerationLog",
    "PortalPinnedPost",
    "PortalActivityLog",
]

# Compatibility guard.
