"""BYS360 veri modeli paketi.

Bu paket, eski tek parca ``app/models.py`` dosyasinin davranisini koruyarak
modelleri alan bazli modullere ayirir. Disaridan hala
``from app.models import User, PerformancePeriod`` kullanimlari calismaya devam eder.
"""

from .base import TimestampMixin, db
from .audit_misc_models import AuditLog, PerformanceEvaluationHistory
from .core_models import PersonnelCategory, User, UserMenuPermission
from .settings_models import RoleMenuDefault, SystemSetting, ModuleSetting, UnitMenuProfile, SettingsChangeLog
from .announcement_popup_models import Announcement, AnnouncementRead
from .org_models import EmployeeOrgAssignmentHistory, OrganizationUnit, OrganizationUnitVersion
from .performance_models import (
    AssignmentCoverageLog,
    EvaluationAssignment,
    PerformanceCriteria,
    PerformanceEvaluation,
    PerformanceEvaluationItem,
    PerformanceImportBatch,
    PerformanceImportBatchRow,
    PerformancePeriod,
    PerformancePublishLog,
    PerformanceResultSnapshot,
    PerformanceWeightConfig,
)
from .performance_low_score_models import (
    PerformanceLowScoreProcess,
    PerformanceLowScoreProcessEvent,
)
from .performance_archive_models import PerformanceArchivedResult  # BYS360_PHASE7_PERFORMANCE_ARCHIVE_MODEL_IMPORT
from .performance_process_engine_models import (
    PerformanceProcessFlow,
    PerformanceProcessFlowStep,
    PerformanceScoringHistory,
    PerformancePresidentApproval,
    PerformanceProcessNotification,
    PerformanceFeedbackPipelineFlow,
    PerformanceFeedbackPipelineStep,
)  # BYS360_CLAUDE_FEEDBACK_STATE_MACHINE_MODEL_IMPORT
from .hr_models import (
    AttendanceException,
    DelegationAssignment,
    LeaveBalance,
    PersonnelAssetAssignment,
    PersonnelChecklistReview,
    PersonnelChecklistTemplateItem,
    PersonnelDocumentReminderLog,
    PersonnelAssetTransferLog,
    PersonnelDocument,
    PersonnelDocumentCategory,
    PersonnelDocumentUploadBatch,
    PersonnelLeave,
    PersonnelPositionHistory,
    PersonnelProcessNote,
    PersonnelStatusHistory,
    PersonnelSelfServiceRequest,
    PersonnelSelfServiceRequestAttachment,
    PersonnelSelfServiceRequestLog,
    PersonnelSelfServiceRequestTask,
    PersonnelSelfServiceRequestTemplate,
    PersonnelSelfServiceRequestEscalation,
    PersonnelSelfServiceRequestSlaPolicy,
    PersonnelLifecycleCase,
    PersonnelLifecycleTask,
    PersonnelExitInterview,
    PersonnelHandoverRecord,
    PersonnelHandoverItem,
    PersonnelApprovalStation,
    PersonnelDigitalHandoverDocument,
    PersonnelExitRiskAssessment,
)
from .ai_models import AIRequestLog, AIRecommendation, AIFeedbackLog, AIRedactionRule, AISummaryCache
from .feedback_models import (
    FeedbackActionPlan,
    FeedbackAnswer,
    FeedbackCampaign,
    FeedbackCampaignAssignment,
    FeedbackPulseEntry,
    FeedbackQuestion,
    FeedbackQuestionOption,
    FeedbackSubmission,
)
from .support_models import (
    SupportCategory,
    SupportFeedbackRating,
    SupportHelpArticle,
    SupportTicket,
    SupportTicketAttachment,
    SupportTicketMessage,
    SupportTicketStatusHistory,
)
from .publication_models import PublicationIssue
from .communication_models import (
    EvaluationPublishLog,
    FeedbackMeeting,
    FeedbackRequest,
    MailLog,
    Message,
    MessageAttachment,
    MessageReaction,
    MessageThread,
    MessageThreadParticipant,
    MessageTypingState,
    Notification,
    Survey,
    SurveyAnswer,
    SurveyAssignment,
    SurveyQuestion,
    SurveyQuestionOption,
    SurveyResponse,
)

# BYS360_CORPORATE_PORTAL_V1_MODEL_IMPORTS
from .portal_models import (
    PortalProfile,
    PortalGroup,
    PortalGroupMember,
    PortalPost,
    PortalPostAudience,
    PortalPostAttachment,
    PortalPostReaction,
    PortalPostComment,
    PortalCommentReaction,
    PortalCommentMention,
    PortalSavedPost,
    PortalPostReport,
    PortalModerationLog,
    PortalPinnedPost,
    PortalActivityLog,
)

# Kaldirilan moduller icin startup uyumluluk katmani

__all__ = [
    "db",
    "TimestampMixin",
    "AuditLog",
    "PerformanceEvaluationHistory",
    "User",
    "UserMenuPermission",
    "PersonnelCategory",
    "RoleMenuDefault",
    "SystemSetting",
    "ModuleSetting",
    "UnitMenuProfile",
    "SettingsChangeLog",
    "Announcement",
    "AnnouncementRead",
    "OrganizationUnit",
    "OrganizationUnitVersion",
    "EmployeeOrgAssignmentHistory",
    "PerformancePeriod",
    "PerformanceCriteria",
    "PerformanceWeightConfig",
    "PerformanceLowScoreProcessEvent",
    "PerformanceLowScoreProcess",
    "PerformanceArchivedResult",
    "PerformanceProcessFlow",
    "PerformanceProcessFlowStep",
    "PerformanceScoringHistory",
    "PerformancePresidentApproval",
    "PerformanceProcessNotification",
    "PerformanceFeedbackPipelineFlow",
    "PerformanceFeedbackPipelineStep",
    "PerformanceEvaluation",
    "PerformanceEvaluationItem",
    "EvaluationAssignment",
    "AssignmentCoverageLog",
    "LeaveBalance",
    "PersonnelAssetAssignment",
    "PersonnelChecklistReview",
    "PersonnelChecklistTemplateItem",
    "PersonnelDocumentReminderLog",
    "PersonnelAssetTransferLog",
    "PersonnelLeave",
    "AttendanceException",
    "DelegationAssignment",
    "PersonnelDocument",
    "PersonnelDocumentCategory",
    "PersonnelDocumentUploadBatch",
    "PersonnelPositionHistory",
    "PersonnelProcessNote",
    "PersonnelStatusHistory",
    "PersonnelSelfServiceRequest",
    "PersonnelSelfServiceRequestAttachment",
    "PersonnelSelfServiceRequestLog",
    "PersonnelSelfServiceRequestTask",
    "PersonnelSelfServiceRequestTemplate",
    "PersonnelSelfServiceRequestEscalation",
    "PersonnelSelfServiceRequestSlaPolicy",
    "PersonnelLifecycleCase",
    "PersonnelLifecycleTask",
    "PersonnelExitInterview",
    "PersonnelHandoverRecord",
    "PersonnelHandoverItem",
    "PersonnelApprovalStation",
    "PersonnelDigitalHandoverDocument",
    "PersonnelExitRiskAssessment",
    "FeedbackRequest",
    "MailLog",
    "EvaluationPublishLog",
    "FeedbackMeeting",
    "PerformanceResultSnapshot",
    "PerformanceImportBatch",
    "PerformanceImportBatchRow",
    "PerformancePublishLog",
    "MessageThread",
    "MessageThreadParticipant",
    "Message",
    "MessageReaction",
    "MessageTypingState",
    "Notification",
    "Survey",
    "SurveyQuestion",
    "SurveyQuestionOption",
    "SurveyAssignment",
    "SurveyResponse",
    "SurveyAnswer",
    "MessageAttachment",
    "PublicationIssue",
    "FeedbackCampaign",
    "FeedbackQuestion",
    "FeedbackQuestionOption",
    "FeedbackCampaignAssignment",
    "FeedbackSubmission",
    "FeedbackAnswer",
    "FeedbackPulseEntry",
    "FeedbackActionPlan",
    "SupportCategory",
    "SupportTicket",
    "SupportTicketMessage",
    "SupportTicketAttachment",
    "SupportTicketStatusHistory",
    "SupportFeedbackRating",
    "AIRequestLog",
    "AIRecommendation",
    "AIFeedbackLog",
    "AIRedactionRule",
    "AISummaryCache",
    # BYS360_CORPORATE_PORTAL_V1_MODEL_EXPORTS
    "PortalProfile",
    "PortalGroup",
    "PortalGroupMember",
    "PortalPost",
    "PortalPostAudience",
    "PortalPostAttachment",
    "PortalPostReaction",
    "PortalPostComment",
    "PortalCommentReaction",
    "PortalCommentMention",
    "PortalSavedPost",
    "PortalPostReport",
    "PortalModerationLog",
    "PortalPinnedPost",
    "PortalActivityLog",
]

# BYS360_CLAUDE_V13_P1_WAITRESS_MODEL_IMPORT_HOTFIX_EXPORTS
